# Possible Syllabus

This syllabus is based in part on James Henry Collins PhD, and Anne-Marie Cowe's Philosophy of Fiction class at The University of Edinburgh in 2015.

When attempting to understand fiction, it is generally helpful to try and understand the different ways we use fiction. As such, an interdisciplinary approach is better than a strictly topically constricted one. An interdisciplinary approach then will include topics found in aesthetics, epistemology, metaphysics, and the Philosophy of language and mind. It is organized differently however, preferring to prioritize the relation between fiction among the different philosophical disciplines.

## Aesthetics

## Philosophy of Mind

## Metaphysics

## Metaethics

## Philosophy of Science

## Philosophy of Language

## 

## Aesthetics

## Philosophy of Mind

## Metaphysics

## Metaethics

## Philosophy of Science

## Philosophy of Language

## 

## Aesthetics

## Philosophy of Mind

## Metaphysics

## Metaethics

## Philosophy of Science

## Philosophy of Language

## 
