
# Relational Intuition {#rel-int}

Given the fact about our ability to empathize with others, narrative would be an important part of human society in that it gives us insight into who the members are that comprise the communities we live in. It enables us to share their perceptions, phenomenal states and our ability to do so is an important feature of our cognitive faculties and how we learn various facts about the world. Because of the contributions of our imaginations for potentially fostering empathy then, the view that narrative literature may be useful for teaching ethics is important [@choo21]. For instance, literature is important for fostering the kinds of dispositions central to an intellectually autonomous civil populace, and empathy. Through such rational autonomous and free thought, a civilization can ward off institutional intolerance, discrimination, and violence. We can imagine what emotional states would be experienced by a given character and from this, infer what may be their own perceived possible course of action in some hypothetical situation [@des15]. We can develop relationships with other members of a broader society. Assuming that a particular crime family recently lost a son to territorial violence, we may be justified in thinking that a given member of this family is experiencing pain and anger. As such, we might think that many following actions would be governed by a motivation rooted in a feeling of vengeance, or a similar emotion. Nevertheless, there are those who give reason to deny the necessary correlation between ethics and narrative [See @gilm20; @mora94; @curr20]. Before looking at what is of central concern here, it will be important to look at some theories of emotions as prescribed in the reading of a given narrative and what this means for a narrative’s audience. In this chapter, I argue that deference is not the best state of affairs. I first show a number of cases presented by McGrath wherein we may accept deference. These cases will motivate our intuition about the importance of what I go on to call sensitivity to reason, a kind of moral understanding.

## Intuition Cases

Cases one through three seem plausible and likely are. However they assume anti egalitarianism. I argue that this means that we treat moral expertise the same way we do non-moral. I then highlight situations wherein individuals reject deferring their moral judgments. We often treat these individuals as moral exemplars. I argue that this shows that we care about one's sensitivity to moral particulars.

### Case 1 {-}

> Initially, Al suspends judgment about whether $\phi$ ing is wrong, because he knows that he is ignorant about various non-moral facts about $\phi$ ing and its consequences that he takes to be bear on its morality. He then learns that his wife is morally opposed to $\phi$ ing. Because he knows that he and his wife share the same basic moral outlook but that she is well informed about the relevant non-moral facts, he defers to her judgment.

This does not seem to motivate the concern felt above. Al is not depending on his wife's moral views but rather her non-moral views. We should not think that this is a case of moral deference. The concern about the existence of moral properties is not raised.

The following case is a more interesting one than the previous. Here, Al perhaps rightly assumes that were he to have the same information as his wife, he too would arrive at the same conclusion as her. For instance, Allan @gibb92 in a defense of contextual authority, argues that I might defer to another on the assumption that we share the same norms and standards when it comes to evidence gathering [e.g., p. 174]. As such, I am reasonably confident that were I to put in the same time and effort, that I too would come to the same conclusion.

### Case 2 {-}

> The situation is the same as in Case 1, except that Al doesn't suspend judgment. He determines that $\phi$-ing is morally permissible on the basis of the information available to him. He reverses his judgment upon learning that his wife thinks otherwise, because he reasonably assumes that the fact that they arrived at different views is due to the fact that she has relevant non-moral information that he lacks.

However, once again, Al is not deferring his moral views to his wife, but rather upon recognizing that he and his wife share the same views, accepts her view as his own since it is likely that were he to think on the matter, his conclusion would be the same as his wife's. Even if there are moral properties, both Al and his wife have equal access to them.

### Case 3 {-}

In the more interesting case, Al reverses his judgment upon learning what his wife thinks. There can be several reasons for this.

#### Case 3.1 {-}

A more problematic case is one wherein Al's moral sensibilities are compromised in some way. If his moral sensibilities are compromised, then he will not be able to recognize the properties of wrongness on some actions and behaviors. Here, it is not necessarily a question about non-moral facts, but moral ones which Al does not and cannot have access to the relevant moral properties.

> Al knows that he has all of the relevant non-moral information that his wife has, and that they share the same basic moral outlook. If he made up his own mind, Al would judge that $\phi$-ing is morally permissible. Nevertheless, he defers to his wife's view that $\phi$-ing is wrong, because with respect to this particular issue, his judgment is compromised in a way that hers is not.

@enoc14 says of the third class of cases that Al would be morally commendable. In fact, in recognizing that one is morally compromised in some way, one has a duty, in the interest of fulfilling our obligation to prevent harm, to defer in all cases wherein we are not absolutely certain about what would be the morally right thing to do. As such, perhaps 3 does not necessarily reflect the problem that most find in cases of moral deference. However, we may think that even here Al has fulfilled his duty in exercising his moral conscience. But because of the communal nature of knowledge, there are moments wherein we do defer at least some of our judgments because of real limitations in our perceptual faculties. For instance, we will leave it up to the ultrasound technician to tell us whether the blip on the screen is a boy or girl. To think otherwise would be unnecessarily individualistic.

However, such concerns may fall on questions about Al's moral judgment in a particular area. For instance, maybe Al does not know the correct moral norms in India whereas his wife does and he therefore defers to her when in India. However, an even more controversial case would be one wherein Al defers all of his moral judgments to his wife because of a more general worry about his insensibility.

#### Case 3.2 {-}

The first reason why one may defer to another is because two people have the same moral outlook and so their judgments are the same. However, the deferrer leaves it up to the deferred to identify the pertinent moral facts. The case above reflects the best example of problematic moral deference but it still does not reflect true moral deference since a social epistemologist may very well accept moral deference at least in some cases.

> Your friend Al informs you that he is passionately opposed to eating meat because doing so is immoral. You ask him why he thinks this: is there, for example, some particular argument against the practice that he finds convincing? He replies that there is no such argument. In fact, the arguments that are typically offered against eating meat strike him as weak and unconvincing: as far as his own moral sensibility is concerned, doing so seems morally unproblematic. For this reason, if he were to make up his own mind, he would believe that eating meat is perfectly permissible. Nevertheless, he firmly believes that doing so is wrong, and indeed, takes himself to know that it is. His staunch opposition to eating meat is due to the fact that his wife has told him that doing so is wrong, and his belief that, in general, her moral judgment is more reliable than his, he has adopted a general practice of adopting her moral view in any case in which her expressed view conflicts with what he would judge to be the case if he made up his own mind. His opposition to eating meat, he reports, is simply a manifestation of intellectual humility within the moral domain. [@mcgr19]

What follows is a closer look at what true moral deference looks like. In the following, I will show that even though in some cases, we do defer and deference is better than any alternative, this is not a default moral position. So we must distinguish between a person who does not know the particular cultural norms of a given community, someone who cannot exercise their own moral capacities, and someone who chooses not to exercise their own moral capacities. This person is not concerned with objective morality, but rather is more concerned with something other than moral truth than they are with moral truth.

## Egalitarianism

It is one thing to think that one should defer because of a problem with their moral senses. Even though deference may be commendable given the alternative, this is still not the best state of affairs. First, there is reason to believe that the best realist views are egalitarian. Mind independent moral facts are equally accessible to any normal adult human being leaving no room for moral expertise and rendering moral deference otiose. This view at first seems implausible because we often attribute knowledge to experts in non-moral cases, even cases like mathematics, wherein mind independent non-moral facts are equally accessible to any normal adult human being. However, assuming there are moral experts like mathematicians, when we defer to them, we fail to act on those reasons that make the action right [@mark10]. Second, we should raise concerns about comparing deference in cases of mathematics to moral cases.

### Case 5 {-}

There are several points about moral expertise that should be noted here. One rejection of moral expertise, is that unlike non-moral expertise, moral theory is not a theoretical science. If this is true, it would then explain moral particularism wherein the right action is right only in context to the situation. Of course one could also reject moral particularism, but importantly, moral particularism is not all that different from non-moral particularism.

> Al has all of the non-moral information relevant to the morality of $\phi$ -ing that his wife has, and he has no reason to think that his own judgment is impaired or compromised, either with respect to this issue or more generally. Indeed, he regards himself as a perfectly competent (although fallible) judge of moral matters. On the basis of this information and his own careful consideration of the issue, it seems to him that $\phi$ -ing is perfectly permissible. Nevertheless, he judges that $\phi$ -ing is wrong because he knows that this is what his wife thinks, and he has adopted a general practice of deferring to her moral views in cases in which he is disposed to judge differently. He has adopted this policy because he believes that his wife in general, is a *moral expert*. (72-73)

Physicists often have a command of a different set of facts than a biomedical engineer. Like directions and other non-moral facts, actions are also morally right in a given context. Two people walking towards a library from opposite directions would take two different ways there in the same way that lying may be morally right to prevent a murderer from harming a family member but not to your spouse. Experts are generally experts in a particular domain, in part, because of their ability to apply general rules to that particular domain. We might try the following distinction to explain moral expertise instead.

```{.remark}

A full-blooded expert about X is not merely someone who knows more about X than the non-expert, but someone to whom it is rational for the non-expert to defer in arriving at her views about X.

```

The strongest point against moral expertise is egalitarianism. The above says nothing about universal laws and their applications. Experts in two different fields may indeed have access to the same set of facts, but because of their applications, one expert is deferred to for questions about physics while the other for biomedical engineering. While there may be experts in mathematics, it is likely that the non-expert, given enough time and effort, could come to the same conclusions as the expert. It is not important enough for most of our purposes however, for every non-expert to arrive at a truth in mathematics on their own. But this does not necessarily follow in moral cases. It is reasonable to think that regardless of the time and effort required, the moral non-expert ought to exercise the same capacities as the moral expert in arriving at the same conclusions as the moral expert.

McGrath draws a distinction between the right or wrong making features of an action, and one's evidence for believing that a certain act is right or wrong.

> Even if the evidence that alerts me to the fact that what I'm doing is wrong is a certain characteristic feeling or pleasure or enjoyment, the fact that I'm experiencing that pleasure or enjoyment is not a plausible candidate for being the feature that *makes* the action wrong. In general, evidence or reasons to believe that a certain action is right (or wrong) are not the same as reasons that make that action right (or wrong). [@mcgr19, 95]

A moral expert is someone whose testimony justifies the non-expert's beliefs because the moral non-expert is incapable of perceiving for themselves what the right thing to do is. But in moral cases, it is the sentiment and motivation behind an action that justifies an agent's moral beliefs. McGrath assumes that sentimentalists assume that the right or wrong making features of an action, are the feelings and perception that that action raise. But this is not the case, rather it is the exercise of one's moral sensibilities that is central to one's moral belief or moral behavior.

Whether or not moral testimony can be used to fine-tune one's moral perception is important, however, it is not as important as the fact that the dominant criticisms of moral testimony operate on an assumption that moral testimony cannot be used to fine-tune one's moral perception. Another way to think of moral experts then, is in reference to those individuals whose moral testimony can fine-tune our moral sensibilities. They help us to see the moral particulars relevant in a claim's truth or falsehood.

### Understanding and Right Reason {-}

While moral testimony confers moral knowledge, what we truly need in cases of moral deference is moral understanding. Unlike knowing a proposition *p*, understanding a proposition involves more than just *knowing that* *p* is true, but also *knowing why* *p* is true.^[@hopk07; @hill09; @nick01]. @howa18 and @call18d accept this view but explain the asymmetry differently than do Hills, Hopkins, and Nickel.^[Also see @stum10, 40--63.] Knowing *why p* in a moral case requires a characteristic feeling. For instance, compare the statement *how do you feel about capital punishment* with the statement *how do you feel about trees?* Moral testimony involves more than just a cognitive understanding. There is something more complex regarding our views about capital punishment than our views about trees.^[This example was taken from @prin07, 13. Also see @howa18.] While I cannot sufficiently address the entirety of moral cognition, I can focus on a more specific kind of moral cognition that has not received as much attention, namely on non-cognitive moral understanding, via affect. Affect here exemplifies our deepest desires and cares marking such concerns more central to our lives. Some have called this emotionism. According to it, our feelings are constitutive of what it means to value something. Moral values are a specific kind of valuing denoted by what we feel strongly about in the moral realm.^[See @prin07] Because we care about actions by some humans towards other humans, morality is a strongly held value.

### Epistemic Agency with Respect to Moral Testimony {-}

According to the traditional pessimists, we all possess a moral conscience, and its exercise is not merely a right, but a duty [@wolf98]. But there can be complications with this view. For one, it is unnecessarily individualistic. The view does not correlate with current epistemological views, namely that knowledge is a more communal enterprise than previously recognized. Therefore, some optimists on the other hand do not see the asymmetry as at all problematic because of this recognition of the communal nature of knowledge.

Following this general criticism of the sociability of knowledge, some argue that there are those who see the moral contours of a situation more clearly than others. For instance, one way to understand the relation between our emotions and what we value, is to argue that our emotions are a sort of perception and moral facts, such as moral goodness and moral rightness, are a property of moral behavior and actions. Some have better perceptive abilities than others. Sometimes these perceptual capacities are exercised better in particular instances, such as a gender minority may be more sensitive to transphobic assertions. Sometimes they are exercised better moral generally, someone who is sensitive to perceived instances of injustice. Why shouldn't they pass along what they know [@watt82; @ansc81; Walsh; @coad94; @jone99]?

Robert Hopkins in @hopk07 argues that moral testimony is unusable. While testimony can make moral knowledge available, there is a further norm that makes relying on it illegitimate.

> They remove grounds for thinking that suitable Humean arguments will not be available to recipients of moral testimony" [627]. While one may have knowledge, what is needed is to act on reasons [Humean thesis (*Inquiry*, ch. IX)]. ". . . it attempts to find reasons, available to the recipient of testimony, for thinking that what she is told is true [627].

While reductionists treat testimony as a kind of inductive evidence, an anti-reductionist thinks that testimony's epistemic efficacy at yielding knowledge does not depend on the availability to the recipient of any argument. Rather than preserving the recipient's epistemic autonomy by offering her grounds of her own for believing the claims she is offered, such positions see the recipient's epistemic position as directly dependent on that of her informants. An agent is not given any credit for their beliefs.^[For instance @reid94; @mcdo94; @burg93.] Testimony then either is, or is not counted as evidence in the same way that perception is. However, testimony can be used to fine-tune one's sensibility improving their ability to perceive a proposition as true.

Imagine Johnny. Johnny was raised in a good home that believed in equality and treating others with respect regardless of who they were. During a particularly troublesome freshman year in secondary school, Johnny fell in with the wrong crowd. However, whenever his new friends would make a sexist or racist remark, Johnny would feel apprehensive. Although he would try to brush away such feelings, laughing when everyone else did, he could never quite appreciate their jokes in the same way that everyone else seemed to.

### The Asymmetry {-}

A problem emerges in that though the word of others can be a source of moral knowledge, the process is deficient in a way dissimilar to non-moral cases. Testimony is a source of knowledge but the question is not how do we learn from moral testimony? What is wrong with the Humean argument about moral belief is that it fails to give one a grasp of the *moral* reasons for that belief [@hopk07, 630]. The Requirement here then, is having the right to a moral belief requires one to grasp the *moral* grounds for it. But why? What "deeper demand . . . imposes The Requirement on moral thinking?" [@hopk07, 633].

Therefore, the problem with moral testimony as traditionally construed then---unlike non-moral testimony---is that it does not confer what we truly care about regarding moral behavior because we do care about the affects behind one's actions, our affect is conceived of as a motivation for acting. For instance, we might think that a well-lived life then, means experiencing appropriate affective states in the right contexts. @nuss01i motivates an analogous view.^[To be discussed in section 4.] The implication is that given the importance of moral understanding over and above that of moral knowledge, Mary should not defer her moral judgments. Her deference in the moral domain represents her lack of moral understanding and subsequent actions therefore, would be void of moral worth [@hill09, 94; @sliw12, 186]. Another position however, is one offered by @enoc14. Mary is actively committing a wrong action by engaging in risky behavior. An analogous sense of wrong doing may be exemplified by a medical doctor pursuing a novel medical procedure rather than deferring to an expert. For instance, in Flaubert's *Madame Bovary*, Charles Bovary performs a medical procedure with disastrous consequences.^[ Some other examples of non-morally worthy right action can be seen in @arpa04's discussion of Flaubert's Madame Bovary, 67--68.] However this is not as completely analogous because for Enoch, this risk is just as bad as the potential consequences. Importantly, what Enoch identifies as *opaque* evidence, on a knowledge first account, I remark as central to moral understanding and argue that it is less opaque than Enoch supposes. Enoch places weight on the outcome, but for attributions of moral worth, we do care more about one's engagement with moral reasons. We care more about the effort than we do the outcome.

Here, we should follow the example set by @wolf98. Evoking the communal nature of knowledge, Wolff asks us to imagine the concept of the state. A state is a group of persons who have and exercise supreme authority within a given territory. To claim this authority means to claim the right to be obeyed. This authority is shared by the members of the state. As such, each member of the state, has the right, in a shared capacity, to exercise authority in the territory occupied by that state. Therefore, this authority is normative in that it equates to an ultimate authority over all matters of the state.

Because of the shared nature of this authority, a state's members do not merely have an obligation to obey the state, but also good reasons to do so. Here, the consequences of defiance here, outweigh the indignity of submission. Consequences imply that a state's members are metaphysically free and on account of their freedom, have a responsibility to exercise their freedom which is done through reason. As such, men are responsible for their actions and this responsibility implies autonomy. So the authority of the state requires that its members exercise their autonomy. Taking and forfeiting moral responsibility needs strong justification. Though there are cases in which it is justified that one gives up their autonomy (independence); the defining mark of the state is authority and the consequent primary obligation of man is the exercise of autonomy given that they comprise this authority.

While one may have knowledge given their receipt of another's testimony, what is needed is to act on reasons. According to the Humean thesis (*Inquiry*, ch. IX)], a moral agent " . . . attempts to find reasons, available to the recipient of testimony, for thinking that what she is told is true" [627]. However, others [@reid94; @mcdo94; @burg93.] think that testimony's epistemic efficacy at yielding knowledge does not depend on the availability to the recipient of any argument. Rather than preserving the recipient's epistemic autonomy, by offering her grounds of her own for believing the claims she is offered, such positions see the recipient's epistemic position as directly dependent on that of her informants [anti-reductionism]. But this means that moral testimonial transactions work differently than the non-moral case.

As moral agents, having the gift of free and autonomous choice, we have an obligation to take responsibility for our action, to exercise our free choice. We may think of this as exercising the ability to justify our beliefs through the exercise of reason. A virtue of McGrath's account, is that she argues that this argument fails to distinguish between *justifying and being justified* [@mcgr19, 63].

However, the moral worth of an action depends on whether a person understands the rightness or wrongness of her action. This is similar to the demands we place on researchers. McGrath is only concerned with the transfer of moral knowledge whereas the pessimists care about moral worth. "One might know that some moral claim is true even if one is not in a position to understand why it is, and genuine moral understanding is often a more demanding intellectual achievement than moral knowledge [@mcgr19, 96]."

In some non-moral cases, understanding is more valuable than knowledge. For instance in cases of scientific expertise, it would not be enough for a chemist to merely know from testimony the nature of a given compound, she will be expected to know what experiments are needed to confirm the thesis and whether these will do so. In moral cases, like in cases of scientific expertise, understanding is more important than knowledge. Those who think that requiring critical reflection of a moral proposition are demanding more from persons in the moral realm than they would in the non-moral realm. Following Laura @call18d; and Robert @howa18, this means that moral worth is conferred when they have the right kind of emotional response in a given context.

The following is a defense of the view that moral worth is conferred when an agent non-cognitively understands why a moral claim is true.

```{.remark}

Given sentimentalist accounts of morality, moral goodness/badness is grounded in our emotional responses. Emotional responses are grounded in bodily perceptions and correspond to action tendencies.

```

```{.remark}

Our concepts of good / bad are derived from our experiences and our approval or disapproval of an action is grounded in our concepts of good / bad.

```

```{.remark}

Therefore, given that the moral worth of an action is grounded in our approval or disapproval of an action, moral testimony is successful when it grounds our emotional responses in the correct way.

```

Let us now turn to sentimental pessimists and optimists within the debate on moral testimony. Sentimental pessimists argue that moral testimony appears useless because it does not confer what we truly care about regarding moral worth. Morally right actions, as actions, are a right response to moral reasons. However motivation, a point I argue has been embedded in the criticisms against moral testimony, is that one can be in a state of *being* justified, for instance by having the right sentiment and affect and being moved by it.

## A Sensitivity to Reason

The morally relevant connection between emotion and moral worth is often obscure as these relate to *right reason*. For one, many philosophers already conceive of emotion as a form of perception [@audi10; @prin07, esp. 87--137]. Therefore, to recognize the role of moral knowledge in moral understanding will require an acceptance of this relation between emotion and moral worth, where an individual's emotions are merely an important response on the part of the individual to something in their environment. For instance, if we understand knowledge rather than justification as more basic and perceptual, then our affects regarding moral propositions will be that much more pertinent to our moral beliefs. For instance @mcgr19 uses a knowledge first account of knowledge, though hers does not seem to consider that affect as a perception is a source of knowledge. A part of the worry here, is that there is a high standard for belief to count as knowledge for some epistemic agent. However, according to knowledge first epistemology, knowledge is prior to belief. As such, we might think that there are some things that are known prior to beliefs, given that justification is not a central component in the relationship between belief and knowledge, such as perceptions.^[See @will00; also see @mira15 and @mcgr19. E.g., @mcgr19, 63 argues that even if knowledge does not justify some beliefs, or beliefs more generally, the moral inheritance view still stands. Possibly because in light of a child's inability to critically reflect on knowledge she has, we might have reason to attribute justification to those beliefs that she holds.]

Callahan, Fletcher, Howard and Enoch argue that the moral worth of a behavior corresponds to the right affective states underlying the action. Following this, they argue that the problem with moral testimony is that testimony is not a good way of acquiring appropriate motivational and emotive states.

Therefore, one way to expand our conceptions of moral testimony, requires that we understand emotion as a type of moral perception and testimony a way of fine-tuning one's faculties of moral perception. Doing so shows us that rejecting moral testimony may be a hasty move. It also increases our motivation to revisit our conceptions of what is moral testimony. Additionally, this move aligns with a knowledge first epistemology. Accordingly, what we know justifies what we believe, lying in the realms often associated with our perceptions.^[For knowledge first views, see @will00.]

I may come to know the right course of action at a given moment solely because of another's account of moral testimony. Testimony can make moral knowledge available. Therefore it is not the case that moral knowledge from testimony is unavailable. However there is a further norm that makes relying on this knowledge illegitimate.^[See @hill09, 627]. “The puzzle about moral testimony, then, is why you have reason neither to defer to moral experts nor to trust moral testimony, if indeed you do not, given that taking moral advice is obviously acceptable and may even sometimes be required [@hill09, 97].” I have given reason to believe that not only is it a better state of affairs, that we come to the right moral beliefs on our own, but that we have an overriding obligation to work towards this state of affairs.

Merely appreciating some action as being the right thing to do will not suffice for moral worth as long as one lacks more direct motivation by the reasons that make the action right [@call18d, 443].^[E.g. see @nick01; and for recent discussions of moral worth see e.g. @mark10.] If one will be motivated by the right reasons, then one should have a grasp of the right reasons and the support they provide for the relevant moral judgment [443]. There are a number of benefits for the agent assuming that they have this kind of grasp.

What we want is a richer and more holistic kind of engagement with moral reasons, encompassing affective and motivational engagement as well as cognitive, but still basically structured by rational appreciation and ability [@call18d; 450]. The core of what understanding *‘p'* requires, in standard non-moral testimonial cases, is ‘knowing that *p*', and 'knowing why *p*'. In the moral cases, it also is not enough to only *know* that compassion is the correct response, but also why it is the case that compassion is the correct response. We need to believe '*p*' for the reasons that make *p* true'. Plus, ‘feeling X, Y, Z emotions appropriate to believing *p*, for the reasons that make *p* true', plus; ‘being motivated to behave in X, Y, Z ways appropriate to believing *p*, for the reasons that make *p* true' [@call18d; 451].

However, someone may worry that this may require not only that an agent have the correct moral responses (i.e. emotional) in relationship to the correct reasons for the response, but it might also require them to be able to articulate their emotional response as a reaction to those reasons rightfully contributing to this response. They may worry that we do not bestow moral worth to an agent who is unable to justify her affective response to some state of affairs granted that we consider said response to be an apt one.^[I think that this is an important point regarding @arpa04 discussion of the importance of Huck Finn. Also see @benn74.]

Let's imagine that Sue was told that she should get inoculated (wHs) against a deadly and contagious pathogen. Achieving a critical mass of inoculation will stem the transmission of the virus saving many lives. Sue however does not believe any of this, rather she believes that her testifier is in a better position regarding what she should do, accepts this and resolves to get an inoculation regardless of her testifier's reasoning. Because Sue fails to understand (wHs) (inferred from her reliance on testimony), though she successfully receives the inoculation, possibly the right action in the context, this in itself is not a morally right action. Sue fails to perform an action that has moral worth.

We often hope that moral knowledge can be exploited in future reasoning and deliberation [@mcgr19, 60]. But why should we think that it will be useful in future reasoning and deliberation? Is this no different than asking friends whom we trust for moral advice and then remembering their answers later on? Therefore, because it will be difficult to apply correctly in future scenarios, we should not act on this advice without our own ability to critically reflect on our beliefs.

Let's imagine that later, while Sue is on her way to a job interview, she is the only witness to a traffic collision. While it would not have taken much to dial 911 as the accident was severe enough to produce critical injuries, she merely drives on, quickly forgetting about the incident. This infers that Sue was not successful in employing the reasoning behind the testimony about the vaccine, namely that human lives are important and one should do what one can to mitigate threats to them. The pessimists will likely summarize the problem this way:^[E.g. @hill09, 103; @howa18, 1070] Utilizing this knowledge properly for Sue means including the testimony she received in her reasoning and deliberation. Had she done this, she might have remembered receiving the reasoning behind the importance for getting inoculated and making the correct inferences.

But let us say that she does use this testimony in the context of his reasoning and deliberations. As such, she concludes that: I was told that I should get inoculated to stem the transmission of the virus. This is not so that others will not get sick, but so that I will not get sick. This looks similar to the picture of moral knowledge defended by McGrath. It is one thing to rely on trustworthy individuals for our moral outlook, but we hope to be able to figure moral problems out for ourselves in cases of future moral deliberation.

If instead Sue had instead reasoned: I should get inoculated in order to stem the transmission of the virus. This is so that others will not loose loved ones to illness.^[This case is slightly based on @arpa04's Extremist Case (74), although hers provides more detail than mine, still mine is germane to the problem faced here.] Given the problem of testimony and moral worth then, it would be better to characterize the problem as one where Sue never acts against (wHs) after receiving testimony, a trait which becomes a part of her character.

As to those reasons which prompt such action, a question which emerges then is; when does such restraint (given its resemblance to moral understanding) constitute moral worthiness, and when does it cease to do so given all the possible reasons available to an agent for acting?

