# A Fitting Moral Fiction of Sentiment

According to cognitivists and non-cognitivists, emotions are evaluative. Such evaluative emotions can accompany our moral judgments which are grounded in or grounds for, emotions of approbation or praise. The concern then is whether our cognitive moral judgments influence the way we perceive the moral landscape directly contributing to those emotions that we feel in a given context. Or, whether the emotion we experience grounds the corresponding judgment. It is standard for cognitivists to endorse the former while non-cognitivists endorse the latter. What is important here, is that the emotion that we experience in response to a given fiction, is not the same kind as those we experience in real life [@gilm20, 59]. So the question is that assuming some given moral aptness to the expression of a given emotion, say loss at the dissolution of an important relationship, whether the criteria governing such emotional expressions accompany our responses to fiction. Although I may feel fear when walking down a dark alley, I would not feel a similar emotion when following a character down a dark alley. This is because in the context of fiction, I adopt the phenomenal states of that character, experiencing the world in the same way that the character does while in real life, the phenomenal character of the emotion is more dubious. The connections between the more deliberate operations of our cognition, such as judgment, and the reactive ones such as emotion, are not clear. It may be hard to determine how our emotional responses to fiction are grounded, in what part of our cognition they originate.

However, this view is at odds with our standard responses to fiction, what some call the emotional paradox of fiction. We have many varied responses to events in the real world that are constrained by certain facts about the real world. We are likely to have a greater emotional response to the death of a loved one rather than the death of a stranger. We will appreciate a cheap trinket from a close sibling more than a cheap trinket from a stranger. We will worry more for a close son or daughter traveling in an unfamiliar foreign country than we will the son or daughter of a neighbor. This is because fictions often constrain our emotional responses in ways dis-analogous to the real world. It may take years in the real world to do what fiction can do in several chapters. We cry when Jess discovers Leslie's death in Katherine Patterson's Bridge to Terabithia. James Hurst's *The Scarlet Ibis* teaches us that we can develop empathy for a character even more quickly than suggested in novels when Doodle is left to die in a moment of adolescent insensitivity. What this means is that while I might experience sentimental approval, joy, glee, optimism in one context in fictional worlds, I do not necessarily need to have similar experiences in similar contexts in the real world to feel similar emotions.

If this is true, it can raise problems for the view that fictions are necessarily sources of a richer form of moral knowledge as some have argued. For instance, we might consider the interesting ability of tragedy to convey the important value inherent in human relationships. We can experience pain upon the dissolution of a relationship in a tragic play. But, tragedies are also most immediately notable for the conflict in desires they give rise to, as expressed by a given moral conflict centered in a given tragedy, for instance our recognition of the conflict of desires in Aeschylus' Agamemnon. Further, the audience also experiences a similar moral conflict in their desire to consume the tragedy rather than turn away from it. Paradoxically, tragedies contain a feature wherein while we desire that some event take place, at the same time, we would not normally desire that such an event take place, or we desire that the event does not take place. In tragedy then, we pursue experiences which conflict with our normal dispositions to avoid pain and distress.

One approach is to say that our interest in the tragedy suggests there may be a value that supersedes other values associated with the avoidance of pain and distress. Some possible values of tragedy include opportunities to clarify our emotions, intrinsically valuable enlightenment about the nature of suffering; a safe experience of suffering [@gilm20, 158]; and an opportunity to clarify our own human vulnerabilities [@nuss01t]. Among these values are certain kinds of pleasure that may mitigate the pain that tragedy causes, e.g. some affective stimulation, positive or negative in valence, that we desire. But this is not to say that the value inherent in tragedies needs to be rooted in pleasure. Therefore we can split the possible values in two ways.

::: {.remark}
Type One Responses, Non-moral: Pleasure or another kind of affective stimulation.

Type Two, Responses, Moral: Intrinsically valuable enlightenment about the nature of suffering, a safe experience of suffering, an opportunity to clarify our own human vulnerability in light of suffering etc.
:::

A part of the problem with emotional responses and fiction, is that it is not clear what the delineation is between these two categories. What factors go into whether we have an experience situated in category one, or category two. In what follows, I argue that identity is a constraint on the kinds of emotional experiences we have in regards to fiction. As such, identity, whether we identify, or whether the author intends that we identify or not with a given character, will determine whether our affective response is of type one, or type two.

## Moral Sentiments and the Ethics of Caring

In her 1982 book *In a Different Voice*, Carol Gilligan coins the term *Ethic of Care*. Gilligan argues women treat moral issues in terms of relational and emotional responses. When a care-giver wants to teach the harms of bullying for instance, they will often encourage a child to imagine being bullied or if someone they cared about were bullied. Such concerns are a part of a larger tradition where such philosophers recognize the importance of empathy in both public and private life. Highlighting the centrality of emotional expression in moral matters, we may revitalize the works of seventeenth century sentimentalists, Hume, Hutcheson, Smith, etc. This resurgence refocuses our attention on classical moral views grounded in social lives that are centered on empathy. For instance, in book VIII of the Nicomachean Ethics, Aristotle defines his ideal social constitution, ranking three types of friendships, the best of which he calls *friends of virtue*. Importantly, an individual of virtue appreciates the friendship and wishes the best for the friend, a desire rooted in empathy.

> Friendship and justice seem, as we have said at the outset of our discussion, to be concerned with the same objects and exhibited between the same persons. For in every community there is thought to be some form of justice, and friendship too; at least men address as friends their fellow-voyagers and fellow-soldiers, and so too those associated with them in any other kind of community.

Friendships between individuals of virtue and civil polity correlate with empathy. According to such a view, the psychological phenomenon of empathy that may be at the foundation of the best types of friendships, is also at the heart of the best kinds of civil polities.

### The Ethics of Care {-}

According to some moral sentimentalists, the moral worth of an action depends on the sentiment it is grounded in, actions done without the right kind of corresponding affect are devoid of moral worth. Some call such expressions of empathy *moral understanding* [I.e., @howa18; @call18]. Moral understanding is an affect which underlies our moral judgments; motivating, accompanying, and grounding our actions. It can also explain and justify the same. Accordingly, moral narrative is a form of moral testimony which relies on more than just our cognitive faculties, knowing right from wrong, but also our non-cognitive faculties as well, being motivated by the right affects.

Moral sentimentalists resting on an ethics of care account [@slot07; @slot13; @gelf19] will draw our attentions to the moral emotions that frame a moral motivation. This work focuses our attention to sentimentalists who will draw our attention to fictional narratives that enable us to acknowledge the importance of the expressions of care and empathy in human relationships. This is because moral narratives are grounded in philosophical concepts of identity and rely on constructions of empathy closely related to one's sense of identity. The familiar story of Jesus weeping at the death of Lazarus becomes a story of Jesus, knowing what Mary does not, empathetically weeps with Mary. Accordingly then, through empathy, our imagined relationships to depicted characters in fiction constrain our emotional expressions in a given context. We may weep with others even when we know that their pain will shortly give way to rejoicing. A fact which may not be available to the literary character in that moment. An ethic of care provides us with an ability to understand the importance of narrative where other philosophical accounts fail.

## Narrative Suffering

There is much that can be said about suffering, for instance that the existence of suffering can be explained by benefits that mitigate the suffering. These can include pleasure, affective stimulation, opportunities to clarify our own emotions, valuable enlightenment about the nature of suffering, a distanced experience of suffering, and opportunities to clarify our own vulnerabilities to loss and hardship [@gilm20, 158]. The story of Job may lead credence to some of these values. For instance, it would be one thing to hear that Job was devout and faithful, but a narrative about him remaining devout and faithful throughout his suffering, gives us a greater appreciation for the depth of his faithfulness, in a way in which we might develop a greater appreciation for our own resilience in the midst of tragedy. There is a kind of suffering that we experience when reading the story of Job. Through a narrative account of his suffering however, we learn something about him. That he was devout and faithful. One way to understand the relationship between tragedy and narrative then, is by understanding how narrative can produce the benefits of, for instance, suffering, and it can do this without the suffering itself.

### A Re-Conceived Moral Testimony {-}

Corresponding with various group dynamics in regard to the motivations for the expression of our emotions, the other concern then, is a broader, and perhaps more controversial one. On the relationship between art and ethics [@gilm20; @stol92; @gaut03], a primary point has to do with our emotions in relation to fictional contexts, namely when is an emotional experience an apt response to a fictional representation. I argue that the intractability of these two concerns, which have been up until now considered separately, is due to the fact that we do not often consider their relation to one another. Drawing on claims regarding the connection between narratives and emotional states [especially by @nuss85], we might ask ‘what might a morally expressive emotion look like?’ Martha Nussbaum, Eleonore Stump and Linda Zagzebski have argued that morally significant intimate relationships depicted in narratives between two or more individuals necessarily involve morally significant emotional states. The ways in which these emotional states have moral significance vary. For instance, @zagz17 articulates emotions as having objects which in the state characterized by that emotion, the object of the emotion appears to us as having the property characterized by that emotion. Objects which appear admirable to us, motivate us to emulate those objects [@algo09].

In the moral literature on narrative, there is debate about whether a work depicting a particular event can motivate an emotional state contrary to a similar event in the real world.^[See e.g., @stum10, @nuss85; @nuss83; @nuss01; @harr11] We can call continuitists those who claim that narratives are important for facilitating empathic relationships among individuals by expressing the emotional states of the characters in morally appropriate ways. There are two relevant components of such an argument, however. One says that the relations depicted by narratives are normatively descriptive of moral [@nuss85], or admirable [@zagz17] relations among individuals. However, others may suggest [@gilm20; @mora94], that such depictions may rest heavily on sufficient artistic engagement, or attunement by the artist, and a particular sensitivity to the relevant moral issues, noted particularly by the motivations and intentions of the artist. They may argue, any less literary engagement with these contexts will not sufficiently express the complex moral frameworks Nussbaum, Stump and Zagzebski find in literature (The View).

This has implications if, as some have claimed, narratives are important for facilitating empathic relationships among individuals by expressing the emotional states of the characters in morally appropriate ways. We might think, for instance, that emotions can constitute a type of perception where we recognize the moral significance of a situation by our affective perception of it [@nuss85, 521]. According to Nussbaum, *The Golden Bowl* represents such an ethical representation when Maggie Verver, for the first time in their marriage, embraces her husband with an emotion commonly reserved for lovers [@jame85]. The artistic engagement is noted by the motivations and intentions of the artist. As such, we may think that the values associated with e.g., tragedy, are those defined by the author, but not intrinsic, or emerging from the work apart from the author’s intentions. Can we find natural moral content in narratives wherein the author hadn’t meant to include? Can a narrative cultivate a harmful stereotype apart from the author’s intentions or does the lack of intention negate the harm?

A debate in aesthetic literature might undermine optimism about moral testimony through narrative. The discontinuity thesis is the view that our emotions in fictional worlds do not need to be continuous to those in the real world. Some have claimed that narratives are important for facilitating empathic relationships among individuals by expressing the emotional states of the characters in morally appropriate ways [@nuss83; @arpa04]. The way we respond to fiction can drastically depart from our responses to their real-life counterparts. Our affectations can also radically differ and a part of the explanation for this is that objects in fictions are presented to us in ways that differ from the presentations of their real-life counterparts. One common answer is that the aims of the artists determine these framing effects [E.g., see @stoc17]. There is a worry here however and one important reason for asking such questions is the hope that they motivate a different way of thinking about narratives which highlights their extra-aesthetic properties regardless of the artistic intent behind the work. Sentimentalists approaches are uncommon enough in moral testimony, that considering one based on narrative may clarify some of the major points of discussion. Doing so may highlight the necessary relationship between moral knowledge and narrative providing a better account of narrative, one which provides an explanation of what they are and what they do. In my account, narratives are forms of moral communication. They can undermine or build up one’s moral knowledge. They are moral in that they represent human emotions in the contexts of human and human or human and other sentience relationships. Not only do narratives cognitively show us what important relationships are like, but more importantly they show us what such relationships feel like. Such effects are important for moral worth in action. Because of their ability to elicit affect, narratives are important sources of moral knowledge. A central question to be resolved in the first section is the asymmetry problem between moral and non-moral testimony. Optimists argue that though it may not always be optimal, moral testimony is an acceptable source of moral knowledge. By contrast however, pessimists argue that though it can confer knowledge, moral testimony does not confer moral worth which can only be obtained through moral understanding. As such, moral testimony is useless.

Alongside narratives in literature, there are other disciplines which tell us about individuals in communities outside our own. We may read the reports of a past explorer and obtain an awareness of various propositions about the cultures encountered by them. However, we are likely to question the authenticity of a report if we have reason to suspect the author has a personal bias coloring the analysis. Importantly here is the question of whether it is possible to learn about others through narrative.

It is curious that while we may worry about a historian’s bias corrupting a particular character analysis of a historical figure, concern is not similarly expressed regarding a created narrative.

> It should be clear that, for my purposes in this book, it does not matter whether or not the narratives I examine are revealed. A defense is a story that accounts for the existence of God and the existence of the suffering in our world and that is not demonstrably false; a defense does not need to claim that the reasons it ascribes to God for allowing suffering are God’s actual reasons, only that they might be God’s reasons, for all we know. [@stum10]

We may have reason to be concerned with bias regarding Job’s account. We hear about the Christian virtues of a particular e.g., politician, through narrative, and only find out later that this individual was hiding a particularly horrific sin. A question that arises then is ‘what are the relational benefits incurred by our suffering in tragedies?’

### Moral Perception of Others {-}

Perhaps it is because the created narrative requires us to use our own imaginations, rather than the imaginations of the narrative’s author, in order to understand what a historical figure might have been like, how they might have perceived the world, what their phenomenological responses to events in the world may have felt like. Accordingly, we might think that although many facts in the narrative that we were led to believe were false, especially those corresponding with the virtue of the individual, these in themselves are not important. There are other facts, maybe, which are more enduring, such as a story of an individual, who if they did possess certain character traits, would have been a very admirable person. As such, the important truths conveyed through the narrative are hypothetical. If a given individual were to possess some particular virtue, then they would perhaps view the world a given way.

Although we may read in the new testament bible that Jesus is God, we may think that the new testament also wants to show us that Jesus is human. Therefore, upon seeing Mary weep at the death of her brother Lazarus, Jesus himself weeps, even though Jesus knows that in just a moment, Lazarus will be raised to life [John 11:35]. He is affected emotionally rather than cognitively. Rather than just relying on the testimony of the text’s author then, we are contributing as much to the analysis of Jesus, through our ability to imagine Jesus much like us, as the author.

Attempting to understand narratives as they are, we can come to understand the character, what he or she is like, that Job is faithful, God is human, a given saint is virtuous. But why should we trust these accounts?

Much of what is involved in the representation relies on our own imaginative faculties, we can imagine Job sitting on the floor of his tent in extreme agony, and then from the foggy recesses of his mind, hearing God's voice. We may imagine that it is gentle and nourishing, or that it is harsh in its rebuke of Job’s accusations against God. As such, it does appear that there are some qualifications for understanding what an agent is like through narratives. The narrative accounts for some proposition related to that agent, that in some sense they exist and that certain propositions about them are true. However, the particular features of the narrative which act as reasons are reasons why a proposition is not demonstrably false rather than true, and once again, what is not demonstrably false are the positive character attributions directed at a given individual. Once again, we should reject this response assuming that we are attempting to attribute positive characteristics to demonstrably vicious individuals, such as the wayward politician. But of course, if the wayward politician is malevolent enough, then the wayward politician is nothing like us.

However there are other ways in which we can attribute the important traits of virtue regardless of the virtue or vice of the represented person. If the character is an obvious fictional character, then it does not seem that we can commit any harm in the ways we would if we were to attribute similar traits to those who have, unbeknownst to us, committed incredible evil. Another method, however, is by attributing these to individuals whose lives existed so deep into history that it is questionable whether they ever truly existed. If we imagine that Job hears God’s voice, this is because it has not been communicated in the context of the narrative, that Job does not hear God’s voice. Job’s life, by now, verges on the mythical and if this is plausible, then I suppose it’s perfectly fine, for mythical humans hear God’s voice all the time.

I suspect that some falsehoods are even more problematic than the narratives of virtue. We can imagine an individual with malevolent intentions falsely portraying members of a community that he dislikes. We might imagine a fan of a certain sports team falsely portraying a fan of the opposing team at a sporting event. One available explanation as to why some inaccuracies are more harmful than others, is that when maligning others, we might think that we have an obligation to be as truthful as possible. This is because the harms here outweigh the benefits. We are harming a particular person. In the virtuous narrative, the benefits provided by moral education outweigh the harms of inaccuracy with respect to the truth. As such, there are two kinds of inaccuracy in the narrative. One concerns the inaccurate narrative of the malicious individual attempting to harm others, while another seeks to present someone in a better light than they perhaps deserve in order to communicate some aspect of moral reality.

Therefore, the propositions under consideration are only under consideration, and therefore narrative accounts are possibilities rather than true. But this still says nothing about our emotional responses. Can our emotional response to fiction aid in our moral understanding of a given moral proposition?

If an audience member is unhappy with the emotion prescribed by an artist, they can decline engaging with that work of art. Even more damning for my argument, is the fact that it is likely that sentimental optimists may accept this conclusion. According to them, only some literature can be thought of as a source for moral knowledge. This is unacceptable. What it leaves is a conclusion that while some literature is a source for moral knowledge, it is not necessarily the case that any literature undermines one’s moral knowledge. For instance, works for the intents of pleasure, are not intended for moral knowledge and therefore will be unable to undermine moral knowledge. If the work is particularly morally problematic, it is not the work, but the audience that is culpable. To fix this, I suggest that sentimental optimists classify any work which represents human emotion in the context of human other relationships as narrative. As such, continuitists and discontinuitists have differing conceptions of narrative. As a way to make the two commensurable, I suggest we define narrative in such a way that each discussant can accept. On a care account, a systematic way to recognize moral frameworks in narratives can be modeled on a sentimentalist ethics, specifically a care ethic, enabling us to recognize moral testimony as a source of moral knowledge in a way other ethical theories do not. Such accounts of moral testimony would then necessarily include narratives and therefore on an ethics of care account of moral testimony, narrative is an important source of moral knowledge not recognized in the literature as a kind of moral testimony. In the first section, I argue that the asymmetry of moral testimony is really a question about whether or not testimony confers morally worthy affective states. In the second section, I further expand on this idea using literary examples showing the importance of affective states in moral reasoning and how without appropriate affect, there is something missing in moral action. Because I’ve shown the importance of affective states in moral reasoning, and how narratives are supremely important for showing this relation, I continue the following section by looking at some more relationships between narratives and morally worthy actions. I start by looking at a specific conversation between those who think that our emotions towards fictions are governed by the same criteria as our emotions towards situations in the real world, and those who disagree. Without declaring a side, I continue the next section by further highlighting some reasons in favor of each view. In the final section, I develop a model which will highlight important aspects of moral knowledge in narrative accounts.

When we rely on testimony in a range of situations, doing so confers justification to one’s belief of a given proposition. For example, when a child obtains true beliefs from a reliable source, such as “the Earth revolves around the Sun,” there is reason to credit her with knowledge [E.g. @mcgr19]. However, the main reason for relying on moral testimony is not primarily to confer justification, but rather to motivate behavior. There are several reasons for this. In non-moral epistemology, while we may know, or think we know the answer to a given proposition, we may feel comfort in another’s testimony confirming that we know. As such, our belief is justified by the more knowledgeable . In the moral case, however, it is not enough to have the correct belief. Therefore, relying on justification to confirm that our moral belief is the correct one, leaves a lot to be desired.  As such, the epistemic state that we care about in cases of moral testimony is understanding and not knowledge. The point of contention here is a difference between the epistemic state of knowledge and the one of understanding.  Knowledge is knowing that p, that a given proposition is true, while understanding is knowing that p and why p is the case. This is perhaps a reason why a number of authors recognize a deep connection between narratives and moral knowledge (Martha Craven @nuss90; @stum10). We may think that what these authors mean by moral knowledge, is a richer state of understanding.

Additionally, authors have argued that the connection between narrative and moral knowledge has to do with a narrative’s ability to express important moments in a character’s emotional and moral development [@stum10 @nuss83; @nuss85; @nuss01; @arpa04; @zagz17; @harr11; @dol18]. For instance, narratives can be a source of second personal knowledge where through narratives, we develop close relationships with characters in narratives. We might think this is plausible assuming that a narrative has an ability to represent these important moments contributing to our sense of familiarity with them. Perhaps we then grow along with the individual through the narrative. We experience moments of hardship and joy, and other defining moments which often contribute to our understanding of the world. It is not immediately clear what this has to do with moral understanding of a given moral proposition. The standard argument is that narratives are a form of moral education. However, this connection spans two separate concerns. First, there is the less controversial worry about moral testimony as a source for moral knowledge.^[Also @hill09; @hopk07; @nick01; @enoc14]. However, this can lead to questions about the perceived relationship between art and ethics, an issue that is more contentious.

While Stump suggests that we can understand narratives as a source of moral knowledge, the psychological implications, the processes involved, are not immediately clear. For such an account to develop beyond folk psychology, it will be helpful to distinguish between several psychological accounts of moral development. On the other hand, Nussbaum has defended an interpretation of Greek tragedy wherein the project of Greek tragedy is that it enables us to get a sense for just how fragile a good human life is. Ultimately, Nussbaum concludes that the most important feature of a good human life are our relationships with other persons. According to Nussbaum, tragedy as a form of narrative is important for its ability to communicate this intrinsic feature of a good human life. For instance, in Pindar’s version of Aeschylus’s Agamemnon, when Agamemnon sacrifices his daughter to meet his obligations to Zeus, he does so without any sense of the emotions we would expect one to have in a similar situation. As such, Agamemnon fails to recognize the moral conflict Zeus’ demands have placed on him, the moral conflict undergirding his competing obligations to Zeus and Artimus.

What is attractive about narrative is that it gives us insight into what communities plausibly care about, thereby helping us to understand what we may possibly care about. In other words, it acts as a kind of perception enabling us to know about other communities. Oftentimes, when we think about psychological disorders, one trait that many of them have in common is that they undermine the sense of connection that we may experience with other members of a close community of people. For instance, individuals with autism may often lack empathy, experience social isolation, and avoid eye contact. Further, researchers noted that neurons in the anterior cingulate cortex which usually fire when a subject is in pain, also fired when the subject saw someone else in pain [rama07], except in individuals with autism. While others have called these findings into question [@cook10]. The point here is that our ability to share the perceptions of others may be an intrinsic part of who we are as a species.

Given this fact about our abilities to empathize with others, narrative would be an important part of human society in that it gives us insight into who the members are that comprise that community, it enables us to share their perceptions, phenomenal states and our ability to do so is an important feature of our cognitive faculties and how we learn various facts about the world. Because of the contributions of our imaginations for potentially fostering empathy then, the view that narrative literature may be useful for teaching ethics is a strong view [@choo21]. We can imagine what emotional states would be experienced by a given character and from this, infer what may be their own perceived possible course of action in some hypothetical situation [@des15]. Assuming that a particular crime family recently lost a son to territorial violence, we may be justified in thinking that a given member of this family is experiencing pain and anger. As such, we might think that many following actions would be governed by a motivation rooted in a feeling of vengeance, or a similar emotion. Nevertheless, there are those who give reason to deny the necessary correlation between ethics and narrative [See @gilm20; @mora94; @curr20]. Before looking at what is of central concern here, it will be important to look at some theories of emotions as prescribed in the reading of a given narrative and what this means for a narrative’s audience.

### The Ethics of Audiences {-}

Resting on an ethics of care account then [@slot07; @slot13; @gelf19]; I argue that recognizing moral frameworks in fictional narratives, begins with the audience empathizing, or desiring to empathize with a given character. It begins in the concept of identity. Such an ethic is grounded on sentiments of care wherein our imagined relationships to depicted characters in fiction constrain our emotional expressions in a given context. @slot07 provides a systematic account of why more traditional accounts are insufficient for motivating our intuitions about why some actions fail to possess moral worth. Moral understanding here, is thought of as moral motivation where we have various affects which underlie our moral judgments. Such affects motivate our actions, accompany our actions etc. According to this sentimentalist view, actions done without these corresponding affects are devoid of moral worth. As such, what we have then are pessimists about moral testimony, mt, optimists about mt, and the sentimentalists who can either be thought of as optimists or pessimists with respect to moral testimony. Most sentimentalists however are primarily sentimental pessimists. Narrative then, is a form of moral testimony which relies on more than just our cognitive faculties, but also our non-cognitive faculties as well.

What this means is that while I might experience sentimental approval, joy, glee, optimism in one context in fictional worlds, I do not necessarily need to have similar experiences in similar contexts in the real world. Here, what makes an emotional expression apt in regards to fiction, is whether or not the audience intends to engage with that fiction, and doing so aptly, means experiencing those emotional expressions intended by the creator of the work.

If an audience member is unhappy with the emotion prescribed by an artist, they can decline engaging with that work of art. Even more damning for my argument, is the fact that it is likely that sentimental optimists may accept this conclusion. According to them, only some literature can be thought of as a source for moral knowledge. This is unacceptable. What it leaves is a conclusion that while some literature is a source for moral knowledge, it is not necessarily the case that any literature undermines one’s moral knowledge. For instance, works for the intents of pleasure, are not intended for moral knowledge and therefore will be unable to undermine moral knowledge. If the work is particularly morally problematic, it is not the work, but the audience that is culpable. To fix this, I suggest that sentimental optimists classify any work which represents human emotion in the context of human other relationships as narrative. As such, continuitists and discontinuitists have differing conceptions of narrative. As a way to make the two commensurable, I suggest we define narrative in such a way that each discussant can accept. On a care account, a systematic way to recognize moral frameworks in narratives can be modeled on a sentimentalist ethics, specifically a care ethic, enabling us to recognize moral testimony as a source of moral knowledge in a way other ethical theories do not. Such accounts of moral testimony then would necessarily include narratives and therefore on an ethics of care account of moral testimony, narrative is an important source of moral knowledge not recognized in the literature as a kind of moral testimony. In the first section, I argue that the asymmetry of moral testimony is really a question about whether or not testimony confers morally worthy affective states. In the second section, I further expand on this idea using literary examples showing the importance of affective states in moral reasoning and how without appropriate affect, there is something missing in moral action. Because I’ve shown the importance of affective states in moral reasoning, and how narratives are supremely important for showing this relation, I continue the following section by looking at some more relationships between narratives and morally worthy actions. I start by looking at a specific conversation between those who think that our emotions towards fictions are governed by the same criteria as our emotions towards situations in the real world, and those who disagree. Without declaring a side, I continue the next section by further highlighting some reasons in favor of each view. In the final section, I develop a model which will highlight important aspects of moral knowledge in narrative accounts.

## Narrative and Narrative Identities

Early research at the intersections of language and the behavioral sciences, have sought to understand emotion via our moral intuitions.^[@moha21. Also see @osgo57] This project is important for understanding a wide range of issues ranging from online radicalization, to vaccine hesitancy. By extracting and analyzing emotional content in messages; narratives; and other forms of public discourse, we can better understand how the psychological influences of moral judgments affect broader global populations through the emotions anticipated in a given text [@moha21; @alfa22]. Researchers studying sentiment in written text, attempt to discover what emotional states are most likely being experienced by the audience of a given narrative. Looking at the word count of words associated with positive or negative sentiment / valence, and the semantic placement of words associated with a given sentiment [@rink19] is one way to analyze the moral content in messaging found in social and traditional media, contemporary archives, or Victorian literature.^[See @alfa22?; @osgo57 for a look at some of the historical developments in textual analysis.] Such research helps us to better understand human behavior and our decision-making processes by helping us to understand one’s attitudes towards a given topic. This assumes a given attitude may inform us of particular behavioral or motivational dispositions. However, these claims are contentious. A better method involves understanding those emotions one is likely to have based on what communities they belong to.

Work on sentiment analysis suggests that moral content in messaging plays an instrumental role in cultivating various dynamics supervening on, or emerging from emotional states, such as our sense of identity.^[@brad17; @brad18; @brad19; @brad20, 984] By understanding what gives rise to emotion then, we can better understand these dynamics and their associations with human behavior, for example group identity, and how it may inform what choices of action we decide on.^[@hopp21; @gram09] According to one view of group identity, social identity theory, when group identities become highly relevant, for instance on social media platforms, emotions are motivated in terms of group rather than individual goals.^[@brad20, 987; @tajf04]

Similarly, there is also evidence that suggests that public moral content influences the individual cognitive processes of individuals when phrases loaded with moral implications are processed more quickly by our cognitive processes.^[@hopp21; @brad20; @gant14; @gant16] Some individuals argue that this occurs in news reporting, motivating research into what emotional states are most likely to be experienced by which audiences.^[@haid22] Assuming that we align politically with a given party, we may experience anger when viewing a news report on vaccine hesitancy as opposed to another. Another branch analyzes the importance of personal and public narratives and the roles that these play in identity development.^[@mcle15b; @brun90]

One important aspect for factors that motivate our emotions is found in the psychology of personality literature. Here, personal narratives are a subjective understanding of how one came to be the person they currently are.^[@mcad01] We can infer a person’s expected emotion by referencing various contextual factors such as one’s social group and class.^[@tajf04] Much of the research has defined two kinds of narratives, master and personal. A master narrative is a script that is held publicly by a group of individuals. These are defined as culturally shared stories that guide one’s beliefs, behaviors, and values (bamb04?). Accordingly, an individual often shares the values of the community she belongs to. These values are defined through her scripts which are often indisputable by rational members of a given community, for instance the denying the 1969 moon landing defines membership in a community of conspiracy theorists. @nels04 have called these immersive socialization processes [Also see @book22) and argue that they are socialization processes, a system of human developments that includes language, memory, and identity. As a contrast, personal narratives are autobiographies which we use to explain how we became the person that we are. While there is significant research on both master and personal narratives, what is less well known are the cultural contexts of personal narratives. Because of the large interplay between social scripting, and what one believes about herself, our personal narratives often emerge in relation to master ones. However, it is not well known how master narratives factor into one’s own autobiography. Some possibilities can include a common example narrative about a shared recognition of the value of knowledge and understanding held by the members of a particular Russian Jewish community for instance. Academic success by one of the members of the community may be explained by reference to this shared communal value. Intelligence and cognitive ability then is not a surprise outcome but expected given one's membership in that community. Even more importantly here, while master and personal narratives often converge, they can also conflict. Not only can they do this in matters of traditional cognitive ability, but also moral cognitive ability given the moral beliefs held by members of a particular community.

One way to understand the relationship between moral understanding and master narrative is provided by Marc @alfa15 in his book Character as Moral Fiction. Alfano argues that moral technology is a form of character attribution wherein we assert various positive moral traits of a given individual regardless of the truth value for such a claim. Importantly however, the given trait attribution is not demonstrably false and therefore remains a possibility. Because of this possibility, the assertion is a placebo which motivates the object to begin believing certain facts about themselves. Referring to the fact that there is a positive correlation between the story about whether one possesses a moral virtue, and associated behaviors stemming from that possibility, we might think that positive moral trait attribution is a kind of moral testimony wherein one comes to believe certain moral facts about themselves and behaves accordingly. However, in relation to a worry by epistemologists regarding moral testimony as a source for moral knowledge [@hill09; @hopk07; @nick01; @enoc14], that we do not have any reason to trust it [e.g., see @hopk07; @hill09], there may be various reasons why one would think that narrative as a form of testimony is sufficient for moral knowledge whereas traditional testimony is not. To understand why this might be the case, we should contrast narratives with what we know about empathy and group identity. Our reliance on moral narrative as a guide for our behavior can bestow moral justification on our behavior in that we might experience an emotional event that motivates a given moral action.

Alternative narratives are important in contrast to personal and master narratives as they enable an individual to conceptualize their personal narrative in contrast to a culturally shared negative one. An individual falling under a socially attributed stereotype may believe that certain unproductive behavior for them is expected and therefore excused. However, another who rejects the broader social organization by accepting alternative narratives instead of the master one, may not excuse themselves for sub-par behavior. Additionally, alternative narratives can change public perceptions mitigating harmful stereotypes. For instance, Catherine Harrison (2011) argues that we have a similarity bias which is the root cause of emotions of empathy [Also see haro03?]. Harris argues that Emily Gaskell’s novel Mary Barton, evoked the similarity bias of Britain’s upper-class by describing the socially poor in London as people with similar motives and concerns as the ruling and wealthy class, creating empathic relations between the upper and lower classes of London. This empathy was central to Britain’s expanded social safety net.
