# Knowing Your Moral Worth

Thus far, the conversation has been dominated by pessimistic and optimistic views on moral testimony. Further, I have shown that there is another class of optimist not noted in the literature. These argue that narratives are a form of moral testimony which satisfies the criteria for moral worth as specified in the literature on moral testimony. I call these sentimental optimists. They situate the moral worth of an action not only in the cognitive assent of the correctness of a given behavior, but also in the corresponding emotions.

Whether moral understanding is cognitive or non-cognitive, has been thought to be unclear however. I have addressed the question of what constitutes, i.e. is representative of, an apt emotional experience in fiction and in doing so, show how the continuitists may be thought of as a form of virtuous carer. Here, the established role of affect in moral understanding as through narrative, is a way to achieve affective moral understanding and the virtuous carer wants desperately to understand others. It teaches us to recognize morally significant emotion states. To tease out this point, I look at an important point regarding continuity and discontinuity as raised by Jonathan @gilm20. Relying on @nuss01's analysis of fiction in the *Fragility of Goodness*, I argue that one way to deal with a question raised by Gilmore, is to consider the importance of our narratives in the context of our human relationships.

As I've argued thus far, many of the arguments disputing narrative as a source of moral knowledge, fail to recognize the relatively recent resurgence of virtue theory. In his Nicomachean Ethics, Aristotle questions whether an individual could experience *eudaimon* without close friendships and other parochial relationships [1169b2]. One particularly important branch of this form of moral theory, is the importance of who we are as communal creatures. One important concept in this view, is that of a moral sentimentalist ethic, according to which empathy plays an all important role in our obligations to one another [@slot07]. Empathy, fellow feeling, special sympathies, particularly for those whom we closely associate with, is a natural mental and emotional state. Others have marked this aspect of our natures as a natural vulnerability that is necessary for creatures like us. Without our ability to empathize with others who are close to us, our humanity would not look like how it does now. Moral sentimentalists argue that this ability to empathize is the source of many of our judgments regarding right and wrong behavior. Actions that do not reflect empathy, are those actions devoid of moral value. Some examples of such failures, often involve however, individuals who fail to empathize, or express empathy outside of certain contexts however. For instance, a grandmother who is seen as the pinnacle of virtue towards her family, but recoils in horror at the suggestion that she has similar obligations towards immigrants or the impoverished. The response to this however has been those sentimentalists who think that this form of empathy can be taught.

Both Eleanor Stump and Martha Nussbaum have argued in favor of narrative as a potential source of this kind of knowledge. According to @stum10a, narrative gives us insights apart from those available to us through analytic philosophy. Nussbaum has argued previously, that emotions are a cognitive response to these special perceptions of value.^[E.g. see @nuss85] In return, I will argue that what narrative offers us, are arguments about these special units of value. I argue that these insights, the ability to recognize what is valuable about lives like ours, are apt expressions of emotion in the right context. Various narratives can offer competing arguments about what the proper expressions of value as emotional states in the right context, look like. As such, narrative offers us the ability to discuss and compare contrasting conceptions of relational value. What it looks like, how to recognize it, where it may be found. However, a view we should turn to first, is Zagzebski's theory of the emotion of admiration and its grounded role in good behavior.

Exemplars are people which we perceive as excellent in some manner. The faculty of perception involved in admiration detects an object which we experience and then feel the emotion of admiration. @zagz17 argues that it is possible to define deontic kind terms through direct reference to exemplars. Her philosophical project rests on various examples of our moral practices including narratives and other fields outside of philosophy. Such a theory is structured around what she considers the motivating emotion of admiration. It also tracts moral development by explaining and justifying “a genealogy of morals” where the moral development of a person and that of a community are intricately linked. By identifying psychological conditions of moral development, Zagzebski argues that her project follows this moral development which can be observed in the telling and re-telling of narratives and in the imitation of models. Another important point, is that her theory will also rest on empirical studies in psychology and neuroscience. Lastly, it provides a cross cultural discourse where it applies pluralistically to radically different societies. Her moral genealogy here then, is cross cultural.

What motivates behavior? Zagzebski argues that the emotion of admiration, where the emotion of admiration provides a point of semantic direct reference to the moral objects (individuals possessing admirable traits, or possessing qualities that move us to admire them) of the theory; goodness, kindness etc is seminal in motivating positive behaviors.

For instance, see *The Principle of Linguistic Labor*

> Ordinary users of the word “gold” can form beliefs and make statements about gold because they are semantically connected to gold through a linguistic network that privileges certain users—-the experts. [12; also see @putn75, 144—146]

Many moral exemplar theories posit similar views. This suggests however that narrative has the ability to instill within us moral fictions. Namely that we are led to believe that we have certain moral traits. If successful, we come to possess these traits through a process he calls self-fulfilling prophecy.^[E.g., see @alfa15] @stum10's own view is that we enter into relationship with narrative characters who possess the traits we come to admire. We might think that if we are led to believe that such individuals are a part of the community we belong to, it becomes apparent that it is not too far fetched to think that we would not adopt behaviors similar to theirs. Namely that individuals are motivated to perform a given action based on their experience of similar actions. According to Zagzebski, this is because those actions elate positive feelings which contribute to characteristic behavior in the perceiver.^[For other foundationalist theories; see @putn75; @krip80.]

Moral terms are anchored in exemplars of moral goodness. These act as direct references which grounds our moral terminology [15]. We learn which individuals are admirable through narratives of fictional and non-fictional persons. We come to identify these individuals through our emotions, specifically admiration. A question which would arise then, is what about instances wherein these emotions are falsely being motivated in us? Zagzebski argues that this emotion is subject to education through reflection on further experience and the emotional reactions of other persons [15]. However, not every member of that community is capable of identifying proper objects of a moral kind term in the same way that not every member of a community can properly identify gold. Typically we often differ such judgments then to experts. It is difficult to see how this might fair analogously to questions about moral testimony where those who rely on the testimony of moral experts are not attributed moral worth to their actions.

## 2 The Moral Emotions

Zagzebski's view is grounded in her definition of admiration. Here, admiration is an emotion with an object which it may or may not fit. It also has an affective component, i.e., a characteristic feeling. It can also be a state where we find a particular object admirable [33]. Further, admiration like all emotions have a characteristic feeling that cannot be detached from the appearance, for instance of an object. In the state of an emotion, an object appears to fall under thick conceptual terms, for instance *pitiful, fearful, admirable*. Such concepts combine the descriptive (i.e. the appearance) of an object with its affective component, the state which the object motivates in us.^[There are various kinds of admiration. Intellectual or artistic genius, moral leadership, stalwart courage, compassion, open-mindedness and intellectual honesty represent the primary differences in the kinds of objects of our admiration: natural vs., acquired excellences. Admiration (what Haidt calls elevation) as an *other-praising* emotion arising from the witness of exhibitions of non-moral excellence in others. See @hait03a; and @haid03b; @algo09; @haid09; and @vian10. Also see Onu, Kessler, and Smith 2016, for a helpful review of the literature on admiration.]

> In constructing a theory in which the admirable is more basic than the desirable, I am reversing the priority Aristotle gives in the *Nicomachean Ethics*. There he defines the good as the desirable—-what everyone desires for its own sake (NE 1094a 18—20) which he identifies with *Eudaimonia* i.e. flourishing or well being. [@zagz17, 31—32]

However, it is very often the case that our admiration, and emotions similar to it, are grounded in problematic judgments of anything that is unfamiliar. Before moving on further, it will be important to first articulate a theory of the way in which emotion is tied to moral or ethical concerns. One important reason for this is that it is very plausible to think that there is no relationship between emotion and various concepts such as the good, noble, obligatory, etc.

A helpful way of speaking about moral concerns, is to also talk about what it means to value something. Constitutive of what it means to place value in something, is to point out that we have strong feelings about it. We might place strong value in the care of certain objects, say maintaining the look of a certain car. We experience more positive emotions when situations correspond with our values in the ways we desire. Emotionists argue that our moral concerns are saturated with sentiment which can be a claim about the valence of an emotion whether positive or negative, the emotion itself, whether joy, hope, fear, anger, pride etc, or other motiving factors [@moha21].^[For a helpful over view of the emotionist literature, see @prin14. Emotions as evaluative representations, see @gilm20, 44--57; @arno60; @laza84; @smit85; @sche01; and @rose90.] There are some issues which divide emotionists. It will be helpful to briefly go over some of these issues.

According to epistemic emotionists, grasping a moral concept means that we recognize the moral fact which corresponds with it.^[See @prin14, 13] But epistemic emotionists can be either realists or anti-realists. If one is an anti-realist about moral properties for instance, then it is likely that he or she would not accept any reasons for thinking that such concepts point to objects that exist out in the world. For instance, on the one hand, sounds and colors are real. However if it were not for our particular cognitive faculties, then our color and sound concepts would be entirely different from what they are now.^[See @prin14, 16. Also see @crim89] However, even if we do accept that our color and sound concepts would be entirely different given a different set of faculties, we might think that we have the faculties that we do because they enable the appropriate concepts, given the existence of such properties. Yet, it is important to point out that though our faculties point to properties in the real world, it is not necessarily the case that these properties have the exact features that we experience them as having.^[See Stephen Palmer] We can accept that some object does not have the same properties that we experience them as having, and yet to not have that experience in relation to the object, would count as a defective faculty.^[See @mill89] As such, we would have reason to think that moral concepts point to objects that exist out in the world. Therefore, analogously, one can also be a realist about moral properties.

When considering the relationship between narratives and moral properties, the question is if moral properties are detected by perceptual faculties, those that use emotion to represent properties, what might an artist create assuming that he or she determined to create a moral framework?

The movie Cider House Rules is a good example. It stars Toby McGuire as Homer Wells, a precocious orphan who is taught how to practice medicine (without a license) by the head of the orphanage—Dr. Wilbur Larch. Dr. Larch defends his actions, including terminating pregnancies (illegally since the movie takes place in 1940’s America) and teaching his unlicensed prodigy to do the same. In defense of the obvious illegality of his actions, he reasons that his patients would seek sub-par care elsewhere if he declined. A seminal moment in the movie depicts a young woman impregnated by her father. Although Homer had until then, been reluctant to terminate pregnancies, he acquiesces. For the emotionist, there is a real moral property regarding the permissibility or moral obligation of permitting medical care related to terminating pregnancies. Therefore, a moral argument expressing as much would involve evoking the desired emotion related to that moral property.

An artist perhaps would not represent moral frameworks in the same way as say a biographer. We might answer such questions by first considering what are the contents of works within fiction.^[E.g., see Catherine @abel20a] For instance, we might think that an author's intentions are what determine the contents of a given fiction. In the case of fiction, the thought often is that the author or artist uses communicative utterances to elicit an imagining.^[E.g. see @curr90; @davi07; @stoc17] Further, imaginings can have a direct causal link to the emotions that we experience. Given the link between emotion and moral obligation then, an artist can make a moral argument using the effect of emotion on our moral reason. As such, an author can use various artistic effects to either evoke an imagining that argues in support of one moral proposition regarding our moral obligations, or another.

But this question in and of itself is not sufficient because even if we were to articulate a set of conditions that in themselves would determine the contents of that fiction, there would still be no guarantee that the audience would reliably be able to identify said contents. Consider the song *The Grand Tour* as written by Billy Sherill and performed and recorded by George Jones. It is a point of debate about whether the song is about divorce or death. Lines such as 'chill you to the bone', 'but now she's gone forever' can be ambiguous referencing either. Tyler Mahan Coe has pointed out that references to a baby but the lack of a baby's photograph or any indications such as a baby's cry, 'See her picture on the table, don't it look like she'd be able' while mentions of 'And her clothes are in the closet like she left them' and 'Taking nothing but our baby and my heart' all suggest an unborn child implying the death of a pregnant mother.^[@coe22] It is arguable that audiences can and do recognize contents in fiction, but similar to a given linguistic implicature, it is thought that there should be various norms governing the correct understandings and interpretations of a work of fiction. In a similar fashion, there also should be various norms governing the correct understanding and interpretation of what emotion a work of fiction intends to elicit. But this is not always the case.

Considering various ethical theories that are not consequentialist or deontologist, such as sentimentalism, what makes such a task even more difficult than suggested, is that moral particulars are complex in and of themselves [@nuss86]. We often refuse to see the moral landscape for what it is because we can be blinded by self deception, desire, practical concerns, to name but a few impediments of understanding moral particulars in real-life. Even more, we might even think that such partialism is a component feature of our ability to morally reason, rather than a bug.^[E.g., see @bowl04a; @rusc14; @toma13; @yama16. Admittedly, there is much to be explored in this literature. However due to space constraints, this present work cannot fully explore these.] Consider whether if your spouse and parent both fell over opposite sides of a life raft in shark infested waters. You can only save one, who would it be? If there is an artist who desires to represent a moral framework in their art, then this artist will likely strive to recreate the moral landscape in all of its complexity including those aspects of human psychology which undermine moral perception or complicate moral reason.^[@slot07; @slot10] An appropriate question would then be: what is the analogy between moral attention and our attention to works of art between moral achievement and the creation of a work of art. Exploration of the moral contribution of works which explore the experiences of beings committed to value.

What is found in narrative art, are terms, words and sentences that are expressive of unique perceptions. Additionally, to understand this question and the various ways of answering it, is that the moral question alone can be answered according to how we resolve to answer evaluative predicates, 'good', 'bad', 'right way', 'wrong way', etc.^[See @nuss85. Also see @alfa15, 7] What does it take to say that the object of some perception is good, bad, correct, admirable or noble? While there are many who argue that moral questions should not be a part of aesthetic evaluations, it is not necessarily clear that this is always possible. Because art is a discipline that is such an integral part of everyday human experience, it seems that a best method of answering the moral question in art is by first considering human psychology. What determines the experiences that we aesthetically evaluate, and what determines our evaluations of them? Do we necessarily divorce these considerations from pure aesthetic evaluation?

> The final moment of the scene describes the act that is the fruit of this communicating. We have said that these picturings, describings, feelings, and communications---actions in their own right---have a moral value that is not reducible to that of the overt acts they engender [522].

One reason why we might argue that it is not possible to divorce moral considerations from purely aesthetic ones, is because we might think that what it means to say *moral consideration* is just what we might say in *living well*. Further, *living well* is a question about one's psychological states and what is it to live well is a question explored by literary works.

### Moral Negotiation in Art {-}

But these are often open ended questions. A form that such debates can take is through the narrative process. Adam @mort13 argues that fiction gives us a platform in which to present contrasting theories of appropriate emotional responses.

How do we come to have apt emotional expressions? On the one hand, it might be fruitless to criticize another for the lack of an emotion they are not able to produce.

> You can’t just decide to be happy, or to have some chosen belief. And if you are experiencing self-punishing remorse when regret would make more sense, it is not enough to simply tell yourself so. )

::: {.remark}
But what is the possibility that we can influence our own emotions to others? What power do we have over our emotions? Some possibilities include the following:

* change our states of mind
* attend selectively to evidence
* choose who to associate with
:::

In other words, we should not conclude that we have no power over what we feel. It can be an open question of which moral attitudes, as expressed by our emotional lives in a given context, are harmful, perverse or counterproductive. Therefore, it makes sense to think of the emotional experiences we have and when it seems appropriate to have them [157].

In his *Emotion and Imagination*, Adam @mort13 asks what is the link between emotion and imagination? He argues that imagination enables us to understand others, by helping us to understand them second-personally. Through the use of imagination, we have the capacity to imagine another’s moral emotions by imagining their imaginings and imagining the other person’s emotion here means imagining their emotions and when it is appropriate to experience a given one. In order to avoid what Morton calls moral smugness, a vice that undermines second-personal knowledge, we must practice what he calls emotional unbundling. This is a virtue that requires that we take motives from which our own emotions are constructed and attribute them as much as it is possible to someone else’s.

> A person acts, moved by shame, approval, condemnation, or some other moral emotion. Another person tries to understand, and perhaps to anticipate the next action. But she knows that if she were acting from shame, condemnation, or approval, she would do something very different. Perhaps what he calls shame is leading him to public confession rather than wanting to hide; perhaps what he calls condemnation is leading him to teasing rather than attack. One possibility the second person must face is that his shame, or condemnation, is not hers. Perhaps they are different emotions with some family resemblance. Part of the evidence that a similar but different emotion was at work could be that the second person managed to imagine such an emotion and it fitted. But to get this evidence, she would have to be able to do the imagining.

At any given point, there are multiple emotions available to us. Morton contributes this to our ability to imagine feeling a particular way depending on a given situation, the participants involved in an event that happens to us, etc. Therefore, there is a question about which emotions are right and which are not. Narratives make *emotion concepts* available to us. Before these concepts are available, we may not know the full range of emotion that is possible to us. Psychological research regarding philosophical treatments of emotion often discusses emotions as basic bodily states, cased by mental activity; the James-Lange view^[See @cann27] where body-states cause emotions; and the emotion as appraisals view.^[E.g., @arno60; @arno84; @arno71] Largely, many current theories of emotion rest on the appraisals view where emotional experience is in someway correlated with moral judgment.^[For a helpful overview of the emotions, see @gend09 and @prin14.]

All emotion involves imagination [1] and imagination involves representing something to ourselves [8]. Because of imagination, we can “see” anything. Our emotions inspire us to search for actions that will address particular problems which we face. One difference between emotion and mood, is that our emotions have objects whereas moods do not. Our emotions put pressures on our thoughts, desires, conjectures, fantasies, and perceptions. This pressure in turn is interpreted as a feeling. Morton cites different categories of emotion, what he understands as a four way distinction between emotion and mood. Our emotions are a two-way cross-cutting distinction between passions and sentiments and another between moods and emotions [48]. Passion is a pressure which grounds characteristic impulses towards action and this impulse is often a direct response to a given event. For instance, passion as applied to mood, can be understood as an angry mood that generates an anger emotion as soon as it finds a target. While sentiment applied to mood can be understood something like depression. For instance, thinking of your own life or social life in certain terms. However, when we apply passion and sentiment to emotion, we understand emotion as being directed at a particular event. Or when we apply sentiment to emotion, we might see someone who often supports particular policies derived from a given emotion, e.g., support for the Iraq war or compassion for the less fortunate.

It is a common practice that we imagine other people’s emotions. This is how we understand their motives, actions, and feelings [54]. Our practice of imagining the emotions and perspectives of other people is a central feature of human social life [56]. Perspective is our ability to imagine the point of view of another. By perspective we plan our actions and predict the actions of others. Nevertheless, it is possible that we incorrectly imagine others. As an example, we might imagine a loved one to be in distress even though they are not. Imagined fictional personalities, such as an incorrectly imagined loved one, are not an illusion however. As a character, they have real motives and actions. As such, imagined fictional personalities can be an invitation to disillusion by allowing us to connect to possible characters, personalities with possible motives and actions. “We are rarely aware of the limits of our imaginative grasp of one another in everyday life, and of how often we do not manage to imagine at all” [88].

But sometimes we are unable to predict the motivations and emotions of others. This is because of an asymmetry between actions with good outcomes and others
with not so good outcomes where our disapproval of some outcome, prompts our desire to understand the reasons why it happened. Imagine someone who fails performing simple tasks. Our frustration with their inability to perform simple tasks prompts our desire to understand why they have acted in the way they did. "'How on earth,' you scream, 'could he make a disaster even of this? Whatever could have been going through his mind?' [@mort13, 91]" While we might understand *why* someone commits an awful act, we cannot understand *how they are able* to commit the awful action. We often think that we would have done the admirable act ourselves. The reason why this asymmetry exists then, is that because for acts that are pleasant, we adopt the reasons behind them as our own. We reproduce possible reasons behind a given action in our head, and assume that these are the same reasons behind the admirable action.
[94]. These sorts of actions require a more thorough explanation. Yet, these do not have a special motive, but it seems that Morton attributes these to a weakness of will. I am not convinced.

Distinctions between empathy and sympathy may either be: emotional resonance - feeling what another feels^[E.g., @gold04; @gold11], emotional appropriateness — having a suitable reaction to another person’s situation, emotional identification — having an emotion that makes you take their purposes to your heart
and their troubles as your concern. When we attempt to understand, by imagining, someone else’s experiences and motivations, we have to
“manage a tradeoff between completeness and accuracy” [@mort13, 109].

Our moral terms are motivated by our emotions.^[E.g., see @prin14; @haid09] Although the way our emotions make us feel about a situation may be inappropriate, or misguided, we cannot retract the fact that our emotional response was thus. However, we can have other emotions regarding our initial emotional response which are a kind of retraction. There are some emotions which allow us multiple perspectives. For instance, we might imagine a subjective perspective, say you feel the pain your friend might have experienced when his girlfriend broke up with him, but you might also have access to a more objective emotion wherein you feel the hurt caused by your friend when he cheated on his girlfriend.^[‘Objective’ here means, I think, not that it is some sort of physical fact, but that a person who saw the situation objectively — that is, not through one’s own eyes — would react that way” [@mort13, 128].] Moral emotions, given these multiple perspectives then, are imagined “complex emotions built out of two others. . . ” [@mort13, 131]. The first, we can imagine an attitude that we attribute to real or fictional persons. The second is this attitude as directed towards an action or pattern of behavior [@mort13, 131].

There is a great diversity and variety of moral emotions. These can correspond with imagined points of view. Further, they are generated by having simple emotions towards people and situations that branch off according to different points of view [@mort13, 139], a point of view which can vary. This might account for the problematic effects that empathy can sometimes manifest in our behaviors to strangers. Yet, having two perspectives which are oppossing [subjective and objective (in part)] to one another, will allow us to act as “impartial observers distant from the immediate situation [@mort13, 139]. Morton suggests that this process is similar to that expressed by Lawrence Kohlberg in his “stages of moral development.” However, it is not clear whether this is something that occurs when a child matures through the stages of development from child to adult, or is something relegated only to a kind of moral development which I think can come about later in life also. This varied perspective does not immediately justify discounting our emotional responses to situations. For instance, we might have an emotional experience because someone mentioned a crude remark. We might initially think that we are over reacting, but as we continue to think about it and attempt to imagine scenarios wherein the remark was benign, it appears to us that there was in fact no justifcation for the remark and therefore our initial emotional response is appropriate.

Moral Emotions do not necessarily enable moral learning, or prevent it: smugness, hypocracy, etc. For instance, “[w]hen you are smug, you feel approval from some respected source, directed at your general character and actions” [@mort13, 150]. Emotional smugness leads to two related outcomes. (1) You might have an attitude to others wherein you hold some advantage over them. Therefore (2) you become satisfied in your current state and therefore do not need change of any kind. 1 and 2 lead to complacency wherein you become comfortable in maintaining ideas of superiority over others; even if these ideas are not warranted.

Finally, because of the imagination, we can have an enormours range of emtions that enable our apprehension of varying points of view. Importantly then, are questions about apt emotional expressions. Morton takes this to be a question about apt immoral attitudes; attitudes that are harmful, frustrate our aims, etc. One way of making
the question manageable is to consider families of moral emotions—one example consists of the much discussed cousins regret, remorse, guilt, shame, and embarrassment — and the ways in which we can slide into one of them when another would make more sense. [@mort13, 157] If we have a concept of a particular emotion, we are then better able to experience that emotion. From families of emotions, we can choose which ones we ought to encourage one another to feel and determine which ones are obstacles to our moral lives [@mort13, 158].

### Moral Space in Narrative {-}

While Morton gives us a glimpse into why we should be more reflective on the beliefs we attribute to others, Martha [@nuss85; -@nuss86; -@nuss90; -@nuss95; -@nuss01; -@nuss01a] Nussbaum argues that the novel can be thought of as a paradigm of moral activity. In the Golden Bowl, we are made aware of the moral importance of the protagonist's recognition of his daughter's moral agency. This recognition is understood as a sacrifice on the father's part. "Prince Amerigo acknowledges, in an image of delicate beauty and lyricism, his daughter's sexuality and free maturity" [@nuss85, 519]. This acknowledgment is perceptual.

> James tells us that sacrifice is an act of imaginative interpretation; it is a perception of her situation as that of a free woman who is not bound by his wish" [@nuss85, 520] . . . Prince Amerigo assents to her pleasure and wishes to be its approving spectator, not its impediment [@nuss85, 520].

We are made aware of such developments and their moral significance linguistically and lyrically. Such lyrical organization expresses the feeling in the work which moves us through its detail, tone, and color. It is this emotional expression which shows us the new way in which Prince Amerigo has become acquainted with his daughter.

As Nussbaum points out here, "Moral knowledge, James suggests, is not simply intellectual grasp of propositions; it is not even simply intellectual grasp of particular facts; it is perception" [@nuss85, 521]. "It is seeing a complex concrete reality in a highly lucid and richly responsive way; it is taking in what is there, with imagination and feeling" [521]. In this way, moral communication is not only purely intellectual activity, but is also expressive of the specificity and of the emotional and imaginative richness of their individual moral effort [@nuss85, 521].

Because of this, we should consider emotions as a necessary condition of a good moral theory. The question is whether and to what extent emotions play a role in the moral praiseworthiness of a given action. One way we might see this relationship, is to consider the importance of actions grounded in the correct emotion. For instance, if emotions are "intelligent responses to the perception of value, then they are suffused with intelligence and discernment [@nuss85]. Another way is if the emotions themselves contain value and importance, then they are necessary for accounts of ethical judgment. We might perceive that an action that was done because of a given emotion is weighted more favorably than one that is not. If our emotions comprise such a central role in our moral judgments or morally praiseworthy actions, then developing an adequate moral theory will require us to develop an adequate theory of the emotions. But emotions can be notoriously misleading. A domestic abuse victim may forgive the abuse she suffers on account that she feels loved by the abuser.

According to Nussbaum, many cultural sources of such theories include narratives. What narratives can offer us, are affective influences which engage the imaginations of their audiences and given this, adequate ethical theories can point us towards "texts we need to turn to if we are to arrive at an adequate account of the emotions" [@nuss01, 2]. In his book *Acts of Meaning*, Jerome @brun90 argues that culture consists of a set of symbolic systems that societies use to construct meaning, man's "participation in culture and the realization of his mental powers *through* culture" [12]. Important here, is the view that not only do narratives affect us through our emotions, but that they also have cognitive content and because of the fact that their connection to the emotions, is more *robust* than non-narrative prose [@stum10a, 492, fn. 6; also see @call18d who also offers an unrelated but similar view.].

While I will not go specifically in the sort of knowledge narrative offers us here, important for my purposes is the relationship between fiction and *moral* knowledge, @nuss85 offers a similar view of narrative's relation to knowledge. She argues that narratives are tools for representing complex moral landscapes. Specifically for Nussbaum, morality is a question about how one should live their lives and can only be answered through the perceptual and expressive terms found in narrative art [@nuss85, 520]. Emotions shape the landscape of our mental and social lives according to Nussbaum and as such, a theoretical account of emotions will have large consequences for theories of practical reason, normative ethics, aesthetics and political thought. Here, the *good* in another's life can be represented in the literary imagination [@nuss95] and finally, "understanding the relationship between emotions and various conceptions of the human good will inform our deliberations as we ask how politics might support human flourishing" [@nuss01, 3]. To understand why an ethic of narratives is important for actions of moral value, I will begin with a major and some minor criticisms of this view. A reason why this is the case can first be understood through an understanding of Greek tragedy.

## 3 Narrative Excellence on Love and Friendship

In her chapter *Aeschylus and practical conflict*, Martha Nussbaum argues that Plato's criticism of Greek tragedy stems from its depictions of practical conflict grounded in the absence of logical moral choice available to its characters. The historical view of moral testimony sees narratives as the premier way to engage in moral testimony but Greek tragedy, on this view, is mired in narratives of seemingly good people with few choices available to them. As a result, these individuals, in performing the only actions available to them, invariably commit horrendous crimes against their own character and ethical commitments because of circumstances which lie outside of their control. As such, while there is a relationship between narrative and moral knowledge, Plato saw this relationship as a corrupting one then. For instance, in the *Republic*, he argued that because elements of all literature can be thought of as truthful to some extent, literary artists whose audiences consisted of children, should be highly censored by the state. As found in the *Euthyphro*, the statement: "By this argument, my dear Euthyphro, the pious and impious would be one and the same" (*Euthyphro* 8A), we see a related worry of apparent logical contradictions inherent in depictions of moral conflict in Greek tragedy. Plato was afraid that connections between moral knowledge and narrative would unduly undermine what little moral progress children may make.

### 3.1 Conflict in moral reason {-}

Conflicts arise in moral reason when the agent has equal reason to perform two conflicting actions. An easy way to view such contradictions is to imagine a moral agent conflicted because they have a desire that does not align in the proper way with what is practically the right action in a given circumstance. I may have enough money to pay the electric bill, but the amount that I possess is also the same as what is required to buy a certain video game. Other conflicts may resemble the agent who realizes they would never be able to divide their affections in the way necessary to satisfy both individuals or even themselves. Desires conflict in that such a person wants to spend their life with two separate individuals, but recognizes, perhaps, that they are constituted in such a way that they could realistically only truly enjoy such a relationship with one other individual. Perhaps Such conflict is usually not the central focus of Aeschylean tragedies however. At the very least, there are not the problematic ones with which Plato is concerned.

An aspect of the former conflict, is that we have an agent wherein regardless of the choice she makes, will always be left with some form of regret about her decision. The examples given before are tame when contrasted against more grievous ones. A man whose wife and children have fallen overboard may experience such a regret given their inability to save both wife and children, or if they will conceivably only be able to save one child. Regardless of which child is saved, the parent will always wonder in what way they've erred in their decision. It may be contested that such examples are really examples showing that in such situations, there are moments when we realize that the decisions of a moral agent are not always truly autonomous. In the *Nicomachean Ethics*, Aristotle gives the example of a tyrant who, having control over an agent's parents and children, orders the agent to perform a shameful action. Arguably this raises questions about what extent we might think such actions are free. However he makes a distinction between conditionally and unconditionally free actions. A conditionally free action is one where the agent would not choose a given circumstance and therefore the agent's response to the tyrant's threats, though conditionally free, are not unconditionally free since the agent would not choice the circumstance [1110.a4]. Although it is not my intention here, one interesting line of thought regarding to what extent our choices are autonomous can be found in the literature on adaptive preferences. Perhaps one example of this concern can be found in Aesop's fable of the fox and sour grapes where upon failing to procure a batch of grapes, the fox reasons that the grapes are sour. Jon @elst83 argues that the fox's judgment in determining the value of the grapes is irrational and unfree.

A preoccupation of Greek ethical thought is that the good human life is dependent on things that human beings do not control [@nuss01a, 343--372]. On this view, human excellence (those activities which enable a person's participation in a life well-lived) is in-part constituted by external resources and contextual conditions. Given the kinds of things we are (communal creatures), these resources include human relationships (e.g. citizenship, political attachment, personal love and friendship) [@nuss01a, 343].] This includes the search for self-sufficiency through reason and the limits of reason, but there are also three sub-problems: the vulnerable components of the good life; the contingent conflict of values; the ungoverned elements of the personality and the importance of works of literature as an indispensable part of a philosophical inquiry into these questions.^[Other notable literature addressing similar themes can also be found in @nuss85; @nuss01a; and @nuss01a]

> [Plato's] own creation of a way of writing that we deem 'philosophical' is linked with specific views about the good life and the human soul; we do his arguments against tragedy serious injustice by taking the distinction between philosophy and literature for granted and by assuming without argument that literary works are dispensable in an inquiry that aims at ethical truth. [@nuss90, 12]

If human excellence is contingent on external resources and necessary conditions then it requires intimate external objects which will receive the good activity of the excellent human [@nuss01a, 343--345]. Though all good human activities are in some way relational, some are more self-sufficient than others. Therefore there are important human values which lie at the opposite end of the self-sufficiency spectrum where on one end we have speculative thought, and relational goods (those connected with citizenship, political attachment and personal love) on the other.

Love and friendship are contingent on there being other persons to receive the virtuous activity; the just person needs those he can act justly towards. Therefore, love and friendship in themselves or as a specific type of political excellence are relations and not only states of character.

The relational goods are dispensable and we might think the pursuit of self-sufficiency requires cultivating a solitary life where we do not ascribe to relational goods given their fragility. Aristotle rejects this view, social and political relationships are valuable parts of the good human life because of human vulnerability.

The overall themes in Greek tragedy are that it shows good people being ruined because of things that just happen to them, things that they do not control a charge which has historically led to Greek tragedy being called primitive: in the Euthyphro; "stories depicting the collisions of competing claims of right are repugnant to reason, since they assert a contradiction, and as such, evidence of pre-rational thinking: 'By this argument, my dear Euthyphro, the pious and impious would be one and the same' (Euthyphro 8A)."

> Human excellence is seen, in Pindar's poem and pervasively in the Greek poetic tradition, as something whose very nature it is to be in need, a growing thing in the world that could not be made invulnerable and keep its own peculiar fineness.^["Some pray for gold, others for boundless land. I pray to delight my fellow citizens until my limbs are wrapped in earth---a man who praised what deserves praise and sowed blame for wrong-doers. But human excellence grows like a vine tree fed by the green dew raised up, among wise men and just, to the liquid sky. We have all kinds of needs for those we love---most of all hardships, but joy, too, strains to track down eyes that it can trust." Pindar, Nemean VIII.37--44. (as seen in @nuss90.)]

Membership and good activity in a political activity leads to the development of good character in a way that is more resistant to circumstances of luck, relational goods are important for the development of good character because moral worth is just in the vulnerability of human character development.

One important aspect of narrative (literature) is that it can motivate the question that if it is true that human beings are vulnerable in such ways, then how does the "goodness" of a human life warrant any moral praise if we think that these external conditions are necessary for a good human life?

> The problem is made more complex by a further implication of the poetic image. It suggests that part of the peculiar beauty of *human* excellence just *is* its vulnerability. [@nuss90]

Moral realities as viewed in literature, the standard literature argues, are a combination of some context standard emotional expression, representation of some significant emotional experience involving a aspect of human relationship, and a character or characters who express such emotions where we might ask whether the emotions exhibited by some character or characters are reflective of their vulnerability and need for others. As such, our participation in active political and social life is an important aspect of the development of moral character so that our actions begin to have moral worth.

Looking at those discontinuous aims of literary artists seems to undermine the importance which relational goods hold for virtue and moral worth. But why should we think that the conflict between moral worth and vulnerability to our environments should not exist? Denying the assertion that the content of Greek tragedy consists of competing claims of right action, Nussbaum argues that Aeschylean depictions of conflict in Greek literature and narrative reflect our intuitions better than theoretical solutions posited by claims that competing conceptions of right action represent a logical inconsistency. Namely, these other claims miss the connection between human vulnerability and moral worth.

### Love, Friendship and Emotion {-}

Narratives represent human emotional responses as valuable sources of information about the practical and as of high practical value of the emotion experienced by some individual character, even apart from this informational role about the person's experience [@nuss01a, 291]. As such, narratives have the ability to evoke emotional activity in the reader; representing a particular activity or circumstance, context etc, as valuable, both for itself and for its epistemological role, what it can teach us. On this view, emotions have a cognitive content and are intimately related to beliefs or judgments (about what is important and valuable) about the world.

::: {.remark}
\noindent There are two points which I want to continue by focusing on here:

1. What in narratives is thought to be valuable.
2. Human emotional responses to narratives.
:::

I argue that through a care ethics, this is much more salient,^[for instance see @slot07] where the idea is that "caring and (traditional) justice deliver contradictory moral judgments about certain cases involving (supposed rights of) individual autonomy [2]," I argue that such moral complexities the standard literature is concerned with, in large part, are how the expressions of empathy in literature, reveal complexities, moral conflict, at the heart of significant moral judgments. These reveal the importance of our emotional expressions in these judgments. I then go on to show how the discontinuity view of narrative undermines this importance.

Eleonor Stump in her book "Wandering in Darkness" argues that narratives give us insight into what communities care about. It also gives us insight into who the characters who comprise that community truly are.

> There is one last general point about methodology that probably needs to be made here. An important part of the examination of a narrative consists in reflection on the underlying thoughts or motivations of characters in the narrative, but some scholars will be uncomfortable with such an approach to biblical narratives. [@stum10a, 36]

\noindent In what follows, I look more closely at this insight.

Nussbaum argues that the function of narrative is evident in narratives which have a complex narrative structure. This structure evokes associated moral activities in the reader which includes human emotional responses associated with moral worth. Accordingly then, for an artist to recreate a perception as Nussbaum understands it, means that artists have an obligation to render reality, including this moral complexity [@nuss90, 524], but this assumes that art's function is to imitate life.

How might we defend such an obligation given that not all artists have such aims in mind? Are these other aims inappropriate? Why should we think that an artist does or does not have an obligation to represent a moral landscape as Nussbaum supposes?

We might think reality-directed emotion typically has the function of accurately appraising the objective individual-or species relative-value of its object. However, other fictional-and imagination-directed emotions are generated in practices that are constitutively oriented toward ends such as pleasure, entertainment, and absorption--that don't require that the emotions always be rationalized by the facts of the objects to which they respond [@gilm20, 75 ?]. In other words, the fact that we are merely caused to feel a given way may be a sufficient reason to feel that way. What justifies emotional responses towards fictional contexts are those that are ascribed to us, those that represent correct engagement with the work. One might ask however, why should ascription *justify* such reactions.

Gilmore argues that our desire to engage the work justifies the affectations the work calls for. To understand why then, we must first make a distinction between an appropriate emotional response and the appropriateness of allowing ourselves to experience a work we know will call on us to have such a response. Here, I readdress this question from a position of care ethical behavior. What we care about is not only desirable outcomes, such as affective and other emotional states. An approach to this may be that we utilize narratives as a way to motivate, educate others regarding desirable/apt affective states which represent apt emotional responses, those represent care in a relationship [@stum10, 39--63; @zagz17, 129--153; @nuss01a, 401--454; @choo21]. That is, while it is not possible to morally educate others through the use of moral testimony as traditionally understood, narrative as a form of moral testimony also means that we use narrative to morally educate.

I therefore argue that Nussbaum and other similar continuitists define narratives in this light.

### Normative Criteria of Emotion in Narratives {-}

The kinds of reasons that justify our emotions depend on the functions of the art in which our emotions are elicited. Some imaginative activities have epistemic or practical aims like that of beliefs and perceptions. E.g., planning for the future, or discovering some truth about the actual world, our evaluative commitments, or what is modally possible [requires citation]. The aims which justify emotional responses towards fiction are 1) based on reasons that speak to qualities of their object, or 2) not the arational result of some independent cause, but of an aim.

An emotion directed at fictional content is warranted if the fictional work from which the emotion is elicited is designed to evoke the emotion toward the object it represents, and succeeds in doing so by virtue of that design. Although works of arts can elicit emotions by representing situations which would analogously elicit that emotion in the real world, they can also elicit emotions without relying on such devices.

They may also offer internal reasons for a response, through music, lighting and other other tools irrelevant for our emotional responses in real-world scenarios. Using the physical appearance of a character to represent them as morally corrupt for instance.^[@nort97, @mcgi97]

Sometimes, our experience of an object in the real-world is different from our experience of it in a fiction. For instance, lets imagine an incompetent factory worker in the real-world. A fiction may represent this object differently from what we would expect in the real world. Charlie Chaplin's *Modern Times* depicts this in one scene where Chaplin gets trapped in the cogs of the factory's machinery. A work of art represents an object in the real-world through the relationship between the features of what it uses in its representation and what is depicted when our experience of the representation is different from what it would be if the object were in front of us. The devices used in literary works may involve 1) influencing our moods. @clor03 argues that evaluative, motivational, and perceptual states are primed using environmental events. Such moods can be sustained over time [@gree09]. 2) Affective contagion where we conform behaviors, postures, expressions, and vocalizations to those of others. [@hatf92, 153--154], and 3) Artists can recruit audiences to adopt a character's or narrator's point of view on some state of affairs [@gilm20, 124] without relying on depictions we would expect outside of that fiction.

Because ascriptive devices used by the artist may explain why an audience has the emotional experience that it does, e.g., Joy in the case of *Modern Times*, a positive affiliation with a fictional character might not be justified by what we know of him, but can serve as an artistic end anyway, our scorn for a character might be elicited by arational causes and still justified in the confines of the experience of a fiction [@gilm20, 124]. Here the emotion is grounded in a reason which speaks to the facts in the fictional scenario, which would not necessarily carry across to a real-world scenario.

The facts which are ascribed, rest on the ends towards which the creation of the fiction is directed. These include pleasure, entertainment, and absorption. One reason in which we might think that these particular ends do justify the responses we have towards them, is because we are first making a distinction between the appropriateness of our response, and the appropriateness of allowing ourselves to experience a work upon the realization that it will call for a certain response.

By emotionally responding in the way that is prescribed to us, we are aptly, appropriately engaging with the literary work. It is only descriptively, but not normatively that the aptness of our emotional responses holds across real and imagined domains.

Though it may seem that we do have normative requirements to respond emotionally in a way that is beyond the ascriptive devices used by an artist, this is only because we have not made the requisite distinction between an appropriate response and appropriate engagement. By engaging with the work of art in the first place, we have already accepted that our engagements with certain works of art is appropriate. Accepting this then, our emotional response is appropriate given that it represents such an engagement.

Therefore, there are some kinds of reasons that justify an emotion felt toward a state of affairs represented in a fiction or imagining that would not justify that emotion when felt toward an analogous state of affairs in the real world.

## Ethics of Care and Moral Narratives

What justifies an emotion felt depends in large part on the aims of the artist.^[As noted by Suzanne S, Choo in her critique of contemporary aesthetic evaluative practices, the traditional view of artistic purpose is that art and beauty are ends unto themselves [@choo21, 15].] Whatever means enable the artist to achieve these ends, justifies our own emotions felt towards that artwork assuming that such emotions were the results intended by that artist in our appreciation of their work [@gilm20, 132].

### Imaginative Representations of Morality {-}

Martha @nuss85 on the other hand argues that the work of art is to model life by modeling/representing the moral landscape [521]. The task of seeing and representing moral frameworks, given the complexity of moral particulars, falls on the literary artist who strives to recreate the moral landscape. But this as Gilmore notes is not the aim of all artists.^[@walt90 has argued that at least some works of art function as props enabling imaginative representations of the real world. Here the art itself is a prop which aids in generating a truth particular to a piece of fiction. For instance, understanding Andress Ingrid as representing a moral framework then: "I can't wait to show you where I grew up. . ." and ". . . probably feel like you've been there before," we should think that in this particular fiction, there is a place where someone will feel something like nostalgia, or comfort, upon visiting the childhood home of another. Shannon @spau16 provides a nice overview of the relationship between knowledge and imagination.]

But there is a case to be made that artists attempt to contribute to our well-being in some way. A way for them to contribute to these aims includes using literary works to explore questions about what it means to live well [@nuss85], for instance, where we would feel excitement at introducing a close relation to family and old friends and this being a significant event in a well-lived life [See @nuss01a].

Reality directed emotion typically has the function of accurately appraising the objective individual-or species relative-value of its object. The question then becomes about functions of narrative and whether the aims can be anything other than contributing to a well-lived life, which includes asking questions about what this means and so on. I will look at this question from a care-ethical point of view, where caring about others is a characteristic of living a meaningful life. There are other questions however, which might also be asked here. Assuming that mirth is an important component of a well-lived life, then entertainment may also be a viable goal for the artist. It is not clear however, whether or not entertainment can supersede other potential goals. We can imagine William James, although succeeding in creating a work that is true to the admirable experience of a life that is well-lived, fails spectacularly to do so in a way that is interesting. Are banal pieces of art failures? @elpi22 argues that boredom is an aesthetic tool used by artists to draw our attentions elsewhere. In this sense boredom allows the artist to communicate other arguments via our emotions.

We might think that apt emotional responses to fiction ought mirror similar engagements in the real world. When we witness Madame Bovary's discontentment with domesticity, one might think that assuming we think ours and her response is apt, similar discontentment with domesticity would also be apt in the real world. A character's response might be a reliable guide of possible counter-factual responses in the real-world.

Considering the potential relationship of narrative and moral knowledge, we should first disambiguate when an artist prescribes affective states in a continuous way and when they do not. By looking at affect and art when these are continuous with the real world, we can see with more clarity the relationship between affect and moral worth. But where these are discontinuous, we see possibilities regarding our affects. Below, I first articulate narrative disconitnuity. In the section following this, I motivate the view of narrative on the consideration that the relational goods, namely political/social activity, relationships between individuals is important for moral character.

### Narrative Discontinuity {-}

There are two versions of the continuity thesis:

```{.remark}

Whether our evaluations, emotions, desires, and cognitive representations can be explained in a way that is largely indifferent to their genesis in, alternatively, imagination and belief. Can our affective faculties be explained apart from their source in imagination and belief [8]?

```

```{.remark}

The question is whether the kinds of reasons that can serve in the justification or criticism of such responses are invariant across imagined and real-world contexts [@gilm20, 8].

```

Some concerns include the point that the cognitive mechanisms behind such engagements are consistent with those behind such engagements in the real world. There are epistemic reasons to attribute facts to a fiction that do not hold when attributing similar facts to the real world. Make believing then, is not epistemically rational in the same sense as believing, and the norms governing our desires, emotions, and moral evaluations vis-a-vi what is internal to a fiction can be inconsistent with those governing our responses to relevantly similar things in the real world

Considering the normative question then, the criteria governing the aptness, fit, or rationality of our emotional, cognitive, and conative engagements with the actual world are continuous with the norms governing those attitudinal engagements with fictional works of art and objects of the imagination [@gilm20, 9].^[On Quasi-emotions, Kendall @walt90; @walt94, 215. Also see @curr85. For other defenses of Descriptive Continuity, see @livi01.] Gilmore defends our affective responses to fiction on account that these represent apt engagements with the artwork, as the artist intended.

Therefore, a person's emotional response to fiction is not an unmediated reflection of his or her character and genuine desires. As such, it is not the case that stories evoke a reader's responses by giving her reasons for them that would apply in the real world. However, given his acceptance of the descriptive claim, it is not clear that our responses to fiction are not unmediated reflections of our desires and other aspects of our character, nor is it the case that our characters are not influenced by such evocations, following [@arpa04; @stum10; @zagz17; @nuss85; @nuss90; @nuss01a.].

> Philoi, says Aristotle, are 'the greatest of the external goods' (EN II69b10) . . . the love of Nick and child is a paradigmatic case of *philia*; all close family relations, including the relation of husband and wife, are so characterized. [@nuss90, 354]

@stum10 argues that a kind of knowledge that allows fully functioning human beings to know the ''actions, intentions, and emotions of another person in a direct, intuitive way'' [80], and can be gained by second-personal experiences
[81]. Referencing Saint Dominic, and Saint Francis' ministries, she argues that St. Francis' ministry, unlike St. Dominic, was facilitated both through
direct experience of Francis' character, and through narratives which
spoke of his character. This made possible a ''personal
connection to Francis, either by personal experience of Francis or by
the knowledge of Francis garnered from stories about him'' [@stum10, 45]. This kind of knowledge is different from knowledge about Francis however, for
instance, that he is a person, or that he is human etc, propositional knowledge.

Knowledge of persons, argues Stump, is a type of perception. So while,
for instance, an individual might know that Joan is her mother, and
that Joan is sad; without knowledge of persons, second-personal knowledge, the individual does not know by direct perception or experience that her mother is sad. She may know that Joan is sad through some other source of knowledge such as reflection, but she does not perceive that Joan is sad. There are things then, that we can know Fransicanly that we cannot know Dominically, one of which is the knowledge of persons as a kind of direct perception.

@zagz17; @stum10, chs. 2--4; @arpa04; @nuss85; @nuss90; @nuss01a; show us that those perceptions involved in close and meaningful relationships provide the basis for what moral epistemologists may call moral knowledge. Here, caring relationships are characterized by emotional sensitivities between persons, and these resemble something like empathy. Accordingly, narratives have the ability to intimately acquaint one individual with another [@stum10], where a fully functioning human being can come to know the

> actions, intentions, and emotions of another person in a direct, intuitive way. [@stum10, 80]

\noindent And can be gained by second-personal experiences [@stum10, 81]. Similar to Nussbaum, on this view, narratives provide a more clear picture of this particular landscape. But as we've seen, it is a highly contentious issue whether the literary artist is attempting to accurately reflect emotional moral frameworks in narratives and whether we are justified in treating narratives this way.^[For instance see, @gilm20]

\noindent In this project, I do not attempt to offer an answer to the continuity question. Rather what I intend to do is first model what the artist is proscribing to us regarding this relationship. How do we define areas in literature where the literary artist is articulating the emotions of the characters involved, attempting to evoke our own sympathies, or making normative claims about which emotions belong and who or what should be experiencing them.

### Immediate Concerns {-}

It is not often clear that all examples of literature contain what Stump and Nussbaum may call moral knowledge. For instance, we might think that due to the complexity of the moral frameworks depicted in narratives, one may argue some literary engagements are better than others. That these contexts (in the lesser works of literary art, e.g. popular music lyrics) will not sufficiently express the complex moral frameworks the standard literature, finds in literature. The moral frameworks addressed by Stump and Nussbaum are often very complex, but sometimes this may just mean linguistically lengthy, or involving either classical speech patterns, adhering to grammatical norms; conforming to traditional notions depicted in literature etc. The emotional type states expressed in such frameworks are often similarly complex. They may concern multiple emotional states which involve more fine distinctions. Given the careful attention and temporal dedication to such representations, it can be said that such descriptions as provided by various narratives, can only be found in some literary works, i.e. high art.

A problem with this view, is that it is often argued that classical pieces of literature, possibly owing to their length, their linguistic complexity, the culture or cultures; they are thought to represent etc, will express moral features better than popular, i.e. vulgar artistic representations. This is a problematic view. I will argue that denying the relationship between moral knowledge and vulgar artistic expression makes it hard to see the relationship between such art and moral knowledge. An even more problematic point of this feature, is that it might undermine our ability to see corrupting influences in art. I want to motivate that narrative can contribute to one's moral knowledge, then following @mcgr19, it can also undermine one's moral knowledge.^[For instance see @mcgr19, esp. ch 5.]

Through this project, I hope to show, that regardless of the degree of the complexity of such frameworks, that they can nevertheless be found elsewhere, for instance music lyrics. I do so by defining a narrative as the representation of an emotion context pair.

The particular moral frameworks that I will look for in my conception of narratives, are conceptions of caring concern between two persons. This caring concern I argue is marked by feelings of empathy between two individuals or more individuals.^[@nodd84 offered an early version of the ethics of care. Martin @hoff00 connects care to empathy. @slot07, who argues some of the earliest care ethicists where individuals such as Francis Hutchison and David Hume, also defends such an ethic of care based on empathy.]

My goal for this project then, is to develop a model by where narrative is a method for uncovering moral complexities. A point that I will come back to later, is that I define the moral complexities mentioned by Nussbaum as empathic relations between individuals.

Regarding perplexing situations wherein our sympathies misalign with our moral principles, narratives are doubly important for showing us situations in which our moral reasoning can become conflicted. What happens is that our judgments come into conflict with our moral perceptions, and our moral perceptions win out. In the book *The Golden Bowl* by Henry James, as noted by Martha @nuss85, of particular moral concern is the new-found ability of the protagonist's father to recognize the unique individuality possessed by her.

The pinnacle of such a recognition is a state like empathy wherein the emotional states of the moral knower align with those of the one known:

> Moral knowledge, James suggests, is not simply an intellectual grasp of propositions; it is not even simply intellectual grasp of particular facts; it is perception. It is seeing a complex concrete reality in a highly lucid and richly responsive way; it is taking in what is there, with imagination and feeling. To know Maggie is to see and feel her separateness, her felicity; to recognize all this is to miss least of all. [@nuss85, 521]

This moral reality consists of such a relationship---where each is intimately (non-cognitively) known by the other---between two individuals:^[Also see @stum10, chs. 2--3 for a separate defense of this claim.]

> ... but by showing the extent to which fine attention to another can make two separate people inhabit the same created world . . .. Together they give birth, in love and pain, to a lucid description of the moral reality before them. [@nuss85, 522]

The motivation surrounding this project then, consists in devising a method of uncovering moral situations such as those above, in *all* narratives. Uncovering moral and anti-moral reality alike. If we think that there is any merit to her claims, that narratives can express contexts wherein we might find moral landscapes as perceived by Maggie and her father, areas wherein two characters come to know one another intimately enough such that their judgments become negligible, then we might consider that it is possible to classify art by its ability to recreate moral contexts.
