# Emotionism

## Sensibility

### The Emotional Construction of Morals (Prinz)

1. Sentimentalism by Michael Slote
2. The Discernment of Perception, Nussbaum 1990

**Metaphysical Emotionism:**

* Darwall et all., 1992
* McDowell (1985)
* Wiggins (1987)
* D'Arms and Jacobson (2006)

**Epistemic Emotionism:**

* Gibbard 1990
* Ayer 1952
* Stevenson (1937)
* McMillen and Austin 1971

### Apt Imaginings (Gilmore)

**Moral Judgments and the Emotions:**

* Greene et al 2001
* Lerner et al 1998
* Tye 1995, 100. Intentionality
* Sentimentalism about Moral Understanding

**Representative Appraisal Theories:**

* Arnold 1960
* Lazarus 1984
* Smith and Ellsworth 1985; Scherer, Schorr, and Johnstone 2001; Smith and Lazarus (1993); Schacter and Singer (1962)
* Greenspan (1988); de Sausa (1987); Roberts (1988)

**Cognitivists Theory of the Emotions:**

* Nussbaum 2001; Solomon 1993; Lyons 1980; Kenny 1963; Gordon 1990; Lazarus 1984; Lazarus 1991
* Nussbaum 2004
* Goldie 2000; Goldie 2009 (distinctive kind of evaluative state)
* Prinz 2004

2. Chapter 3 of Apt imaginings

### Fragility of Goodness, Wandering in Darkness

**Sensibility and Well-Being:**

* Nicomachean Ethics
* Chapter 14 of Wandering in Darkness
* Vulnerability of the Goodlife 1, and 2 (Fragility of Goodness)
* Finely Aware and Richly Responsible, Nussbaum 1990

**Tragic Emotions:**

* FG Interlude 2: Luck and the tragic emotions
* WD, Ch. 9, The Story of Job: Suffering and the Second-Personal
* That Obscure Object of Desire: Pleasure in Painful
Art [pdf]
