---
title: Introduction
type: docs
bibliography: ["/home/redapemusic35/data_storage/library.bib", "/home/redapemusic35/data_storage/my.bib"]
weight: 2
---

# Imagining Identity


```{r, echo=FALSE}
knitr::include_url("/home/redapemusic35/courses/hugo-book/static/slides/dissertation-slides.html")
```

## Normative Discontinuity


> . . . make-believing is not epistemically rational in the same sense as believing, and the norms governing our desires, emotions, and moral evaluations vis-a-vis what is internal to a fiction can be inconsistent with thsoe governing our reponses to relevantly similar things in the real-world. [@gilm20]

The aptness of our emotional response to what is true in a story is grounded by a different set of norms than the aptness of our emotional response to what is true in real-life. I may laugh at Charlie Chaplin being crushed in the cogs of a machine, whereas in real-life, the appropriate emotion would be closer to panic.

This is because the functions of our engagement with truths in a fiction are more comprehensive than the functions of our engagement with truths in real-life. The affective norms for real-life are grounded in functions such as accurately representing the criterial properties of some object in the real-world. The fear that I experience upon hearing the sound of a small rodent is apt just in case there are criterial qualities relevant to the rodent, such as disease, that license such an affection.

The affective norms that justify a given affection in fiction include functions such as entertainment, pleasure, and absorption.

But consider the following two stanzas from popular songs:

> There are three wooden crosses on the right side of the highway\
> Why there's not four of them, Heaven only knows\
> I guess it's not what you take when you leave this world behind you\
> It's what you leave behind you when you go\

Assuming that the previous is a moral object, given a sentimentalist ethical view, we might think that it warrants positive emotions. All persons die. But more importantly, there are some individuals who are the source of found memories such as Ghandi, while others such as Hitler are the source of unpleasent ones. What the above says is that our time on earth is short, it would be better to use it to create pleasant rather than unpleasant memories. The problem however, is not its truth value necessarily, but rather that as a fiction, we should suppose that the norms of truth are suspended and as such, it is not clear what an apt affective norm would be.

## Suis quot vota

Ea _furtique_ risere fratres edidit terrae magis. Colla tam mihi tenebat:
miseram excita suadent es pecudes iam. Concilio _quam_ velatus posset ait quod
nunc! Fragosis suae dextra geruntur functus vulgata.

## Tempora nisi nunc

Lorem **markdownum** emicat gestu. Cannis sol pressit ducta. **Est** Idaei,
tremens ausim se tutaeque, illi ulnis hausit, sed, lumina cutem. Quae avis
sequens!

    var panel = ram_design;
    if (backup + system) {
        file.readPoint = network_native;
        sidebar_engine_device(cell_tftp_raster,
                dual_login_paper.adf_vci.application_reader_design(
                graphicsNvramCdma, lpi_footer_snmp, integer_model));
    }

## Locis suis novi cum suoque decidit eadem

Idmoniae ripis, at aves, ali missa adest, ut _et autem_, et ab?
