
# Teaching Philosophy

I am a recent PhD in philosophy from Saint Louis University. My work has been in philosophy of mind, cognitive science, and moral psychology where I focus on questions regarding the formation of human agency. In August, I defended my PhD dissertation on moral epistemology and narratives. In my academic work, I focus broadly on narratives themselves, and what narratives can do for human moral knowledge and understanding.

I have taught undergraduate courses in Ethics, Critical Thinking, and Self and Reality. In my courses, I focus primarily on stories, highlighting how they can change our perceptions. I designed and delivered a custom asynchronous Philosophy-Digital Humanities course, where I integrated teaching methods relying on technology to enhance student engagement and critical thinking skills.

I organize my materials and feedback around the principle that for a concept to be truly memorable, it must hold intrinsic value for the student, a key component of healthy learning environments. As such, my courses push my students to reflect on storytelling and personal engagement. In my student evaluations, my students have noted that they often receive more instruction from the course material and each other, than from my lectures. I believe that many of our formative experiences are sourced in our relationships with others. Therefore, I try to leverage this fact, providing opportunities for them to learn less from the material that I carefully and thoughtfully curate, and more from interpersonal conversations about the material, since we are a community.

I try to bring the class to reflect on the fact that some mediums engage our emotions more than others, for instance fiction rather than a legal brief. I then ask whether we should think that our emotions are more meaningful for our judgments than are our beliefs and pre-commitments. My students have often reflected that this approach helps them to see philosophical questions as central to a meaningful life. In my classrooms, I pursue the following values in my courses.
Critical thinking, listening, self-inquiry and reflection. These are central to understanding. Based on my experiences in the digital humanities, I use artifacts from popular culture, songs, shows etc., in my assignments to motivate students to apply their experiences outside of the classroom to the course material. Which promotes personal engagement with course materials that in turn prompts the student to pursue philosophical insight for its own benefit. This approach is interdisciplinary, and blends philosophical concepts with digital tools, and focuses on a dynamic learning environment for diverse student groups.

In addition, I have implemented adaptive learning strategies, tailoring course content to individual student needs, resulting in mixed results.

I have also facilitated online discussions and group projects, cultivating a collaborative virtual classroom that promoted peer-to-peer learning and knowledge sharing.
I also work towards developing a forward-thinking curriculum that bridges traditional philosophical inquiry with contemporary digital literacy.

This prepares students for an evolving academic landscape that requires an increasing familiarity with digital and computational technologies.
My most recent pedagogical projects look to incorporate game play footage and game play as a form of philosophical thought experiment into course discussions.

## Experience

I began my PhD studies in 2018. In 2019 and 2020, I was the assistant to the editor of the department’s journal, Res Philosophica. Since its founding in 1925 (as The Schoolman), Res Philosophica has been a particularly important publication in academic philosophy. From 2020 to 2022 I was also the assistant to the editor of Schutzian Research, a central publication dedicated to the thought of Alfred Schutz. In both positions, I streamlined the editorial process, enhancing publication efficiency. In part, I adopted an algorithm which extracted bibliography information and encoded it according to latex standards. I also conducted thorough manuscript reviews, ensuring high-quality content. For each issue, I coordinated with authors, reviewers, and editorial board to facilitate a smooth publication process. This enabled me to foster strong relationships and improve communication and productivity. I worked to ensure the authors adhered to submission deadlines, ensuring timely publications.

From 2022 to 2023 I was the graduate assistant for the Walter J. Ong Digital Humanities Center. While there, I conducted digital humanities research, analyzing historical texts using computational methods and techniques from natural language processing. I helped students and faculty develop digital humanities projects. In at least one example project, I helped students design projects analyzing and recovering expressed sentiment from a group of texts considered formative to modern Hindu culture. We built a database to store student annotations of the materials and a website to host the findings and developed data visualization tools to present findings effectively. I also pioneered novel approaches in digital text analysis, integrating machine learning algorithms to uncover hidden patterns in literary works. I often partnered with faculty to design and implement digital projects, enhancing interdisciplinary research capabilities across humanities departments. This required that I meticulously curate and maintain digital archives, ensuring data integrity and accessibility for future research endeavors. I also applied computational methods to analyze historical and contemporary texts.

I am currently a member of the Saint Louis Digital Humanities Network. This is a group of educators in the Saint Louis area that are committed to exploring ways and implications of expanding use of technology for pedagogical purposes. As our digital technology develops, more and more of our social lives are being conducted through digital mediums. Given that my philosophical interests are motivated by questions about our social environments, these new modes of social interaction are of great interest. I am currently working on developing a philosophy course that I intend to conduct in virtual environments, namely in Massive Multiplayer Online communities (MMOs). I hope to collectively explore implications for conducting our lives in digitally represented social environments by using philosophical reflection to better understand how online communities can be used as a social learning environment.

I have a book titled Play and Meaning, an epistemology of emotional testimony in contract with Vernon Publishers. In it, I explore the view that stories are a form of play that use our emotions to teach us what it means to live well. In addition, I have four paper projects near completion that explore concepts related to imagination and well-being.

I am excited about the opportunity to contribute to a learning environment that seeks to engage the student population in meaningful philosophical discourse. My interdisciplinary experience, and philosophical rigor combined with innovative pedagogical methods will be a terrific addition to your department. I would welcome the opportunity to discuss my qualifications and the needs of your department further. Thank you for your time, and for your thoughtful consideration.

