---
bibliography: ["/home/redapemusic35/data_storage/library.bib", "/home/redapemusic35/data_storage/my-library.bib"]
display: block
---

How do we understand the correct meaning for the word 'friends'?

***Kanye's *Real Friends*:***

Real friends, how many of us?\
How many of us, how many jealous? Real friends\
It's not many of us, we smile at each other\
But how many honest? Trust issues\
Switched up the number, I can't be bothered\

Which we can compare against the usage of the word 'friend' in Alex Jean's song *Dying to Self*

***Alex Jean's *Dying to Self*:***

You show me just how to move\
Love how you call me a friend\
You wanna make me amazing moving adjacent I'm going up in demand\

Importantly for the purposes here, I want to understand the sentiment valance. There are two possibilities, the sentiment valance is either positive or negative. We can represent this with a number, either below zero or above zero, -1- or 1+.

Natural Language Processing refers to attempts to make language meaningful with computational methods. It is important for very basic computer usage, from email classification systems protecting our in-boxes from a deluge of spam, to automatic translation systems on websites like Youtube and Google. These work because human language has become accessible to computers, and as such, computers are better able to carry out the function we've come to expect of them.

There are a number of applications that together make up natural language processing. These include computational linguistics, machine learning, artificial intelligence, computer science, speech processing, and ethics. Importantly, the overall discipline underlying and uniting these functions are statistical analyses and probability assessments, both functions making possible other functions important for natural language processing, including text classification, prediction and so on.

For instance, consider the following sentence:

> (1.3) Umashanthi interviewed Ana. She works for the college newspaper.

We could ask 'who' works for the college newspaper. Namely, we are in part, asking what is the proper classification for 'she'. How should we label the pronoun? Do we label it 'Ana' or 'Umashanthi'? While this may be obvious for us, computationally, it is a more pressing question. For instance, there are several important factors. Any element of language, word, phrase, sentence, or even a sound can be described from three perspectives [@eise19, 9].

The word journalist is a subcategory of a profession, journalism. Anchorwoman is a subcategory of journalist. And, a journalist is an individual who performs journalism. Because Umashanthi is interviewing Ana, Umanshanthi is more probably a journalist. Further, because a journalist is more probably a person working for a college newspaper, Umashanthi is most likely the referent of the pronoun she.

Profession

{{< katex display=true class="optional" >}}

Profession {$\to$ Journalist}

{{< /katex >}}

Journalist

{{< katex display=true class="optional" >}}

Journalist $\rightarrow$ anchorwoman

{{< /katex >}}


{{< katex display=true class="optional" >}}

Journalist $\rightarrow$ journalism

{{< /katex >}}

{{< katex display=true class="optional" >}}

\frac{1}{\Gamma(s)}\int_{0}^{\infty}\frac{u^{s-1}}{e^{u}-1}\mathrm{d}u

{{< /katex >}}

What the above represents is a feature of text classification, where we are attempting to understand the meaning of the phrase 'She works for the college newspaper'. On the one hand, we do this using NLP principles such as text classification, by applying a classification analysis to the pronoun 'she'. Another form of text classification is determining the proper sentiment classification to ascribe to a text document.

Similarly, 'friend' can also be described from three perspectives. 'Friend' is a subcategory of another sentient creature, whether human or not, consider a dog for instance. A 'friend' can also be a subcategory of a social class, 'out of all the members of phi kappa kappa pi, he only considered Jose to be a true friend'.

Here, one way to computationally understand the meaning of friendship, or 'friend', is to consider what might be a natural sentiment when we or mention their name or otherwise reference them in conversation. In fact, some of our early research supporting theories we now rely on in NLP, involved assessing sentiment ascription to various terminology in an attempt to understand how humans attribute meaning to abstract symbols used in language [@osgo57; @moha21].

# References
