# The Question

I have been in higher ed for 15 years now and I have never written a diversity statement. To be fair, I think that only nine of those years truly count. In 2009, I moved to Broken Arrow, Oklahoma. Although I am a tad embarrassed to admit it, I was playing with a "rock" band at the time. It was definitely a time of growth and discovery for me. The year prior I had moved from Palmdale, California to Seattle, WA. The year prior to that, I had moved from Los Angeles where I lived most of my formative years. I say "formative" because like many other Los Angelenos, I was a transplant having moved to Compton a day or two after my eleventh birthday in 1988. Prior to this, I was the only child of a single mother, also a flight mechanic in the United States Air Force. Because of this, I was born in Okinawa Japan.

From 2008 until 2009, I did nothing but slowly come to a realization that I would likely need to find something other than the band to occupy my time. Perhaps because of my diagnosed ADD, for me this meant finding a new obsession. In August 2009, I began what I call my career in higher-ed, although it wasn't really a career in higher-ed. In reality, out of boredom, I began attending a bible college called Rhema bible college. It was drastically different than anything I had been introduced to. Unlike any of the other student attendees, I didn't make the decision with the view that it was my calling or anything like that. I didn't sell all of my possessions and travel bareback on a donkey across the prairie grasslands of the western United States. I wouldn't say that I was cynical either, just bored and too poor to go back to Seattle. I was also a bit disillusioned at this point as well. Not because of the music stuff, but because I had never before seen myself leaving the west coast.

It was a unique experience however. Rhema, I think branded itself on being a cross between the charismatic, faith teaching, and more sensible traditional protestant doctrinal messages. While there were attendees who from time to time would stand-up and run around the room during a lecture, I never got the sense that this was being encouraged by the instructor. I think that there was a lot of grace and patience offered by them in recognition of the student's excitement. Many of these were kids who would not have been accepted anywhere else, having grown up in conditions that even I couldn't imagine even though I had lived in some of the most repressed places on the planet.
