# Sharing Morally Good Intuition with Others

In a previous section, I argued that what is wrong with moral testimony as traditionally conceived, is that it fails to account for the more robust form of moral understanding that we are looking for in cases of moral knowledge. I then defined a version of social testimony in which the focus is on cultivating strong pro-social emotions. I then define moral testimony in terms of this cultivation. According to this criticism, there is something important about the emotions that derive from our moral experiences. How we react emotionally to reports of genocide are important concerns in understanding whether or not someone possesses moral knowledge of the proposition *genocide is morally wrong*. Moral testimony as traditionally conceived, fails to account for this.

There is a worry about this approacho though. Given that a large portion of moral testimony consists in narratives, it would be useful to understand some of the more prominent forms of narrative in order to understand our moral emotions. However, as Jonathan @gilm20 points out, our emotional responses to fiction often diverge significantly from those we have to objects and events in the real world. In this section, I draw a relationship between fiction, and the more robust form of moral understanding referenced in the previous chapter. Here, I argue that some questions which have been raised in the epistemology of fiction literature are related to a similar question about moral understanding and its relationship to fiction. But first, we need to confront one important objection to such a view.

@gilm20 references various criticisms of the view that the emotions we have towards fiction are of the same kind that we have towards events in the real world. He first adopts a functionalist view of imagining. Through the use of my imagination, I can envision the steps that I need to complete in order to finish a long project for instance. Here, imagination and other mental faculties are defined by the functions they perform rather than the behaviors they are associated with.^[See @bloc80a] Imaginings are context dependent, planning a trip motivates different imaginings than does watching a film for instance [p., 19]. Accordingly, in cases of fiction, we can differentiate the faculty of imagining from belief by referencing imagination's connection to volition instead of truth for instance. We can differentiate imagining from other mental states by the contexts in which they function, a belief aims at truth while imagining aims at desire satisfaction.^[E.g., see @gilm20, 17--18] In a similar vein, pain for instance, as a mental state, can be defined by the relations between it, and all other mental states related to it. As such, imagining is better used to describe our relationship with fiction than is belief.

One such function of the imagination is its ability to enable us to understand the goals, motivations, and behaviors not only of people in real life, but also those in fiction.^[@gold03c] Imagination then too, can enable us to evaluate characters and contexts in a fiction. I can imagine what bribe would be large enough to get out of a speeding ticket for instance, or instances that would justify such a bribe for a given character. I would more readily forgive one who bribes an immigration official to help his family escape certain death at the hands of a merciless authoritarian government before a wealthy politician who bribes a school official to place their under-achieving child in a top academic program.

Often times, the contents of our imaginings are emotional or they motivate various emotions in me. For instance, my imagining of various consequences is often accompanied by emotions such as fear of arrest or regret of losing our employment. According to some then, emotions are evaluative.^[See @arno60a; @arno84; @arno71; @laza84; @laza91; @smit84; @smit85; @smit93; @sche01] Evaluative emotions can accompany our moral judgments which are grounded in or grounds our emotions, e.g., of approbation or praise. Importantly, we can have such emotions towards real or fictional objects and there is purported to be a strong correlation between the emotions that we have and our moral judgments. A known view in psychology of emotions and moral psychology then, argues that emotions are evaluative representative states of things in the real world [E.g., see Jonathan @gilm20; @arno60a; @smit93; @laza84; @sche01; @smit84, to name a few.].

Similar to fiction more generally, we often experience music and other art as a swirl of emotions.^[E.g., see @gilm20] While the emotions that we experience, are evaluative representations of that object, the connection between these emotions and our moral judgments are not as clear. To fear a dark shape late one night in a back alley would evoke fear in many of us. Evaluatively then, our feeling is the expression of our evaluation of that object, such as fright.^[E.g., @arno60a; @laza91] However, the emotions that we experience in relation to art, are in some cases the direct work of the artist, seeing a large dark shape in the alley when watching batman, we might instead feel a sense of justice. If all of this is true, then we may ask an analogous question, whether emotional responses are also evaluative representative states to fiction as well. If so, when the creator of a fiction makes a fictional utterance, that utterance is often intended to cause an emotional response in us.

One concern that has been expressed, is whether our cognitive moral judgments inform our perceptive responses regarding what emotion we experience, or whether the emotion we experience grounds the corresponding judgment. Here, Nussbaum in her reflection on Henry James' *The Golden Bowl* suggests that we have particular judgments already, and the emotional responses we have can inform us of what those value positions are.^[@jame84] For instance, we may not realize our deep affection for a friend until their wedding day to someone else.

> Moral particulars are complex. We often refuse to see the moral landscape for what it is. The literary artist is the individual who strives to recreate this landscape in all of its complexity. What is it to live well is a question explored by literary works, and a question which can only be explored by literary works. As such, the novel can be a paradigm of moral activity.^[@nuss01 gives a detailed defense of emotions as judgments of value. Accordingly, the emotions we have are indicative of the value these objects hold for us. Her view raises other important questions which I will introduce later on.] Those who think that our moral judgments determine our evaluative emotion, are called cognitivists while those who think our emotions inform our cognitive judgments, are non-cognitivists. [@nuss85]

What is important here, is the concern over whether the emotion that we experience in response to a given fiction, is the same kind as those we experience in real life [@gilm20, 59]. The emotion we have in relation to some object, some take to be an expression of the value that we ourselves place in that object, what Nussbaum would call the *moral landscape*. So the question is that assuming some given moral aptness to the expression of a given emotion, say loss at the dissolution of an important relationship, whether the criteria governing such emotional expressions accompany our responses to fiction. When a song requires that I experience hatred in a context that I might otherwise feel forgiveness or mercy, this is because the author is telling us that this is the appropriate emotion in that context instead of the one I might normally have had.

This is because in the context of fiction, I might adopt the phenomenal states of that character, experiencing the world in the same way that the character does while in real life, the phenomenal character of the emotion is more dubious, perhaps here in real life, the emotion is more dependent on my moral character rather than that of the fictional character. The connections between the more deliberate operations of our cognition, such as judgment, and the reactive ones such as emotion, are not clear in the fictional context. It may be hard to determine how our emotional responses to fiction are grounded, in what part of our cognition they originate.

## Fictional Worlds

Similar to fiction more generally, we often experience music and other art as swirls of emotion.^[E.g., see @gilm20] Often, it is the case that the emotions that we experience, are evaluative representations of that object. Evaluatively then, our feeling is the expression of our evaluation of that object, such as fright.^[E.g., @arno60a; @laza91] However, the emotions that we experience in relation to art, are in some cases the direct work of the artist. Therefore in addition to determing the emotion, some might think the author is also responsible for determining the aptness of the emotion expressed towards the fictional object. As such, the author is directly responsible not only for the emotive affect of their work, but what are morally apt evaluations directed at the object. We might think however, that there are *two* grounds for emotional aptness in relation to art, aesthetic and ethical.^[E.g., see @gilm20, 204]

Many theorists would argue that any extra-aesthetic evaluations are inappropriate for works of art. If what we feel is the work of the artist, then in the context of appreciating art, we do not deserve moral praise or condemnation for our emotional experiences. If this follows, then it is hard to see what is moral about art. However, it is not clear to me that the emotion we feel is always the one intended by the artist. There are other reasons why we could feel a given emotion upon hearing a song. We might remember our mother singing it to us at night before bed, or it playing in restaurant where we first when on a date with our spouse. This means that what we feel emotionally, does involve us. Not everyone will be drawn into the feelings of revenge asked of us in the *John Wick* sagas, with some audience members recognizing the movie is asking for and abstaining from viewing it. The puzzle that we need to solve then, is what internally motivates an audience to adopt those emotions that an artist calls for. Given this, we might think that whatever emotions are there, are possible emotions.

There are many kinds of objects that an artist may attempt to represent in their artwork. We can begin by asking 'how do audiences *identify the contents of author's fictive utterances*'.^[See @stoc17; @abel22] In order to fully appreciate the connection between the fictive utterances in a given artwork, we must understand the centrality of the imagination and its relationship to fictive utterances. What is the object being represented and more specifically, how is it being represented? There are objects embedded in a piece of art. This object is causally related to the emotion that we feel. Here there are some important points to note however. In fiction, it is not always the case that the emotion we experience is synonymous with the emotion we would have had in similar contexts outside the fiction, say in the real world. As such, the fiction defines, or is only casually related to the emotion we will end up having.

```{=latex}
\begin{figure}
\centering
 \begin{tikzpicture}[
    every node/.append style={circle, draw, minimum height=0cm}]
    \node[label=below:w0] (w0) at (0,0) {Actual World};
    \node[label=below:w1] (w1) at (2,-2) {Possible World};
\end{tikzpicture}
\caption{Casual Relation}
\label{fig:casual}
\end{figure}

```

One way to understand this question, is to consider that for a given fictional utterance, what it infers is that for a given world $w_0$, there has been an utterance that references an alternative world $w_1$.


```{=latex}
\begin{figure}
\centering
 \begin{tikzpicture}[
    every node/.append style={circle, draw, minimum height=0.6cm}]
    \node[label=below:w0] (w0) at (0,0) {Actual World};
    \node[label=below:w1] (w1) at (2,-2) {Possible World};
    \path[->]
        (w0) edge (w1);
\end{tikzpicture}
\caption{Utterance that References an Alternative World}
\label{fig:utterance}
\end{figure}

```

At alternative $w_1$, given the speech act, there is some object which is referenced. With fiction, the imagination plays a determining factor in portraying that represented object. The question then becomes, is it the imagination of the creator of the fiction, or the audience? When it comes to moral content in fiction, identifying the object becomes important, what role does the audience perform in determining some content of fiction?

In "Only Imagine", Katheleen @stoc17 argues the content of fiction is determined by what the artist reflexively intends the audience to imagine. Here, not only does the artist imagine what is becoming prescribed, but also the audience recognizes what the artist intends for them to imagine. Conversely, Catherine @abel22 defines intentionalism as a premise which states that an "actual artist's intentions determine the content of their fictive utterances" [3]. Abell argues that fictive utterances are grounded in fiction institutions where an institution is comprised of a set of social practices and rules [@gual16; but also E.g., for fiction as an institution see @walt90; @lama90.]. The rules of fiction institutions enable members of a set of rules to coordinate their communicative practices, etc. Regarding fiction, such coordination is necessary in order to communicate imaginings.

We can imagine having two agents wherein one agent modifies the physical environment of the other. In communicating imaginings, discussants each desire that the other be capable of imagining specific contents prescribed by one of the discussants [@abel22, 30]. Following a set of rules allow the discussants to imagine what the other desires them to do so.

> Such rules guide agents' actions, and enable them to coordinate on equilibrium solutions to the coordination problem of identifying a medium of exchange, store of value, and unit of accounting. [@gual16a, 35]

Having the prescribed emotion represents our correct understanding of that fictional utterance. There is an important implication of intentionalism in regards to the philosophy of fiction. The emotions that we experience in response to fiction, unlike those we experience in response to the real world, are not necessarily apt just in case they accord with some moral norm. Rather, an emotional response to fiction is apt if it is the one prescribed by the fiction according to the artist’s intentions. The creator of the work makes a fictional utterance to the audience. The fictional utterance is grounded by an artist's intention. Recognizing her audience, the author conforms to the rules and standards of a given community in order to represent an object of emotion to that community.

Here, we may think that the moral activity in the novel is dependent on the author, it rests on the author's intentions. However, the author plays no role in determining who belongs to a given community. She does not determine what objects illicit which emotions in a given community. Although a community can form around a piece of art, the role the artist plays in determining that community is not clear.[Look up artistic communities]

A similar position is defended by Jonathan @gilm20. Under this view, the emotional responses that we have in response to fictional objects, are dependent on the creator of that fiction. The dominant view in the epistemology of fiction is *intentionalist* in that "the fact that we are merely *caused* to feel a given way may be reason to feel that way" [@gilm20, 132]. For Gilmore, a primary point in favor of the intentionalist view is rooted in a related one. First, how we respond to events represented in art, does not infer how we should or may respond to similar events in the real world. Gilmore then draws a distinction between what is normative, and what is prescriptive regarding our emotional responses to art. One important point here is that what it would be epistemically rational for us to imagine in fictional contexts, is not necessarily applicable in non-fiction.

A known view in psychology of emotions and moral psychology then, argues that emotions are evaluative representative states of things in the real world [E.g., see Jonathan @gilm20; @arno60a; @smit93; @laza84; @sche01; @smit84, to name a few.]. If this is true, then we may ask an analogous question, whether emotional responses are also evaluative representative states to fiction as well. Here, Gilmore notes that the evaluation can be apt in either a narrow scope or a broad one.^[@gilm20, 221] When the creator of a fiction makes a fictional utterance, that utterance is often intended to cause an emotional response in us. That emotional response is a kind of evaluation. In a narrow sense, a given emotion is fitting, for instance when one engages with an immoral work, then one's emotions ought to conform with a successful representation of its contents. Under the broad scope however, one's emotions ought, if one engages with an immoral work, conform with how its contents are successfully represented.^[@gilm20, 221]

What makes an emotion an apt response to fiction then, is the artist's prescription of that particular emotion via their artwork. Such an emotional state is the appropriate state to have in the fictional context because imagination here plays a functional role. The functional role that imagination here is performing, is to enable an audience to engage with a creative fiction, a fiction which that audience choose to engage with. The creator here seems to anticipate the ability of the audience to invoke the cognitive capacities, e.g. imagination, important for interpreting fictional utterances. In order to perform the task to which it has been assigned, engage with a given fiction, a prescribed emotion is required. Following this then, we *should* express sympathetic anger when *Rage Against the Machine's* Zack Delarocha pleads for justice assuming that such an emotion is the one prescribed in the context of his plea:

<p>Weapons, not food, not homes, not shoes</p>
<p>Not need, just feed the war, cannibal animal</p>
<p>I walk the corner to the rubble, that used to be a library</p>
<p>Line up to the mind cemetery now</p>
<p>What we don't know keeps the contracts alive and movin'</p>
<p>They don't gotta burn the books, they just remove 'em</p>
<p>While arms warehouses fill as quick as the cells</p>
<p>Rally 'round the family, pockets full of shells</p>

\noindent Perhaps it is not a far cry to argue that Rage prescribes prescribes rage, perhaps anger, in their lyrics given the title they've chosen to give themselves [See, @gree15]. Further, throughout the years, the band has also heavily criticized various factions of the United States government [E.g., see @guan]. They have also criticized other governments they believe have fallen short of moral standards they believe to be normative of institutions that have broad influence, coercive and otherwise.

Assuming that a particular emotion is prescribed by the fiction according to the intentions of the artist, the experience of the emotion by the audience represents their correct and apt engagement with the work. Similarly then, we *should* feel sadness when Jay Farrar poetically recounts the historic flooding of Ste. Genevieve MO in Son Volt's *Tear Stained Eye* assuming that this emotion too, is the one prescribed to us:

<p>Seeing traces of the scars that came before</p>
<p>Hitting the pavement still asking for more</p>
<p>When the hours don't move along</p>
<p>Worn out wood and familiar songs</p>
<p>To hear your voice is not enoug</p>
<p>It's more than a shame</p>

But one might think that the emotions we have towards fiction are different in kind from those that we have towards objects in the real world. First, all conscious mental states, according to Gilmore, are intentional states [@tye95, 93--100]. The state represents an object with which that state is directed at.^["Consider the case of tree rings. Intuitively, the number of rings on a cross section of a tree trunk represents something about the tree, namely, how old it is," @tye95, 100.]

Emotions are mental states that represent objects out in the world to us. My fear of a snarling pit bull dog aptly appraises the dog as dangerous [@gilm20, 45]. But *irrational* would be a more accurate description of my fear of chihuahuas.^[For instance see: @fing20; @klau01. For the relationship between ethics and emotional states, see @darw92; @ross19; and @darm00. For the relationship between general evaluations and emotion, see @will21. Moral evaluation and emotion see: @mull17; @sche01; @rose90,emotional and motivational causation: @arno71.] Therefore some moralist stances place strong value on our emotions [See @darw00]. Our emotions constitute appraisals of objects. If it turns out that our emotive appraisal is inaccurate, either we are judging the wrong object, or our judgment is in itself inaccurate. There may be disagreements raised then, when the fictions we consume prescribe amoral emotions, when they evoke emotions that would not be apt in a non-fictive utterance. We laugh at bank robberies when portrayed in some movies though such a response may be inappropriate in real life. On the basis that emotions are evaluative representations of objects out in the world, a question about accuracy begins to emerge. We might think that a mirthful response to a tragedy is not morally justified for instance.

## Fictions and Emotions

### On Emotion {-}

As we've seen, while it would be epistemically irrational for us to imagine harming others for making an inappropriate comment, this in itself does not entail that it would be epistemically irrational for us to imagine doing so in the context of appreciating the lyrics of a dance song. Following this then, the evaluative norms that govern our emotional responses in the real world, do not govern the emotional responses in fiction. It is important here however, to note that while many moral theories concern the rationality of a given moral action, there are others that do not concern the rationality, but rather, the non-cognitive areas of the mind. The emotion one experiences forms their moral beliefs and values and as such, moral cognition is not cognitive at all.

Unlike traditional moral testimony, art motivates/suggests/represents a given effect in a given context. We can call these evaluative emotions where our emotions are either expressions of our moral judgments, or they motivate our moral judgments.^[Some affective accounts include @gilm20, 44--84; @prin04, 52--78; @prin07. Also see @des15.] According to the evaluative theory then, our emotions embody evaluation of an object. The loss of a romantic relationship might produce sadness if in the loss of relationship, the subject feels something valuable has been lost [@sche01] or being chided by one's partner can produce anger [@rose84, 14].^[@arno84; collecting 200 written accounts of emotional experiences, argues that emotions are relative to a motivation arising out of a desirable state (stimulus event) that a person wants, e.g. being praised, or an undesirable state the person does not want, being criticized by one's partner.] A consequence of this view is that two individuals may have differing emotions to the same event. According to this *cognitive* approach, differing perceptions of a similar event are responsible for the discrepant emotional experiences.^[William @jame84, 191 for instance argued that emotions are correspondants to processes "occuring in the motor and sensory centers", namely "bodily changes characteristic of emotions [which] 'follow directly the *perception* of the exciting fact'." However, James equates the emotion with the bodily response. This approach has been criticized on the basis that bodily response is too slow and undifferentiated to explain discrete emotions [@cann27]. It should be noted, that following James, Prinz defends the view that emotions are feelings given 1) emotions co-occur with 'bodily changes'', changes in the body are sufficient to induce emotions, and reduction in bodily "response reduces emotional experience" [@prin05].]

Evaluative emotions can be type identified by the evaluative properties they attribute to their objects [@gilm20, 45--46]. A worry arises when we consider our affective responses to fictions that would be considered inappropriate in similar real-world contexts. Is our affective response to these fictions indicative of our moral judgments in similar real-world engagements which these fictions are modeled after? For instance, @curr20 argues that emotions contribute to our understanding of a fiction by being the right emotion and getting things right in the context of that fiction. @gilm20 argues that this results from a general capacity for practical rationality that allows us to “richly imagine and emotionally evaluate various courses of potential action” [100].^[Similarly @des15 argues that fictions are similar to philosophical thought experiences but that they enable a richer engagement with the contexts by allowing us to experience potential emotions in a way we’re prevented from with philosophical thought experiences.] Emotions represent their objects as being a certain way, in the real world but can also be used imaginatively.

One way to understand and answer this question, involves recognizing and defining the criteria for appropriate emotional engagements across real-world and fictional world scenarios. Those who defend continuity argue that these criteria are identical: what is an appropriate emotional engagement to a fictional scenario is also appropriate in the real-world and vice versa. @gilm20, 131--132 defends discontinuity, namely that the kinds of reasons that we countenance as justifying or challenging our emotions depend on the functions for which our emotions are being elicited. As a result, what is appropriate in fiction and in real life might differ.

What does it say then of someone when they laugh at an inappropriate joke represented in a fiction, film, song lyrics, etc? There are two sides. Continuitists on the one hand think that given our emotional engagements with fictions are modeled after our emotional engagements with real-world states of affairs; we might think that this emotion is justified if and only if the emotion would be a justified response to an analogous object^[For instance, @gilm20, 1, 102] (the inappropriate joke) in the real world. The question then is whether we *can* represent morally expressive emotions in fictions given this particular discontinuity. @nuss86; @nuss90; @nuss01a; @stum10; and @zagz17 suggest that such representations are necessarily complex depictions of a relationship between two or more individuals, wherein a morally significant emotion is experienced by one or more parties. Therefore although it is plausible, it is not necessarily the case that emotional responses are continuious between fiction and the real world because the intention of individuals such as Henry James specifically is to create such moral complexities as a way of mirroring real life. As such, we might think it warranted that an emotional response to such works will mirror an emotional response in similar contexts in the real world but this says nothing about the intentions of every artist.

The above view would neglect other reasons which would justify an affective response to a work of art. According to the current approach, fiction and other imagination directed emotions are oriented towards other ends---pleasure, entertainment, and absorption---that are justified for different reasons [@gilm20, 132]. @curr20 argues emotions are not continuous because the objects in fictions are not real [62]. While it may be true that the Prosecutor Garrison in *JFK* was a prosecutor in real life, the Prosecutor Garrison as *represented* in *JFK* as "devoted to the truth" is not a real person. Perhaps Oliver Stone's intentions here are to elicit our admiration towards of Garrison whereas in real life we may have been hard-pressed to do so.

> For the rational norms governing beliefs do not speak directly to their contents in isolation, but rather to the reasons in favor of their formation or retirement, and to their relations---such as their consistency---while they are held. [@gilm20, 152]

One particular reason why this is important, has to do with moral education, motivation and the like.^[Maybe we can imagine a community that as a rule does not treat art as containing significant, or any at all, moral motivation. As such, art in such a community just is treated and evaluated for its purely aesthetic, or entertainment, or absorptive qualities.] How do we learn compassionate or empathic behaviors? Some continuitists argue, for instance, that narratives can uncover the good qualities of an individual better than analytic philosophical distinctions. They think that those qualities which make good characters good, e.g. underlying thoughts and motivations, and features about them that make us want to be better, can only be uncovered through fictional and non-fictional narrative [@stum10, 36, 40--42; @zagz17, 18; @zagz17, 170].^["Putting things this way allows us to see how the emotions can be genuine and not simply playacting, and also how they can have the cognitive content of the real-life emotion" @nuss01a, 245.] Upon this, we ourselves then become motivated to act in ways which gave rise to these positive affective states in us.

It is not the response that is unjustified, but rather the decision to engage with that work of fiction if our ends do not cohere with those of the artist.

What we are looking for here I think, are not only constraints that are imposed on what we imagine and how we imagine it, such as would justify laughing at an inappropriate joke, but constraints which would justify creating or consuming such content. Discontinuity as articulated above threatens our ability to say anything other than: if you don't like it don't watch it.

I articulate an approach to this problem. I suggest that the objects which the continuitists and the discontinuitists are concerned with, differ in kind. As such, the point of reference each identifies as the objects of concern in fiction, are not the same. Lastly I argue that the difference is not the content *per se*, but the character of the individual which is expressed through their intention to create.

However, there is a worry about whether entertainment can ever adequately justify all emotional responses in this way. We have emotional responses to things that don't exist. (Fielding 1750/1999, 611--613). First, we may think that our emotions are evaluative analogously to our beliefs. The question that remains is how should we characterize these emotions as opposed to other ones (For instance see Radford 1975). For instance, Nussbaum defends a cognitive view where our emotions are appraisals or value judgments, which ascribe to things and persons "outside the person’s own control" great importance for that person’s own flourishing [@nuss01, 4].^[For other cognitivist theories, see; @solo03; @lyon80; @kenn03; @gord90; @laza84; @laza91.] Here, our emotions are "intelligent responses to the perception of value," and "they are suffused with intelligence and discernment" [@nuss01, 2]. Our emotions here are *about* something, they constitute a special relationship between moral properties and emotion [e.g. @prin13, 14]. Gilmore adopts the *intentionalist* view in the epistemology of fiction. His intentionalist view is grounded in a dominant view in cognitive theory of imagination where the functional roles of imagination is a determining factor in understanding the contents of fictive utterances.^[Also see Catherine @abel22 and Chalmers 2002]

#### Cognitive Judgments {-}

According to cognitivists, to have an emotion involves "some kind of cognitive judgment" [See @nuss01; and @darw92, 148]. Because emotions shape the landscape of our mental and social lives, a theoretical account of emotions will have large consequences for theories of practical reason, normative ethics, the relationship between ethics and aesthetics, and political thought. In other words, understanding the relationship between emotions and various conceptions of the human good will inform our deliberations as we ask how politics might support human flourishing.^[@nuss01, page num]

Our emotions in response to fiction might also shape our mental and social lives. However Gilmore denies the above arguing that our emotions as directed at fictions, and those we have directed towards the real world, are asymmetric principally because they have a different direction of fit than, say, belief. For instance, we might ask when our emotions constitute such evaluations. Many creatures that are capable of emotions, including babies experience emotion without possessing the concepts which the cognitivist associates with them.

Moral properties can be related to emotion in a number of ways. There might be an essential relation where there is something like a human faculty capable of contributing to our ability to perceive moral qualities. John McDowell and David Wiggins have defended such views that have "drawn inspiration from the idea that normative or evaluative judgments might bear some analogy with judgments of secondary qualities, or other judgments essentially tied to the exercise of certain human sensibilities" [@darw92, 152].^[Also see @mcdo85; @mcdo88; @wigg76] Notice however that this is different from saying that emotions are related to moral *concepts*.^[See @prin07, 16] On this view, to suggest that there is a relation between our emotions and moral properties is to state a thesis about "our capacity to grasp moral properties in a standard way" [@prin07, 16].

Here, moral judgments are saturated with sentiment. Our moral judgments concern concepts that we care deeply about. Otherwise known as values, these concepts evoke our passions in ways that for instance, are not evoked in relation to whether Honda or Toyota sold more SUVs in a given year. Nussbaum then, defends a theory of emotion wherein emotions are a kind of judgment and in this way, our negative emotion upon witnessing the flooding of Saint Genevieve, say you find us weeping, is a judgment that this particular flood---perhaps not unlike all floods---is bad which says something about what we value as individuals.^[See @nuss01, 17] But this does not necessarily mean that our emotional states are dependent on our cognitive states.

But it isn't necessary that our emotions do correspond with our cognitive judgments [@des15, find page]. First, humans have a unique ability to anticipate future events, foreseeing possible outcomes, remember autobiographical events, simulate the future, conceive the viewpoints of others and imagine hypothetical scenarios [Gilbert and Wilson 2009; Buckner and Carroll 2007; also @des15, 2].

It is cognitive abilities such as counterfactual thinking, envisioning the near and distant future, imagining hitherto unfamiliar scenarios which afford us the ability to be "transported" into a fiction [Richard Gerrig 1993; @des15, 4]. Here, an audience is drawn into and fully immersed within a fictional world. The audience is able to set aside their own cognitive judgments usually accompanying their emotional experiences.

So one aspect of the current concern is that lyrics by groups such as rage against the machine or KRS One are really just entertainment and nothing more. That there is nothing by way of moral knowledge, for instance, that could be derived from them. On this view, art is amoral and accordingly, our emotional responses to art also, are amoral, devoid of any moral worth.^[A theory of evaluative emotions has roots in *representative appraisal theories* which include @arno60a; @smit93; @smit85; @sche01; @smit84. I have not yet said much about the relation between our evaluative emotions and fiction, though I will devote considerable space to this further down.] As such, our efforts at appreciating the moral arguments made in the art of Rage Against the Machine for instance, is undermined.

However there can be two functions related to this ability. On the one hand, such abilities enable us to better understand implications of a potential action, or what might have happened on the basis of some antecedent event [@byrn02]. Similarly, our emotions are another type of representation for antecedent events. How would I, or would have felt were *Red* a song about my previous or future relationship instead of Taylor Swift's? Here, fictions are another, more robust form of philosophical thought experience.

This is important because some prominent sentimentalist accounts^[There are two varying sentimentalist views under consideration here. There is what I will call the traditional sentimentalist view defended by Michael Slote @slot10; @slot07. Also see @gelf19 and @gelf04 among others Some especially prominent defenses of the traditional view include Francis Hutcheson; David Hume; Earl of Shaftesbury. For more recent sentimentalist views, see @darw92; @mcdo85; @wigg87. Then there is the version I will build from the above quote by Martha Nussbaum above. I will explain this further on.] have argued that for a work of art to engage sufficiently with moral issues, what is needed is a similarly complex, or refined literary engagement. But they might suspect then, that *Tear Stained Eye* is not meant to evoke the emotional state apt for such an event as the 1993 Ste. Genevieve flood. Perhaps it is not necessarily the case that our moral emotions are justified in the same way as they would be were we to witness Saint Genevieve's flooding in person because fiction has more complex aims than this only. Upon witnessing the 1994 flooding of Saint Genevieve, we might appreciate the gravity of the situation responding with emotion that expresses our recognition of the damage which occurs as a result. We may feel distress, compassion, fear, etc. But this does not necessarily suggest that popular songs can be complex in the way needed to evoke the right sorts of moral judgments.

#### Same Emotion {-}

When speaking about emotions, the emotions that are elicited by fictions are the same as those elicited by actual events. But on one hand we should think that if our emotions are expressions of what we find value in, then why do we not experience those emotions that express our value judgments in fictional[b] contexts which are analogous to those we experience in the real world?

[Explain emotion and cognitive judgment, for instance emotion as a cognitive judgment cannot explain emotions in babies or animals, then explain why, despite the empirical research, why Gilmore thinks they are asymmetric; emotion as sense perception; emotion and quasi emotion, according to dominant theories in neuroscience, our emotions reflecting objects in the real world, are brought about by the same cognitive functions as the emotions we have in response to fiction]

This does not specifically state what direction the relation runs in. On one hand, it may be that to say *flooding is bad* is to state a value judgment wherein we give a negative evaluation of the state of affairs in which Saint Genevieve is flooded. It would be odd for someone to laugh while looking at images of a family sitting on the rooftop of their flooded home. However, there is a question that though *Saint Genevieve flooding is bad* is true, that it is only true in virtue of our own judgment and values, a response not necessarily apt towards fiction. While I might perceive a news report of Saint Genevieve flooding as negatively valenced, it is not necessary to perceive a fictional report of the same nature similarly. Another option is to say that in stating flooding is bad, we are merely expressing our emotion regarding our perception of actual floods but not necessarily fictional ones.

If our emotional responses contain value and importance in the same way that our other perceptual responses might, then they are necessary for accounts of ethical judgment. But this presents a problem because I might perceive the flooding of Saint Genevieve as bad, but I might perceive the account of the flooding as expressed through Son Volt's "Tear Stained Eye" as something other than bad. As such, while I may perceive actual accounts of flooding as bad, it is also possible that I perceive narrated accounts of flooding as something other than bad.

As noted here; emotions are often thought of as complex in regards to human cognition. When considering the relationship between our emotions and our beliefs, it is not often clear that first, there is not such a relationship, but at the same time, it is not clear what this relationship would be if there were such a thing. Perhaps we should view emotions as part and parcel of the system of ethical reasoning. The alternative is viewing morality as a system of principles to be grasped by the detached intellect. Accordingly, emotions would be motivations that either support or subvert our choice to act according to principle. While perceiving accounts of actual flooding, I may reach for and grab sandbags, warn others, call for help etc, when perceiving narrated accounts of flooding, I may instead reflect back on what it must have been like to live through such flooding.

A standard inference of the view, and perhaps this is an answer to the above question, requires only that we think of the complexity or subtlety afforded to fiction as represented in high art. Here, emotions are a "prominent part of the subject matter of moral philosophy and developing an adequate ethical theory will be to develop an adequate theory of the emotions. Though a big cultural source of emotion is music, typically only high art, including music, is discussed as having a strong relationship between a song and the moral emotions that it expresses. If we think that a reason for this emerges from the insistence of the artist to express such moral emotion, imparting intention into moral kind fiction, then perhaps this is a view defended by Jonathan @gilm20. On it, we are justified in imagining that some moral judgment is fictionally true just in case our reasons for imagining such is in favor of their formation.^[It is not the case that "a defender of continuity might say: if it's true in the fiction that, e.g., FAgin is morally corrupt, the beautiful person is intelligent and honest, the mobster's ends are merited . . . then that justifies imagining such things as true" but rather "the rational norms governing beliefs do not speak directly to their contents in isolation, but rather to the reasons in favor of their formation or retirement, and to their relations---such as their consistency---while they are held" [@gilm20, 151--152]. I will look at the continuity/discontinuity distinction further below.] For instance, watching *American History X* requires that we take on the emotional perspective of a impoverished but violent neo-Nazi and his impressionable younger sibling in order to understand the redemption he experienced by both at the end of the movie.

The worry that emerges is that though moral justification then becomes unavailable, only in response to low art does it do so. But this also undermines arguments which attempt to make a connection between low art and moral *unknowledge*.^[Later I will discuss the term *unknowledge* following @mcgr19, 172---191, in greater detail in the next chapter.] Emotional aptness is only a question involving high fiction but not low fiction, including those found in popular country and rap songs, television shows, and children's books, for example. Accordingly then, it may be argued that such objects are devoid of moral worth. This would mean then that arguments regarding injustice as found in the popular song "Wake Up"^[For more on the social significance inherent in RATM's lyrics, see @gree15.]:

<p>Fist in the air in the land of hypocrisy</p>
<p>Movements come and movements go</p>
<p>Leaders speak, movements cease when their heads are flown</p>
<p>'Cause all these punks got bullets in their heads</p>
<p>Departments of police, (What!) the judges (What!), the feds</p>
<p>Networks at work, keeping people calm</p>
<p>You know they went after King when he spoke out on Vietnam</p>
<p>He turned the power to the have-nots</p>
<p>And then came the shot</p>

\noindent *are* mere entertainment and devoid of moral worth.^[This conclusion is not universally accepted. For instance see; @camp94a; @craw00; @gree15.]

Therefore, in the remainder of this chapter and the next, a primary focus will consist of the relationship between popular fiction and moral knowledge. Rejecting the common rationalist charge in twentieth century philosophy, I will first defend a view about the relationship between our emotions and our cognitive states, in regards to moral judgment. I will not only be assuming such a connection, but I will also defend such. The next part will be a focus on the importance of fiction in such a relationship.

### Fictions and Imaginations {-}

While we might think that the intentions of the art provide a sort of restraint on our imaginings in fiction, fictions also employ various constraints. For instance, what we imagine and how we imagine it when we adopt a particular mental attitude, such as belief, towards what we hold to be true in a story and what we determine to be true in a story depends on the internal and external sources of truth that we recognize as relevant to that story. Gilmore argues that it is not only the intentions of the artist that provide constraints on what is imagined, but that the artist uses internal and external sources to constrain our imaginings.

In order to understand what makes an emotion apt in regards to fiction, depends in part on the answer to the question about imaginings constraints in fiction. What's important here is that we have emotional responses to things that don't exist [For instance see @fiel99, 611--613] How should we characterize these emotions [See Radford 1975]? One way to do so is by trying to understand the functional roles of the emotional states involved [Chalmers 2002].^[Imagining and conceiving 2 different things (Peacocke 1985). No univocal explanatory concept (Amy Kind 2013)]

An emotionally apt response to fiction requires that the audience's emotional response is the one called for by the artist.^[@gilm20; 102--133] This is because imaginings can be "type-identified" by their functional roles. The appearance of an object can be a consequence of how I choose to represent that object to myself. The factors such as context become important in cases of imagining, but these factors are largely important by choice. But what follows then, is that the aptness of my emotions evoked by Rage Against the Machine would be appropriate assuming that the agent's anger is the response intended by the agent and assuming that we want to engage with the work as the artist intends. When we respond emotionally to the fate of characters in fictional narratives, we allow ourselves to be "carried along" emotionally by the story, and we seem to do this more than we would if the narrative were not a work of fiction [@gold03, 60].

There are various views as to how to identify imaginings. On one view, imaginings, like other mental states such as belief, can be *type-identified* "in virtue of their functional role" [@gilm20, 170].^[Also see @walt90; @lesl87; @gord86; @gold92; @harr00a; @curr02f; @nich00.] However, it is not clear specifically what is the functionalist relation between a cognitive theory of imagination and a functionalist theory of mental states. A functionalist is concerned with what mental states are, not how they account for behavior.^[For instance see @bloc80a] On this account, a *particular pain* is a physical state or event [@bloc80a, 28]. However, Gilmore argues that one way to characterize mental states is by "collecting ordinary folk-psychological observations" about how a mental state is causally connected to various causes. For instance how might a particular mental state be connected to a particular belief, a desire or a perception [@gilm20, 18]. If the functionalist is concerned with what a mental state is, and not how it accounts for behavior, then one way to understand what it is, is in terms of its causal relationship to "sensory stimulations, behavioral outputs, and other mental states" [E.g. @bloc80a, 28; and @gilm20, 19]. As such, Gilmore argues that there is a set of three standard distinctions important for individuating imaginings from other mental states: i) imaginings are constrained by the will, ii) beliefs, perceptions, and other mental states are "subject to a constitutive norm of aiming at what is true" [@gilm20, 19]. iii) imaginings are context-dependent, meaning they depend on a particular circumstance that motivates the imagining. As such:

> the content of a narrative is not just the set of propositions we are solicited to imagine as true when engaging with the work. Rather, that content is constituted by both the facts within a fictional world that are communicated *and* the modes of presentation through which those facts are conveyed. [@gilm20, 42]

Therefore it is not necessary that imagination necessarily aim at what is true. Unlike beliefs, imaginings are typically determined by the willing individual. For instance, it is possible that the appearance of an object is a consequence of how I choose to represent that object to myself. When reading a novel, I may choose to represent myself, or perceive, the protagonist as honest or trustworthy. One way this occurs is that the imagining depends on the particular circumstances that motivate the imagining, say I am reading a story where it is required to perceive the protagonist as such in order to understand what is happening in the story. It possible to think of the movie *American History X* as an example of this. At the start of the movie, the audience is made to feel the motivations underlying Edward Norton's character. The death of his father, the feeling that others are immune to moral condemnation while those like himself are unable to escape it.

But if imaginings do not aim at what is true, then it seems that there is a potential worry questioning when an imagining aims at some object. According to the current view, the worry is that imaginings then aim at what is prescribed to be true in a given context. Imaginings then, unlike beliefs and other mental states not only are constitutive of the will, but they are also context-dependent and it is not clear whether these constraints are always co-extensive.

We cannot reduce all instances of imagining in this way. Sometimes imaginings can be indistinguishable from other mental states like belief. There may be no behavioral difference for instance, between my imagining that others owe me rent or the belief that according to the rules of the game monopoly, a certain player owes me a point value that is demonstrated by a fake monetary value.

We can appeal to external vs internal perspectives. I might mourn what happens to Anna Karenina but express indifference when reading a news report on an otherwise analogous real-life event. As Matthew @kier03 points out, we can imagine a former Roman Catholic now atheist reading reading Emily Waugh's *Brideshead Revisited*. Given her secular conversion, she will deny that morality categorically depends on the commands issued by God. However, she might still respond to the narrative with sympathy, admiration, and awe. In effect, adopting the perspective and external view of the author [Also see @gold03, 60].

### First thoughts on fiction, imagination and learning and Why does it matter? {-}

Nussbaum explains that narrative works include perceptual and expressional terms that seek to represent our own moral frameworks in the real world. Moral knowledge for Nussbaum, is an agent’s ability to perceive a “complex concrete reality in a highly lucid and richly responsive way; it is taking in what *is there* with imagination and feeling” [@nuss85, 521. Emphasis is my own.]

The function of narrative then according to Nussbaum, is practical in that it emphasizes “the human importance of a fine-tuned responsiveness to complex particular cases and of a willingness to see them as particular and irreducible to general rules” [@nuss90, 290]. This function is evident in narratives which have a complex narrative structure, one which evokes in the reader associated moral activities. These moral activities include human emotional responses associated with moral worth. For an artist to recreate a perception as Nussbaum understands it, then means that “the artists are not free to create simply anything they like. Their obligation is to render reality, precisely and faithfully; in this task they are very much assisted by general principles and by the habits and attachments that are their internalization” [@nuss90, 524]. As such, here we only have that an artist must remain faithful to normative moral obligations.

However, Gilmore argues that those norms governing our emotional engagements with moral features in the real world are discontinuous with our emotional engagements in fiction. While we might expect a certain set of emotions in response to a given stimulus, in the domain of fiction, our emotional responses are under a different set of criteria. Our emotions are not under the same normative constraints that they are under in the real world.

Some might argue that this is because those objects which act as stimuli in fictions, are not real  objects. But, Gilmore's defense denies this. Fiction-directed affective states are real (preserves realism), their fit with their objects is governed by a different set of norms [9].^[On Quasi-emotions, @walt90; @curr02. Defenses of Continuity: “The second kind of opponent, more broadly represented among Anglo-American philosophers of art, assumes or defends the correctness of continuity or invariance: the criteria governing the correctness, fittingness, or aptness are the same whether those token mental states are elicited within the context of imagined experiences or genuine engagements with the actual world” [9].^[E.g., @des87; @feag96; @wils86; @gold00; @robi05; @matr03; and @mesk04.] As such, descriptive defenses merely distinguish between descriptive and normative continuity. Further, research only supports descriptive accounts, not normative and therefore: “The functions of our engagements with fictions and other objects of the imagination license a departure in those engagements from real-world affective norms” [10]. As such the following assumptions are not grounded by current views:

::: {.unnumbered}
1. The idea that a person’s emotional response to fiction is an unmediated reflection of his or her character and genuine desires
2. The thought that stories evoke a reader’s responses by giving her reasons for them that would apply in the real world
3. The claim that we can learn from a fiction when it provides a simulation of states of affairs that we might encounter in actual experience
4. The methodological assumption employed in a wide range of psychological research that scientists can study the nature of emotions by exposing test subjects to acknowledged fictional representations (e.g., short films) in which those emotions are elicited.
:::

## Discontinuous Fictional Objects

Rather than considering the aptness or un-aptness of our emotional responses to fiction, it will be important to consider what the objects of such responses are.^[We might think of such objects in the way sensibility theorists do, i.e. @prin07, esp. 88-89, evoking a @lock90'ian sensibility. Here, moral properties are like secondary qualities similar to color, etc. Other similar views include Thomas Reid.] One way to do this, is to evoke standard practices involved in gathering evidence which supports beliefs we hold. In addition to inferences we might make, testimony received by us, perception etc, we also rely on our affective responses to relay important information about our environments to us.^[Micheal @tye95 defends a strong version of this view: "It seems to me not implausible to deal with these cases by arguing that insofar as there is any phenomenal or immediately experienced felt quality to the above states, this is due to their being accompanied by sensations or images or feelings that are the real bearers of the phenomenal character. Take away the feelings and experiences that happen to be associated with the above states in particular cases, and there is no phenomenal consciousness left."] Not only do such affective states merely give us information about the world, but it is plausible that this information comes shrouded in the mysteries of approbation or its negation. I might decline going down a dark alley owing to the apprehension I feel about doing so in the real-world.^[@zagz17; especially 129--154, is one such account whereby we rely on our feelings of admiration to identify which individuals we should want to be like, emulate etc. Such individuals are direct references for moral kind terms where we identify thick concepts such as good, kind etc, via reference to such individuals. Some concerns which may arise with Zagzebski's view, involves her theory that not every member is capable of identifying proper objects of these terms. In such such cases we rely on experts in the same way we rely on experts to identify gold. For literature regarding asymmetries between moral and non-moral testimony and expertise, see @hopk07a; @hill09c; @enoc14. Seminal representative appraisal theories include @arno60a; @laza84.] However, responses to our affects towards fiction can differ from those towards their real-life counterparts. To be able to address this question, we need to consider the metaphysical question of truth in fiction. Discussions on truth in fiction were inspired by an influential paper by David @lewi78a, and more specifically on his reality principle:

Additionally, it will not do well to talk about fiction without first talking about imagination. Typically, I will walk down a dark alley in a major city between the hours of two and four am and feel fear and apprehension. In some fictions, I may experience similar emotions in similar contexts. But my standard emotional responses in the real world are not always indicative of the ones I would experience in a similar fictional context. In some fictions, I am asked to imagine that I possess extraordinary strength and that I have a thirst for justice. In such cases, I would not experience fear but maybe excitement, an emotion that would not be apt in a similar context in the real world.

> If $p_{1}, . . . p_{n}$ are the propositions whose fictionality a representation generates directly, another proposition, $q$, is fictional in it if, and only if, were it the case that $p_{1}, . . . p_{n}$, it would be the case that $q$.

$$\frac{In f, \psi^{1}, . . ., In f, \psi^{n}}{\therefore In f, \phi}$$

According to it, we consider what is true in a fiction by considering a set of truths in the real-world which *would* entail some conclusion $\phi$ at the real-world.


```{=latex}
\begin{figure}
\centering
 \begin{tikzpicture}[
    every node/.append style={circle, draw, minimum height=0cm}]
    \node[label=below:w0] (w0) at (0,0) {Actual World};
    \node[label=below:w1] (w1) at (2,-2) {Closest Possible World};
\end{tikzpicture}
\caption{Truth in the Real World Entails a Conclusion in Fiction}
\label{fig:truth-fiction}
\end{figure}

```

We then contrast these against the fiction, *Pride and Prejudice* for instance. At $w_{0}$, the actual world, on the assumption that the actual world is Victorian England, \"a young woman *y*,\" runs away with \"a vicious military officer *o*\" prior to marrying. As such, in the real-world as in the fiction, *y's* character is threatened. Therefore there are a number of truths, such as \"running away with *o* threatens *y's* character,\" $\psi^{1-n}$, which hold at $w_{0}$, Victorian England, and at least 1 conclusion, $\phi$ which would hold at $w_{1}$, *Pride and Prejudice*, on the assumption that these truths also hold and entail the truth of $\phi$ at $w_{0}$.

$$\frac{In f, \psi^{1}, . . ., In f, \psi^{n}}{\therefore In f, \phi}$$

\noindent The real-world counterpart is synonymous to

$$\frac{\psi^{1}, . . ., \psi^{n}}{\therefore\phi}$$

\noindent i.e., the real-world where a similar set of facts entail $\phi$ in the real-world as they do in the fiction.

## Imagining Possible Worlds

What the discontinuitists are asking of us, is that we consider additional facts, say $\omega^{1}, . . ., \omega^{n}$ that entail $\phi$ in the fiction although they would not similarly do so in real-life.^[\"There the fiction presents a character or state affairs as having one property and our response to that property causes us to correctly imagine the presence of another property, even though the two properties bear no genuine real-world explanatory connection\" [@gilm20, 151]. Also see @lewi78a.] For instance, a fact such as the artist prescribing mirth rather than the anxiety the audience feels towards the affairs of the military officer and his young lover.

\noindent i.e.,

$$\frac{In f, \psi^{1}, . . ., In f, \psi^{n}}{\therefore In f, \phi} \& \frac{\omega^{1-n} \& \psi^{1-n}}{\therefore\neg\phi}$$

As a mental state, imagination aims at what is true more broadly than other mental states such as belief [E.g., see @gilm20, 18—20].^[For some useful literature on possible worlds and imagination see, @fitt23; @spau16 and @kind16.] First, consider that Imaginings are type identified in virtue of their functional role whereas beliefs by their relationship to their object. If I believe proposition *p*, it will rain tomorrow, I will tend to assert that *p* under appropriate conditions, grab an umbrella before leaving the house; behave in ways appropriate to it being true that *p*; deny what saliently contradicts it; rely on it in inferences; and so on. On the other hand, imagining that *p* is noticeable from believing or desiring that *p*, by typical roles imagining plays in the causal networks connecting sensory inputs, our other kinds of mental representations, and our behavior [@gilm20, 18].

In other words, unlike beliefs, imaginings are not constrained by the object, say the affairs of the military officer and his young lover, but by our will or the function of the imagining. For instance, assuming that it a given imagining is propositional. Beliefs are counter-factually dependent on the object and tend to change involuntarily with changes in the object whereas imaginings can be a consequence of how I choose to represent it to myself. Not constrained by what is true and is context dependent.

Importantly, this is not to say that imagining is wholly dependent on my will, and accordingly, fictions provide constraints on our imaginations in at least 3 ways, and count in our evaluation of an affective response as appropriate in the context:

::: {.unnumbered}
1. Through our identification of a story’s genre.
2. Awareness of the author’s communicative intentions.
3. My ends as a consumer of fiction.
:::

\noindent Therefore while beliefs aim at what is true, imaginings aim at what is true in a fiction in pursuit of these three aims.^[\". . . a defender of continuity might say: if it's true in the fiction that, e.g., Fagin is morally corrupt, the beautiful person is intelligent and honest, the mobster's ends are merited, and so on, then that justifies imagining such things as true. *Whatever* the means might happen to be that such fictional truths are conveyed to us, they are fictional truths and therefore we are justified in imagining them as such\" [@gilm20, 153]. Also see @walt90, 41; and @lewi78a.]

One concern with regard to apt affective responses with which the continuitists are concerned with, is whether having relevant emotions in a given context is constitutive of a good, or well-lived life.^[@nuss86, 343--344 argues concerns of human excellence as understood by Aristotle are questions about human value which are expressed in the mutual activities, feelings, and awareness that characterize loving relationships between individuals. A part of the concern here is whether someone can exemplify such excellences and still be moved to express feelings towards even fictional objects which are intended to represent relational objects.] Is the life of an individual who has apt emotional responses in the right contexts, a universally desirable one? If it is, then the imaginative constraints that the continuitists may focus on here is 3, my ends as a consumer of fiction. The moral answer involves feeling appropriate emotions at opportune moments and my questions are what facilitates these or hinders them. Rather than addressing this question however, it will be more helpful to model a way in which such relationships in literature may be expressed. Such relationships are between:

::: {.unnumbered}
1. Subjects
2. Objects of a subject's affects
:::

\noindent and whether such relations align with my own ends. In other words, rather than considering the object and the ends for which affects are being elicited, the continuitist first considers the aims and pursuits of the perceiver.

Regarding 1, we have a moral character, where I define a moral character as an entity capable of moral perceptions as a response condition to a given context. For instance, see @audi10.^[For some important criticism, see @danc10.]

> We can see a theft, hear a lie, and feel a stabbing. But can we also perceive the moral wrongs these acts may entail?

## World Semantic Antics

According to @audi10^[p. 79] we can perceive morality where Audi defines perception in that some perceived properties of an object causally \"produces or sustains, in the right way, an appropriate phenomenal representation of it\" [@audi10, 84]. Such perceptions are of moral characteristics such as *honesty*, *trustworthiness*, etc.

I argue that in cases of narrative, we can perceive some moral characteristic, $c$, for instance lack of ambition in the husband of Flaubert's *Madame Bovary*. This may be some individual character trait, a personal principle etc. Such traits can be perceived by entities that are capable of moral perception $Pm$, the narrative's characters or its audience.^[\"\'This tone at last was right\': that is, if he had said the same words in a different tone of voice, less controlled, more stricken, less accepting, the whole *rightness* of the act, of his entire pattern of action here, would have been undone\" [@nuss86, 523, emphasis mine].] These I will call moral characters.

Regarding characters, we can typify such by their ability to perceive, via sentiment or emotion, in relation to some context \"lack of ambition in one's partner\" for instance. For the most part, these are human relationships. As such, not only are we concerned with the objects of perception, and the intent of the creator of those objects, but in line with our own purposes for engagement, we also care about the character of the one doing the perceiving, who we want to become.^[@zagz17, 129--155; defends an account of emulation whereby we naturally seek to imitate those we admire. As already mentioned, I am not defending this particular claim but rather I hope to model the relevant considerations of fiction which are central to the debate.] What are *their* aims?

Looking at a narrative of a potential world, say *$w^1$* then, should reveal a context wherein a character $c$ perceives a particular characteristic $Pm$ at *$w^1$*. Understanding the context wherein *cPm* is actuated in the narrative $cPm_{w^{1}}$, means needing to understand the sentiment or emotion of a character expressed as a response condition to some context $P$, say a theft, murder, or betrayal and any moral judgment $m$ which arises in them in response.

Narratives identify such relations and as such, a narrative represents a possible world $w^1$ where $cPm$ at $w^1$. Next, we should also consider our own affects, as moral agents $cPm^{2}$, namely the way I might respond to my response. For instance, looking back at my uncharacteristic calmness while being robbed, I might find my seeming lack of fear surprising. Therefore, there exists some moral context i.e. $\exists w^2$, a world $w^2$ where some entity $c$---you or me for instance---capable of moral perception $Pm$, perceives moral object $m$, $cPm^{2}$ at $w^0$ where the moral object just is $cPm_{w^{1}}$. A consideration of the affects of the character to a moral significant scenario.

We then ask, what does this make me *feel*. In other words, $cPm^{2}$. What is our own reaction upon $cPm_{w^1}$, where $c$ experiences both sentiment via emotion where sentiment equates to either positive $+$\ or negative $-$, i.e. good or bad, and emotion is either $Hm$ or $\neg Hm$, say Happiness or its negation. Here we generalize $( Hm  \lor \neg  Hm)$ to $Sm$; meaning $( Hm \lor \neg Hm ) \rightarrow Sm$. Any expressed emotion, whether negatively or positively valenced, generalizes to $Sm$. For all worlds under interpretation then, i.e. $w^{0+n}$, there exists a world where there exists a person capable of moral perception and moral self-reflection.

$$([cP^{( cPm )_{w^{1}}}] \& Sm)_{w^{2}}$$

In other words;^[They say that a picture is worth a thousand words. These illustrations are merely helpful for conceptualizing possible emotional states in a given context. However, if one wanted to see other modal world illustrations, see @fitt23; and @sain20.]

$$( cPm^{2} \& Sm )_{w^{2}}$$

But what should we do with a fiction that is not blatantly false, but false not only because an author has been forgetful, but because they wish to communicate some additional truth? In other words, why is it not false to say \"Holmes wears a silk top hat\" in the same way that it would be false to say \"Nixon wears a silk top hat\" or that it is false that \"those lyrics should anger me\"?

For instance, Gilmore argues that what determines the appropriateness of an emotional response to a fictional work are the facts that are presented in the work, and the modes of the presentation through which those facts are presented [@gilm20, 42]. Here, our emotions are evaluative appraisals of things both in the real-world and the contents of our imaginations caused by fictions, but in fictions, these evaluations are prescribed.^[@gilm20, 57. For more on evaluative emotions, or emotions as evaluative appraisals, see @nuss01.]

\noindent The answer to this question we might think is that we must first abstract away from the original to several of the possible revisions that remain closest to the original.^[@lewi78a; also see @gilm20, 32; and @walt90, 145.] Gilmore's contribution, is in addition to our abstractions, we also include ours and the author's aims.

While at $w^{1}$ and $w^{2}$ it is the case that

$$\psi^{1-n}\therefore\phi$$

\noindent At $w^{0}$, it might also be the case that

$$\psi^{1-n}\&\omega^{1-n}\therefore\phi$$

\newpage

\noindent Using possible worlds then, $\exists w^{2}$ such that

```{=latex}
\begin{figure}
\centering
\begin{tikzpicture}[
   every node/.append style={circle, draw, minimum height=0.6cm}]
   \node[label=below:w0] (w0) at (0,0) {\huge $( cPm^{2} (\psi)$};
   \node[label=below:w1] (w1) at (0,-4) {\huge $w^{1} (\psi)$};
   \node[label=below:w2] (w2) at (4,-6) {\huge $( cPm^{3} )_{w^{2}} (\psi \& \omega)$};
   \node[label=below:w3] (w3) at (2,-10) {\huge $w^{3} (\psi)$};
   \path[->]
       (w1) edge (w2)
       (w1) edge (w3);
\end{tikzpicture}
\caption{Abstractive Aims}
\label{fig:abstractive-aims}
\end{figure}
```

\noindent *only* potentially accessible to $w^{0}$ such that

$$( cPm^{2} \& Sm^{2} )$$

\noindent In other words; $$( cPm^{2} \& Sm^{2} )_{w^{2}}$$.

The problem I see with this approach, is that the moral worth is in the action of engaging or refraining from engaging with certain art works. However, it is not clear what justifies whether someone engages in a certain work of art or not. In consequence, this does nothing for moving the discussion along. What is missing I think, is that we've ignored the character of the perceiving individual. There are some continuitists who situate moral evaluation in the contexts of caring relationships. What they care about, are the representations of such relationships. Ultimately, we need something in the work that would repel the individual of moral character from the work. There are two types of evaluation, and what repels an audience must be aesthetic. Therefore to explain how the ethical features of a work repels an audience, Gilmore wants to make the moral values synonymous with the aesthetic ones. Therefore, when the function of the work is to realize a morally relevant aim and fails, the failure is aesthetic since it sought to a certain imaginative function but failed. Yet, this does not explain works of art that do not have morally relevant aims, but instead monetary, or entertainment. In the chapters that follow, I address this.

