# Robust and Generic Moral Agency

Philosophers do not often take a serious interest in popular music, let alone country music. The list of those who have includes [@grac16; @prin14; @rigg10; @wilt16; @dyck21a; @malo23]. However, even in this list, country music has typically evaded the serious attention of other philosophers [@malo23; @dyck21a], and remains underrepresented in these discussions. One explanation for this could be that the standard objects of focus for philosophers are concepts like ethics and value. For instance, given a particular value, what behaviors are admirable. Philosophers also ask questions in metaphysics, including ones about the necessary qualities of physical matter and substance, or rather, what qualities must physical matter possess; or free will, are our behaviors really up to us, or some previous causes and foreknowledge, if God is all knowing, then how can our actions be free? Some questions that philosophers ask in relation to music more generally are questions about the ontology of music. For instance, we might ask how can a song sound sad [@triv14] when it is merely the collation of vibrations across a given medium? However, these discussions tend to focus on music that is less popular among the general public. For instance, the general public may debate whether a certain song should be played over the loudspeaker of a primary school, or whether one should let their teenage children attend a rap concert. However, a philosopher of music will be more likely to ask for an account of the features of Marler’s music that make it sad, or debate the frequency at which the material producing the sound vibrates. They might propose that a song is sad rather than diminished, when it is in a minor or diminished key for instance. We can easily imagine that a philosopher says that in order for a song to qualify as being sad, the material producing the sound must be vibrating at a frequency less than 40.20Hz, which at least according to the metaphysician, is more interesting than whether emo promotes teenage depression. They are less likely to question the morality of a song’s lyrical content.

When looking at the more dominant questions in philosophy, they are typically situated in domains such as ethics, metaphysics, epistemology, and sometimes value theory. But in these disciplines, we typically ask questions like “is lying wrong?”, “is a right act right because God commanded it or did God command it because it is right?”, “when is a true belief knowledge?” etc. But in relation to music, it is difficult to ask these kinds of questions in a philosophically interesting way. For instance, during the 1980’s, there was a large public outcry against rap music as immoral and that it undermines social values. For a philosopher to analogously wade into these waters, they would have to say something like “lying is wrong and therefore one shouldn’t sing about it”. But this is odd and cringy. How can hyperbole be wrong in the same sense that lying is wrong and many artists think that what they are doing is something analogous to hyperbole. When thinking about popular songs therefore, it is difficult to provide a sustained critique of one’s values in relation to these and one of the things philosophers care about is value. We do not often think that expressions of value in a popular song are all that appealing, perhaps because it is not clear that the author is authentically expressing a given value. Maybe they are merely providing content devoid of any kind of truth values in pursuit of some additional aim, for instance entertaining the public [E.g., see @gilm20]. So we just typically accept that it is unlikely that lyricists are doing anything like making an authentic value claim in their music.

There are two kinds of claims made regarding the ascription of moral value in popular music. Descriptive claims are about whether popular music does ascribe moral value and normative claims are about whether popular music should ascribe moral value. Oftentimes, the general public perceives a value ascription in popular music and the question then becomes whether the appearance is true of the fact. Further more, country music is thought to be evidence in support of this claim while other popular music is evidence against it. Relatedly, it has largely been accepted that country music expresses a given value whether it is one the author espouses or not [E.g., @malo23; @dyck18; @shus99]. One complication inherent in the literature is that value ascription is more commonly *perceived* in country music and less commonly perceived in other genres. In what follows, I offer an account of value ascription arguing that the expression of regret for what happens in a relationship would enable the perception of value ascription more generally than the alternative.

## Introduction

The need for diversity in the public square is a popular conversation currently. A different kind of conversation that is less popular asks questions about authenticity [@malo23; @dyck21a]. Regarding country music, such questions consider whether 19th century Appalachian music counts as country music or whether it counts as folk instead; whether country music should have drums? horns? Strings, etc? Another point of discussion is also the race or ethnicity of country music artists, their origin, and its fans. We might ask what an authentic country music artist looks or sounds like for instance [@dyck21a]. However, while interesting, these aesthetic discussions may fail to capture what is at the heart of country music’s aesthetic appeal, which is neither race nor ethnicity, nor the formal features of county music’s sound. But just as importantly, questions about authenticity also draw our attention to another implication, namely cultural autonomy regarding the representation of a community’s values and notions of well-being. Such questions about authenticity that concern a community’s values are often overlooked with regards to country music, but also hip-hop music.

When asking questions about whether an expressed value statement is authentic or not, we first need a way to understand what a value statement in music will likely look like. There can be a few ways of defining what a value statement in popular music is. What this paper does, is to draw the readers attention onto what I consider an explicit value statement.

Consider the lyric below from Post Malone’s *Rich and Sad*:

::: {.unnumbered #stuntin}
“All this stuntin' couldn't satisfy my soul (–oul), Got a hundred big places, but I'm still alone (–one)”.
:::

Next, contrast this against another lyrics where it is suggested that "[money can] satisfy my soul”. E.g., especially as in Ty Dolla’s *By Yourself*:

::: {.unnumbered #boss}
“Stacked your bread and bought your own Mercedes (Vroom, vroom). You your own boss, do it your way (Way)
:::

It is initially obvious that we can question the difference in the value of money in either example. Also, it is relevant to mention that the value ascription in either song is not money, but a difference between the value of independence versus that of co-dependence. In either case, what is important is that here, expressed emotional dispositions can effectively portray the endorsement or rejection of a given emotion state regarding how things went. This whether in a relationship, a change in one's financial circumstance or something else entirely. Importantly, there is a question about the representation of a proposed inter-relational value. I am not suggesting that one example is definitively an example of ascribing more value to money in one versus the other. Rather I am suggesting what might it look like to recognize the ascription of value as expressed in a popular song. What emotional value ( whether a negative valence, e.g., -0.531?) is the author ascribing to money in *Rich and Sad* versus the emotional value (say a positive valence, e.g., 0.215?) is the author prescribing to money in *By Yourself*?

Traditionally, we may think that aesthetics requires us to divorce art from practical concerns, where a practical concern can include questions about what a good life is, and how one achieves it. Accordingly then, country music is about practical concerns [E.g., @levi16; @grac16]. However, we have reason to believe that another kind of *aesthetic* concern has to do with what constitutes a beautiful life. Any practical concerns in this regard are also concerns about what is beautiful. A beautiful life is one that is well lived and worth being lived. More importantly, there are values which we desire, and often hope to realize in a beautiful life. For instance, it has been remarked that life without art would be boring, bland, feature and expressionless.

It is not just that art in life is beautiful however, but that a life well-lived is itself beautiful in much the same way that art is. As such, we care, or have reasons to care about what contributes to having lived a beautiful life. Values are often said to be central to such cares. To have "lived a beautiful life" can mean living in pursuit of what one found to be meaningful. In this way, values are abstract since they are not tangible. "Abstract" has varying meanings. For instance, the blurb on the back of a book, or at the top of an academic paper that summarizes the contents of the book or paper, is often called an "abstract". Values are a different kind of abstract. They are disassociated properties of items, events, and people.  When you ask yourself what your values are, what comes to mind are those things that you deeply care about and can define you. Values are often represented by the expression of terms like family, friendship, justice, truth, education, etc, all of which are abstract. These concepts, though abstract, cause us to feel deeply. Concrete objects, like rocks and bullets can also cause us to feel, but abstract properties cause us to feel differently than rocks do. They are often the source of strong emotions within us. However, sometimes *value* in and of itself can be used more loosely. Let's imagine that I value my father deeply. At first, one thinks that what I mean is that there is some object out in the universe, and that this object motivates strong emotions in me. While it may be true that the mere presence of my father does motivate strong emotion in me, it is not clear how we might think of my father *as a value construct*. Because of this, someone may say that not all values are abstract since my father is not an abstract property, but a concrete one. I can smell, touch, hear, taste this property that I value and therefore not all values are abstract. But it is not my father's smell that I value, but rather its his smell that reminds me of values that I hold, perhaps his loving devotion to my mother, his care and concern for the welfare of his children, myself included, his central role in caring for the community, always present, etc.

An important point of discussion about about value, includes discussions of their source and the way they are conferred. How do we share our values? Can we entice others to adopt our values as their own? Recently, philosophers working on country music have asked whether country music expresses value [@malo23], negotiates them [@dyck21a], or is a source of them [@meis22a; @mann08].

## What is Country Music?

Country music from its very inception stems from a diverse array of American cultural traditions. There have been moments wherein the cultural traditions together made strange bed-fellows. Individuals like Etta Baker, Deford Bailey playing at the Grand Ole Opry, Freddy Fender and Los Lobos^[Some have questioned Fender and Los Lobos's acceptance into the country genre. What is important here however, is that country music has many diverse origins which for whatever reason, often fail to receive the credit for their influence. E.g., @malo02] whose contributions are so significant that it would be difficult to imagine country music without their influence. Linda Martell for instance, is a less well-known story of the American dream regardless of how unlikely that dream may have been. These individuals have contributed the sounds that we often associate with country music.

Nevertheless, regardless of the diverse nature of country music’s roots, many academic discussions on country music assume that the content of country music fortifies a set of values only central to a specific social class and cultural identity.^[@meis22a; @shus99; @mann08; @holl19; @haye10; @pete05.] @malo23; @dyck21a have recently offered what may be construed of as rebuttals of this view where country music is a kind of discourse wherein artists and audiences work to construct their own practical identities. But this in and of itself does not negate the claim that country music is a discourse wherein audiences and artists work to construct a practical identity. It may very well be the case that the values expressed in country music are culturally relative, but I suggest this needs to be explored further.

Consider the following:

> For, despite Bush’s claim that ‘country music crosses the barriers of culture and language’ (and the strange attempt to somehow frame rhythm and blues as a subgenre of country), country music is widely perceived to be ‘white’ music produced by white people, consumed by white people, apparently appealing almost exclusively to white people, at least in North America. [@mann08, 74]

There is a perception as noted by Geoff Mann, that country music is music published by, written by, sung by, and consumed by white Americans. It may seem to be the case that if a group of individuals sharing a common culture contribute to a cultural product, that this product would reflect, in sound and appearance, that group. But Mann then argues that it is perhaps more likely that country music creates this perception and not the other way around.

> For if country sounds white, it is perhaps worth considering the possibility that something claiming the status of ‘white culture’, something like a purportedly American whiteness however historically baseless is not reflected in country music, but is, rather, partially produced by it.

But there is a move that he makes from arguing that country is consumed by and produced by an individual social class, to the claim that the sounds associated with country music are also exclusive to this group.

> Country music sounds white so much so that Bill Malone, country’s pre-eminent historian, can remark matter-of-factly that the singing voice of Charley Pride, the only non-white ‘star’ in the history of the industry, ‘was so country that no one suspected he was black’ [@malo23, 313]. [@mann08, 74]

From this claim about perception, to one about sound, he makes his way to an additional claim, that the values posited in country music, are those exclusively of this same subgroup.

> To mention only some of the more prominent, country’s lyrical fixtures include rural life, work and everyday working-class life (especially contrasted with that of the affluent), heterosexual ‘salvific love’ [@gros02], family life and ‘values,’ the southern US, youthful rebellion, Christianity, alcohol, death, humor, and nostalgia. [@mann08, 81]

It is this further common claim that is the subject of this paper, which I treat as a claim about value.

A more central approach in academic discussion concerns the values that are often attributed to country music. Are the themes inherent in country songs white, or global? There are values under discussion that are said to contribute to the authenticity of country music. But these are often expressed along lines of upholding specific privileges along racial or gendered lines [e.g., @meis22a]. Values in this sense are thought to be rooted in foundations of certain specific cultural privileges, political associations, societies, or genders which individuals may or may not broadly identify with. But as I will go on to show, this is different from the argument that particular values like love, friendship, faithfulness, etc, are exclusively white values.

## Authenticity, A Primer

In his Moving Truth and Authenticity in Country Musicals, @shus99 questions an account of authenticity in conversations about country music. One aspect of authenticity in country music are its depictions of what he calls “traditional” lifestyles. Included in such depictions are social roles ascribed by gender, or family dynamics thought to represent specific racial identities [Also see @hube13; @mann08; @holl19]. Such views hold that the cultural dynamics expressed in country music are expressions of white culture. I am hesitant to add the qualifier 'only'. This is because what should be one source of contention, is the question of whether values like love, friendship, faithfulness, etc are specifically 'white' values, while another source of contention should be whether or not they are 'only white' values. One particular cultural dynamic here that goes under-recognized, are the values ascribed broadly to country music, and just how specifically accurate these ascriptions are. But more important is the question of whether they are accurate only with respect to that specific cultural ascription.

First, it is noticeable that themes such as hard work, loyalty, perseverance, are often said to be synonymous with country music as stated values. But similarly, it is difficult to imagine a world wherein hard work was not expressive of a virtuous character or one wherein hard work does not factor into what makes a life fulfilling. For instance, we would be hard-pressed to imagine that an individual who works hard to secure the well-being of their family, friends, and neighbors, whether they be a given political association, or professional occupation, as being somehow morally deficient on account that they work to secure the well-being of those in their sphere of influence. Similarly, character traits like loyalty to family members, also express virtuous character as loyalty to family can easily translate into loyalty to values. It is difficult to imagine loving one’s family members as a vice, namely it being somehow vicious for an agent's motivation for behaviors affecting those in their sphere of influence coming from something analogous to love as it is broadly defined. Or that we could imagine that the lack of such motivations is part of what makes a good life complete.

As such, if country music is an expression of whiteness, then this means to say that manifesting certain positive character traits is synonymous with being white. This is similar to @alfa13's use of the term 'moral technology'. in his book Character as Moral Fiction, @alfa13 suggests when we are told we possess a certain character trait, then this attribution becomes a self-fulfilling prophecy in that we are more likely to begin displaying that trait than not. It is this view taht most closely resembles Mann's assertion that country music partially produces white culture.

Arguments such as the one above are often grounded in ideological projects to associate country music with ‘whiteness’ and only with ‘whiteness.’ As such, character representations such as loyalty to others, stem not from autonomous moral agency, but an agency that aligns more closely with one’s race and ethnicity where one's race and ethnicity is formed in part by moral tecnologies like country music. My behavior then is a result of my race or the culture I’ve become acculturated into (for instance the many times Charley Pride is accused of being white). Kane Brown's admiration for his "hometown" heroes in his song 'Hometown' even given his success as an entertainer, is not because of individual character or virtue, but because of moral technologies ascribing his values to him. In other words, when a country artist like Kane Brown does become a country artist in the traditional sense, expressing traditional pro-social values, the fact that Kane Brown is mixed African American and American Indigenous, is no longer a mark of his identity.

We often attempt to defend the view that country music consists of songs which guide or entrench cultural privileges. Given that such portrayals are articulated by us who typically hold a culturally important position in the communications of meaning, another way to view the discourse, is to see such accounts as exemplifying a kind of master narrative. Following McLean and Syed, this means culturally shared stories that “guides thoughts, beliefs, values, and behaviors” [@mcle15, 323]. In this case, the academic discourse on country music, serves as a master narrative possessing the potential to shape our thoughts, beliefs, values and behaviors as to what values are promoted by which individuals.

Before we look at psychological accounts of narrative, it will be important to first clarify what's at stake, namely popular narratives which characterize special relationships as central to human flourishing. In the following section, I describe an account of vulnerability as an ethical obligation grounded in our human nature. One might note a similar concern in @maci99's *Dependent Rational Animals*. However, I think that Martha Nussbaum's treatment of vulnerability as an important human condition is closer to what we care about in human relationships. Therefore I will consider vulnerability as central to an account of ethics rooted in narratives about what sort of person we should be. To do so, I will consider the popular hip-hop song *Rich and Sad* by the artist Post Malone and contrast this against Nussbaum's account of Agamemnon. I argue that in a genre noted for its lack concern with special human relationships, Post Malone, in what might be described as a parody, does just that, namely declare the importance of a particular relationship for his personal flourishing, expressing his human vulnerability for companionship.

## Authenticity, and moral narrative frameworks

@nels04b have called stories, socialization processes. Accordingly, autobiographical memory is an explicit memory of a formative event, or series of formative events in childhood. This memory system is composed of the acquisitions of language, narrative comprehension and production, and contribute to how we understand and represent ourselves. It is sufficient that this developmental process is largely social, embedded in a *social milieu in which particular forms and contents of experience are valued and shared* [@nels04b, 13]. Here, the social and cognitive sources of the developmental process are intimately intertwined. While the social environment is posited as a factor contributing to the autobiographical development of an individual, it is not necessarily clear in this context what that factor constitutes.

For my purposes here, there are three kinds of narratives that complicate a narrative account of agency and personhood. They include autobiographical narratives [@mcad13; @mcad14; @pasu16]. These narratives are internalized reconstructions of events. They include an emotional evaluation of such events and taken as a whole; and are central to a personal understanding of who one is. Biographical narratives are externalized reconstructions of events. They are culturally specific stories that are often accepted by the members of that society to either internalize or to resist [@mcle15].

What makes an individual loving, caring, compassionate, etc, and what does culture have to do with this transformation? Continuing in the narrative literature, @mcle15 proposes a model grounded in narrative. They argue that there are three types of narratives that are important for the formation of one’s identity. The first distinction is between personal narratives which are narratives that are used to make sense of the self over time and across contexts [@mcle15, 320--321], and master narratives which are stories about a given culture. These tell us what it means to be a member of a particular culture. They also tell us what it means to be a good member of a particular culture. To be conservative, belong to a community of conservatives, one should be fiscally responsible, believe in small government, etc. It may be the case that what it means to be a good member of one culture, according to a given master narrative, is different from being a good member of another [320]. Assuming the later, alternative narratives, then, are important as they provide a means to resist master narratives when necessary. Master narratives can sometimes be harmful to some individuals in a community, for instance by identifying those individuals with violent or misogynist behaviors. Alternative narratives then, allow individuals to negotiate their own personal narratives as either different from, or resistant to, harmful master narratives. Crispin offers one kind of alternative narrative account, but here it is not clear if the alternative is to enable the members of the outcast community to see themselves as vulnerable and reliant on one another for the intrinsic goods that doing so provides, or something else.

It is not always clear what forms biographical/master, autobiographical/personal, or alternative narratives take. I suggest that an answer to this question could begin by looking at artistic expressions of emotion and authenticity. Artistic license in representation here refers to the control that artists may exercise over their music, and fans may do so through purchasing power. We might talk about artistic licence, a form of autonomy attributed to truly independent artists, as the ability of the artist to construct narratives without being under the threat of coercion. But here the threat is not only from the entertainment industry, but can also come from the audience. An artist may become concerned that unless they produce content with popularly held cultural views for instance, then they will not get enough streams, likes, downloads, etc. However, we also want to confer creative licensing to the audience as well. Artists often have the responsibility of representing particular communities. More importantly, these representations work in two different directions. While a master narrative is not a story, or narrative about an individual's own life, they are stories that are available to individuals via a community, to internalize or to resist. In this sense, it would be important for artists and fans to have control over the objects represented through their songs as these act as all too important alternative narratives. Instead of traditional ‘white masculine’ power as a cultural identity, or as an individual who is capable of replacing human connections with material possessions, as portrayed by either the entertainment industry, or academia, the artists and fans (through purchasing power), themselves control the artistic presentations afforded by country music resulting in portrayals of faith, family, compassion and other values important to their communities, and necessary for the flourishing of these communities.

The authenticity discourse in country music is rooted in discussions about shared values. “[W]hen country artists and audiences say that a song is authentic or real, they are telling us that they think that the song should be considered as part of the canon of songs which make up the community’s statement of values” [@dyck21a, 12]. Art provides such perceptions to us through the use of framing effects to control the emotional experiences we have in response to these artistic representations [E.g., @gilm20]. Roy Robert’s “Keep old Joe,” in this context is about the fear many feel should an important relationship become strained, and when Joe Simon in his “Nine Pound Steel,” laments his inability to say “good morning” to his significant others due to his prolonged incarceration, he expresses a particular value regarding his loved ones.

Objects presented in a given song arrangement represent a community's values, their reliance on, and need for other members in that community. An authentic expression of country music faithfully represents these values. However, questions about authenticity are also connected to questions about gate-keeping in the genre, whether or not the industry restricts participation within the genre; and whether it is racist on account of said gate-keeping and participation restriction. Because depictions of tradition are often grounded in communal values, country music has traditionally been criticized on account of the above concerns. According to the criticism, country music is a reactive response to an increasingly diverse society as specified by a reinforcement of such values.^[Where, then, can one find a specifically white American ethnicity expressed in a distinctive, ethnic popular music? Country music is the obvious answer. Like rap and reggae, it provides a complete cultural style replete with distinctive dance, fashion, food, and behavioral ethos [@shus99, 222].]

It is often the case that country music mentions relationships. When George Jones sings “I’ll still love you til I die,” or Old Dominion sings “I don’t want to be a one man band,” both are mentioning qualities about a relationship, or a desire for one. Such artists are expressing the depth of value that they place in their relationships. Though the concerns that develop surrounding country music are rooted in questions about authenticity and value, we should also think of value here in terms of “guiding principles by which one organizes the commitments of one’s own life.” As @dyck21a states “authenticity becomes a flag for more general issues about where one’s ideals lie” [11]. Authenticity in country music, then, is perhaps a real commitment to those principles underlying the value that we place in other individuals. In regards to music artists, the question becomes about an artist’s representation of their commitment to others in a given community, or that their popularity stems from the expressions of narrative adoption by a free and autonomous community. Expressing a given value does not necessarily ascribe that value in terms of race or gender or preclude other races or genders from possessing similar values or expressing their autonomy through streams and downloads.

The cultural identity attributed to country music concerns the values we place in particular close members of a community. An important way to recognize these values is through the emotional context that the song suggests. When George Straight sings about being able to "still make Cheyenne", the muted tones of his slight yodel do not imply that this is a welcome turn of events. Rather, the song's narrator has failed to qualify for a Rodeo content. Initially he takes it as a sign to return home to his significant other, however she informs him that she is leaving him upon having met another who "ain't no rodeo man". A curious feature of *Cheyenne*, is that the narrator can be understood as expressing relief that he no longer has to be conflicted about failing to meet his relational obligations. Importantly here, it is therefore not clear whether the negative emotional valence is in response to the fact that the narrator is now single again.

A similarity in both stories, is that the resulting conflict is unavoidable. In each case,there are no available options for the narrator to repair their relationship. Apparently, neither recognizes this conflict although it is painfully obvious to the audience. Maybe we are supposed to understand the importance of pursuing our dreams even when it costs us other equally important goods. In this way, "I can still make Cheyenne" is similar, or close to the style of the Greek tragedy Agamemnon. Here, King Agamemnon has been tasked with pursuing justice owing to his sister in law's abduction by Paris. A series of events unfold undermining Agamemnon's pursuit of Paris. Ultimately it is prophesied that Agamemnon would have to sacrifice his daughter in order to exact revenge. A difference between the Greek tragedy and George Straight's, is that it may be argued that Straight clearly express sorrow as evidenced by the stereotypical country stylings invoked in *Cheyenne*, while Agamemnon does not. @nuss01i argues that this is the point of King Agamemnon, representing a decrepit character in the inability of Agamemnon to express the all too important sorrow we should expect when a relationship has been destroyed.

When the characters central to country music loose their wives, or families, often this is seen as a tragedy and the audience is led to experiencing the all too important emotions in that given context, even when the characters are unable to do so as in Townes van Sandt's Poncho and Lefty. The worry as I've expressed it, is that the argument that such values as expressed through these emotions are representative of a specifically white cultural population, infers that other non-white populations do not hold such values. However most, if not all individuals, value other members of their communities, or at the very least, would be an evolutionary adaptive benefit for them to do so. Considering the cultural identity of valuing shared interpersonal relationships attributed to country music, then country music is about universal ethical commitments to one another, rather than racially or ethnically particular ones.

As such, authenticity may be viewed negatively as entrenching specific traits that align with specific cultural, racial, or ethnic identities, as expressed above. However, many of these attributions are generated by a profit centered entertainment complex and not the communities the stories in country are central to [E.g., @gilm20, 132]. Once we consider the cultural importance of narratives, tying authenticity in this way with industry generated representations of cultural, racial, and ethnic identities implies that such representations predict a certain behavioral ethos. As such, industry representations here control cultural representations that are thought to be grounded in a given behavior. Whites produce and listen to country music in which are grounded values such as community, relational loyalty, and hard work, whereas blacks listen to hip hop in which are grounded values such as non-relational individualism, and materialism.

## Relational Goods

According to @nuss01i, Aristotle's *Politics* and *Nicomachean Ethics (EN)* contain a unique feature. This argument is a defense of the intrinsic value of the political reality of human nature against the argument that this reality is merely an external good. The question concerns whether human beings need to necessarily participate in public life in order to experience *Eudaimonia*, namely, a well-lived life. If the argument is successful, it would go on to show that a human life is incomplete without the ability to participate in public life, including the opportunity to hold public office, or the ability to participate in making decisions which affect the populous to which one belongs. One premise in this argument, is the importance of interpersonal associations. That a reason wherein a solitary human life is an incomplete one, is because of the special value that we as a species place in belonging to a close population of others, both politically and interpersonally.

> And surely it is peculiar to make the *makarios* a solitary: for nobody would choose to have all the good things in the world all by himself. For the human being is a political creature and naturally disposed to living-with (EN, 1169b16--19).

One way to investigate the above claim, is by looking at typical human artifacts. How much weight do we place on the value of sharing our lives with others. In the moral psychology literature, several individuals have sought to test the degree in which human societies have traditionally placed emphasis on the importance of interpersonal virtues in regards to sharing one's life with another. For instance, in his *Moral Universals: A machine-reading analysis of 256 societies*, @alfa22 captures ethnographic accounts of ethics from 256 cultures. Working against the ethical backdrop of morality as a system of cooperation among members of a culture^[e.g., see @curr16; @rai11; @haid10], Alfano tallies records of evidence of seven moral foundations according to which morality is a system of cooperative behaviors with a given relational virtue amounting to each of the foundations. Among these is the foundation of family values wherein we feel a special obligation to care for extended family members. A common question about our special obligations towards one another may be how much weight do we place on personal connection [e.g., see @toma13, 233--234]. Treating various love songs that have one particular special feature, that the narrator in the song claims that all their material possessions lack any value without having others to share these material goods with, I argue that treating some popular songs as a type of ethnographic data can reveal interesting conclusions about our values as a human society.

My argument here is that an artist really isn't always trying to be edgy. That deep down, they are attempting to express a widespread and common experience and make sense of that experience. As such, I treat the *Makarios a Solitary* as a place where we are destroyed, or imagine ourselves being destroyed owing to the weight we necessarily place on the value of having special relationships in our lives. The position many songs attempt to address, is that a good life is impossible without these relationships.

> I am an agent, but also a plant; much that I did not make goes towards making me whatever I shall be praised or blamed for being that it is equally problematic to entrust one's good to friends, lovers, or country and to try to have a good life without them all these I take to be not just the material of tragedy, but everyday facts of lived practical reason. [@nuss01i, 5]

According to Nussbaum, a common theme in Greek tragedy is to show good people being ruined 'because of things that just happen to them' [@nuss01i, 25]. How does this ruin come about? The ruin is often a choice an individual is forced to make. The choice is typically horrific. An example of such a choice is found in Aeschylus's *Agamemnon*.^[E.g., also see @lesk66] Here, Agamemnon is faced with a dilemma resulting from two contradictory divine demands. Agamemnon must sacrifice his daughter, a proposition, which for reasons that I will flesh out in more detail shortly, will call '$\lnot$ you', in order to appease the goddess Artemis so that he can exact vengeance on behalf of Zeus. The proposition, appease Artemis in order to exact vengeance on Zeus's behalf, I will call 'gold chains'. Initially, Agamemnon must choose between his relational obligations towards his daughter Iphigenia, what Nussbaum calls *relational goods*, or procuring favor with the god Zeus. If he makes the decision to pursue the campaign to exact vengeance on behalf of Zeus, then he is effectively choosing other goods over and above relational ones.

These two propositions can be expressed in relation to one another in one of two ways that are equivalent. The first is materially conditional, where the material conditional is 'you $\rightarrow$ $\lnot$ gold-chains'. Meaning that, should Agamemnon elect to observe his relational obligations to Iphigenia, he would be unable to enact vengeance on behalf of Zeus. Additionally, these two propositions can be expressed using a disjunction, 'you $\lor$ gold-chains'. Either Agamemnon satisfies his demands to protect his daughter Iphigenia from harm, or he carries out vengeance on behalf of Zeus. The first proposition, you $\rightarrow$ $\lnot$ gold-chains, means that should Agamemnon choose to reject sacrificing his daughter Iphigenia, then he would lose honor, or whatever it is that accompanies satisfying the demands of a god. Instead, Agamemnon chooses 'gold chains' ('$\lnot$ $\lnot$ gold chains'), sacrificing his daughter resulting in $\lnot$ you.

However, it is not the choice that is reprehensible here, rather it is the ease with which Agamemnon makes the choice. In other words, Agamemnon is not ruined by his choice.

> he adopted an inappropriate attitude towards his conflict, killing a human child with no more agony, no more revulsion of feeling, than if she had indeed been an animal of a different species [@nuss01i, 33]

Ethically speaking then, Agamemnon's downfall was the fact that he wasn't ruined by the choice. We should expect that the killing of other human beings come with a cost all their own. Even in victory, we expect the victor to be plagued by guilt, or sorrow at having to take the life of another human person so much like himself. At the very least, we expect the murderer to be fundamentally and forever changed. Many times, such a ruin can be noted when the agent is no longer capable of being ruined which is perhaps a more tragic outcome. Many rap songs are tragic in this sense, where the rapper is not ruined by the choice he or she is forced to make. But this implies that the rapper is already ruined long before the relevant event. In other words, '$\lnot$ you' is often chosen with ease. For instance, a constrasting case would be the choice Sophie had to make in William Styron's *Sophie's Choice*. Sophie was ruined, electing to kill herself rather than continue living with the decision that was forced upon her. Perhaps a worse outcome would be one in which she never thought about this choice again and went on to have a happy life instead. However, we are not often dismayed at the choices rappers are forced to make in this regard. Perhaps rappers like to parody Greek tragedies in this sense, if true, then *Rich and Sad* is a parody of other parodies. Another possible understanding however, is that the rapper is a representation of someone who is ruined already, incapable of the typical human emotions of guilt, shame, sorrow and regret. In the following sections, I will argue that Post Malone's *Rich and Sad* revert this standard narrative in rap songs in a unique way. Perhaps somewhat pedantically, *Rich and Sad* shows the narrator as having been ruined by a tragic choice, displaying his need for interdependence and relationship, oddly, Post Malone is known more recently for recording country songs expressing similar vulnerabilities.

## Post Malone's *Rich and Sad*

Though not representative of all forms of hip-hop music, many hip-hop songs, if interpreted literaly, can be said to promote common negative themes of material wealth and substance use, anti-social behavior such as misogyny, and relationship commodification. An example is Ty Dolla $ign's *By Yourself*. Here, $ign is praising an individual for what are seen as character traits of self-reliance and independence rather than interdependence and non-material need of others.

<p> Stacked your bread and bought your own Mercedes (Vroom, vroom)</p>
<p> You your own boss, do it your way (Way)</p>
<p> Quick to tell a broke n-, Go away (Go away)</p>
<p> You ain't never 'bout no drama (Nah, nah)</p>

Here, the lack of material possessions by one member of a party, is justification for severing the relationship with the other member. There are two outcomes here, on the one hand, neither member expresses a vulnerability virtue theorists claim is common to the human experience. The suggestion here is that there are no other plausible positive character features that the subject may possess that warrants companionship grounded in such vulnerabilities. Material possessions here are the only important good, and as such, there is no reason to continue the relationship. This negates the importance of plutonic relationships in addition to romantic ones, as these are generally not pursued for material possessions.

The common difference here concerns prioritizing material wealth over personal relationships. In his song *Money Trees*, Kendrick Lamar raps about the influence of money over the decisions one makes in regards to others. Although Lamar does not seem to express any sort of remorse over the fact that we might prioritize material wealth over interpersonal relationship, he still notes that money is a corrupting influence over interpersonal relationships. On the one hand, it is likely that *Money Trees* is a cautionary tale about such corrupting influences, though the general refrain of people being mere objects of practical importance is not far behind.

<p>My homeboy just dome'd a ni--a, I just hope the Lord forgive him</p>
<p>Pots with cocaine residue, every day I'm hustlin'</p>
<p>What else is a thug to do when you eatin' cheese from the government?</p>
<p>Gotta provide for my daughter n'em—get the f*** up out my way, bish!</p>

These are just some of the examples in support of the common characterization, that if taken literaly, hip-hop is violent, misogynistic, anti-establishment and anti-social. In contrast, country music, though having gone through periods of varying relational standards, is argued to be unsophisticated and or prejudiced, but that it also represents themes of nostalgia for family and home life. Importantly, it is thought that country music defines the white American experience in rural environments while hip-hop defines the African American experience in urban environments.

However this particular disjunct is highly contentious with many music theorists defending the assertions in rap and hip hop music as benign. For instance, @sart98b defends stereotypical characterizations of rap as violent, etc., that we may often argue are anti-social character traits. Prevalent in these are expressions are a kind of resistance. Rather than conceptualizing rap and hip hop as promoting materialism and individualism, Crispin argues that the images attributed to African Americans in hip hop as violent, or misogynist, are transformations, "oppression into resistance". As @shus99 points out however, it is important to note distinctions between rap and hip hop more generally. For instance, according to Shusterman, one such distinction is between rap and *gangsta* rap, the former being a commercial product rather than a culturally ethnographic account of a community's values. While Crispin articulates hip-hop as a form of resistance, Shusterman distinguishes between forms of hip-hop, an important point that we should acknowledge, is that the forms that are ethnographic would be those that could be reliably used as forms of resistance to oppressive biases.

Considering market forces central to music production, perhaps there is a general commercial demand for figurative portrayals of African Americans as violent, etc., motivating such portrayals given the market demand.^[See @layb18] But whether the more violent and misogynist elements are rooted in a demand for representative ethnographic account, protest, or something else more sinister, is an important question. One way to approach an answer to such questions would be to consider what is unique about humanity in general and use this whatever trait that we would identify as a central focus on a given layer of a representative ethnographic accounting of a particular community.^[@huan23; @born10; @born20a; @bowk18] Some songs, through their reprsentation of relationship between people, are more representative of the common human experience. Others however, because of market forces, fail to accurately represent the human experience.^[E.g., see @layb18; @shus99] Malone's *Rich and Sad*, as I will show, offers an artistic example of this distinction. In regards to a song's capacity to represent an individual as possessing other important societal virtues, such as the subject's ability to care for vulnerable others, make material sacrifices in order to strengthen one's bonds with another etc., such attributions would better represent a kind of social protest. Namely that, a better form of protest would discredit negative stereotypes regarding one's potential dispositional character regarding interpersonal values, by using one's artistic talent for expression, rather than reinforcing them.

While there are innumerable points of topic for either genre, what is of dominant concern for this paper, is that of authenticity regarding the experiences of various Americans. Most importantly here, are those experiences regarding interpersonal relationships as represented through either genre. Given that hip-hop is commonly thought of as anti-social because of its misogyny and violence, a common caricature then is that it may represent certain individuals as anti-social. In contrast, other individuals, as represented through country music, are focused on building strong family relationships, civic relationships, and nurturing capacities of compassion and sympathy in future generations.

As such, some may be justified in thinking that country promotes a representation of white Americans as pro-social. Although there is plenty of room for disagreement of either claim, this project will focus not on the defense of these claims, but rather on the implication that one's artistic expressions can describe a culture as accepting or rejecting certain cultural values. This can include the emotional valence that accompanies the mention of purported value statements embedded in song lyrics that are central to interpersonal relationship and material possessions.

We can summarize these common themes with a standard disjunct that expresses the hierarchical ordering of relationship and material possession. Accordingly, the typical disjunct then in the songs under consideration is 'you $\lor$ gold chains'. Under the first disjunct, we can imagine that we have some given agent 'you'. Because the 'you' is spoken in the first person, the agent 'you' always references someone other than the speaker of the phrase. Under the second disjunct, 'gold chains', we have any potential material possession, or object of instrumental value only. We can define 'material' as any object that is devoid of personal agency, and as an object devoid of personal agency, representing some perceived extrinsic value. In various contexts, one may forgo their relational obligation in the context of self-preservation, or the preservation of a material, non-agentiated, good valued over and above a relationship with the speaker of the term 'you' or a potential relationship. Conversely, we would imagine what sacrifices one might make to preserve a relationship that is valued over and above material possessions, for instance, a spouse may give up further promotions in a given career under the pretense that these will reduce the amount of quality time they might otherwise have with their family. Or another spouse with a sick partner may choose a career in the trades for the provided health and medical benefits instead of finishing grad school.

In songs that prioritize material possession over relationship, the second premise would be '$\lnot$ you'. However, in songs that prioritize relationship over material possession, we would want the second premise to be '$\lnot \lnot$ you' rather than the double negated 'you'. It seems to me that the double negation would imply that under no consideration would the speaker betray a relationship without experiencing significant harm themselves. Of all the sacrifices someone might make, the relationship is not one that would be made lightly. As such, the double negation is more relevant here than its equivalent. For instance, let's imagine that the first disjunct is the positive 'you' while the second disjunct is merely a placeholder for many possible goods. Because one option would necessarily exclude the other, we can present the implication formally using a conditional statement. What this allows us to do is consider some possible consequences of our choices. If I really wanted money, perhaps gold bars because of their aesthetic qualities, then I would need to negate the left disjunct which gives us '$\lnot$ you'. Further, I think that the implication is a question of what I can live without, rather than a question about what I must sacrifice for a given good. Either I can live without gold bars, or I can live without a given relationship. Understood this way, it is either I can live without 'you', or I can live without 'gold'. Negating one of the disjuncts now becomes a statement about goods central to a good life.

In the later, the positive affirmation, the suggestion is that material possession under consideration, is valued less than the relationship in that while an agent could live without gold, they could not live without 'you'. But this says nothing about other material possessions which the agent may value over and above a given relationship. However, the double negation implies that sacrificing the relationship is unlikely if not impossible. In the first meaning, when forced to choose between the pursuit of a interpersonal relationship or material possessions, the agent is obligated to pursue the material possessions whereas the second, sacrifing the relationship is not an option for the agent.

The song *Rich and Sad* explores this expression of need. By entrusting his good to another and being ruined by it, Post makes a value claim about what is needed for a good life. In the context of this, he imagines needing another, and being ruined due to their absence. In other words, he imagines the impossibility of a good life without a particular special relationship. Of course, there are many examples in country music of this kind of vulnerability. However, there are not many in contemporary popular hip-hop music, and for this reason, *Rich and Sad* is a good example of the expression of human vulnerability in a popular song.

An important distinction to make here is between two popular claims about the value of other people in one's life. The form of the first argument, those often found in rap music, is as follows:

::: {.unnumbered}
Either one pursues a relationship, or one pursues material possessions but not both. Further, loosing out on material possessions is not an option, $\lnot$ $\lnot$ gold-chains. Therefore one ought sever the interpersonal connection $\lnot$ you
:::

We'll call this argument *The Agamemnon Solution*. Here, the individual is forced to choose between a relationship that he or she might value, or money and its equivalents. They forgo pursuing the relationship, severing the relationship, undermining the relationship to keep it from blossoming into something more, etc.

As the example is meant to show, there is a common admiration of traits of independence and self-reliance in such tropes. The point here is to highlight this trope by contrasting it against another. Importantly, on the assumption that *The Agamemnon Solution* is a common enough trope, we can make the argument that its refrain typically results in selecting the part of the disjunct that aligns most closely with material wealth and possessions, it negates the right, rather than the left, disjunct:

::: {.unnumbered}
Loosing out on material possessions is not an option $\lnot$ $\lnot$ gold-chains
:::

With the implication being that the song's narrator has to choose between the pursuit of a particular relationship or material wealth; *Stacked your bread* vs *Quick to tell a broke . . .* As such, the clear choice is:

::: {.unnumbered}
The individual severs the interpersonal relationship $\lnot$ you
:::

As mentioned already, this is the *Agamemnon* solution. The first premise is the choice between two disjuncts; relationship or material wealth. The second premise is that loosing out on the material wealth is not an option. The obvious conclusion then is giving up the relationship. You might have noticed that *gold chains* is slightly different than a standard disjunctive syllogism. This difference is negligible however. The only thing we've done is add negations to the formal version.

Of course something about this whole affair may be off-putting. The point is, it cannot be that the argument is invalid, so it must be some other aspect of the argument. Here we may think one of the argument's premises are false. My money would be on the second premise, giving up the gold chains is an option, the *makarios a solitary*. However, this would merely require us to negate the right disjunct which is not informative. It does not tell us that the individual gave up material possessions to pursue the relationship and so does not represent the moral of the story, the depth of vulnerability the individual possesses, the depth of humanity which the individual can display.

Often times, valid argument forms are equivalent with other valid argument forms. Considering this then, a better way of understanding Post Malone's contribution to Hip Hop, is by looking at one of these equivalency relationships. As we saw, the choice is compatible with a conditional one. Rather than *either or*, what a material conditional says, is that on the assumption that something is the case, then something else follows. Given that the narrator typically faces a choice, this state of affairs may be equivalent with the conditional that if an individual pursues a relationship, the left disjunct, then they will be left destitute with the antecedent being the choice that the individual faces and the consequent being the consequence of their choice, destitution. This can be seen below:

::: {.unnumbered}
If one pursues a relationship, then they cannot possess material possessions. 'you $\rightarrow$ $\lnot$ gold-chains'
:::

But, rejecting material possessions is not possible. $\lnot$ $\lnot$ gold-chains.

As we saw before, the first premise infers that there is a condition on which the pursuit of a given relationship will necessarily result in financial hardship, however the contribution that Post makes, is the expression of vulnerability in having chosen the wrong disjunct. Though it appears that Malone does choose material wealth, he experiences regret because of his choice.

It doesn't have to be however. Perhaps it *is* plausible that '$\lnot$ gold chains', is not an option for Post and therefore we're left with '$\lnot$ you'. Perhaps his significant other has already left before he made his millions. He tries drowning his sorrows with his significant wealth, but is unsuccessful in doing so. Still either way, Post chooses the path less taken in rap songs where '$\lnot$ you' leaves him with feelings of regret.

If this argument is correct, then an important implication would be to ask how do we teach the important virtue of social vulnerability, that of regret when experiencing the loss of a relationship. The role of identity development in personality trait formation, is a prominent theme in developmental psychology, ala @erik68 among others. While I do not pretend to be able to offer such an account of how to teach vulnerability, following Nussbaum, it may be enough to show that the purpose of tragedy is to help us to recognize our vulnerability. These relationships are uncertain however, often evoking questions about the role of human culture in forming personality traits. @brun90 has argued that formative narratives are shared within cultural contexts and that narratives are tools that make its users reflections of that community, (11). A question here then, is whether narratives are important for instilling human vulnerability.

Questions about country music’s practical value is important in that it highlights the practical value of music more generally. In this way, we can understand popular songs as a kind of master narrative. Further, it can then be important to understand less popular ones, those free from the coercive effects of the entertainment industry as a whole, we might think of as alternative narratives. Other concerns may also be raised such as the role between culture and behavior regulation. Importantly, what needs to be asked is whether projects such as cultivating a certain identity can be important or even necessary and what role popular music plays in this. One way to understand such questions is through a neo-Aristotelian focus on identities of human vulnerability, relationship, and the good life.

