## Adaptive Relationships:

### Tommy Curry

***Black Humanities:***

[Interview on Black Humanities](file:///C:/Users/redap/mega-folder/zotero_storage/Humanizing_Blackness_An_Interview_With_T.pdf)

> It doesn’t disown that there are different kinds of
experiences, but when you talk about Blackness in America, you’re talking about how
groups of people who are descendants of slaves and colonialism whose existence within the empire is conditioned by death. That’s a very different thing. And yet, there’s something
in Black people that says resist.

But there is something in Christian blacks "And yet, there's something in [Christian] Black people that says 'love'".

> We can’t both hold that the discipline is false
because it’s based on the illusions or perceptions of mythologies from the white mind, and
say that our notions of Blackness should have equal weight today. Why should we be equal
to the illusion? We know that’s false; we have to start intervening

* We have to start reimagining

> We have not yet even begun, even though we’re in the twentyfirst century, we have not reached a point where Black people could identify humanity
studies as just the study of Black people.

* We should understand it as the study of relationship as a core-component of who we are.

But there are two ways:

* as a nation
* as a people within a nation

I suggest how but first:

### Inventing Failure:

[Inventing Failure](https://www.academia.edu/51002655/Inventing_Failure_Being_Black_and_Male_in_Liberal_Arts_Graduate_Programs_Such_as_Philosophy)

Curry argues that African Americans ought to look beyond liberal arts programs in the US or the West because the liberal arts discipline allow and encourage unchallenged and problamatic stereotypes about black men to persist in Western culture.

I broaden the concept of liberal arts to include entertainment and argue that Christian Hip Hop as a liberal arts discipline seeks to undermine the harmful affects of other more traditional liberal arts disciplines. In other words, according to Curry, the way that the humanities dehumanize black men, Christian HipHop as a liberal arts discipline howeve, humanizes black men.

1. The liberal arts dehumanizes black men and women by undermining the black family.
   1. Academically encouraging black women over black men thereby destabilizing the black family.
   2. Creating and sharing tropes about black men that deter them from social ascension and cultural assimilation.
   3. Counter-intuitively asserting that black men have privilege and therefore restricting their participation in higher-education to make more room for other minorities, e.g., gender and political minorities.

The author advises Black men to recognize the anti-Black misandry of liberal arts disciplines and consider global job markets more open to exploring the experiences of Black men.

Black men should consider global job markets more open to exploring the experiences of black men.

Because liberal arts encourage stereotypes and pathological assertations of black men.

We should look at a more broad conceptualization of liberal arts education.

These institutional and inter-personal forms of misandric aggression dehumanize black men and harm their ability to obtain advanced institutional degrees.
