# Definition of stereotypes:

## Stereotypes

Tommy Curry argues that black men should consider global job markets more open to exploring the experiences of black men.

This is because academia harbor and encourage racist stereotypes and pathological assertations of black men. In other words, academia is a source of institutional and inter-personal forms of misandric aggression that dehumanize black men and harm their ability to obtain advanced institutional degrees.

Broadening a conception of liberal arts, I chart a path forward that mitigates universal intergroup harm by sourcing a humanities education that is sourced within the control of a given community. I then focus on two prominent examples of such a humanities education.

## Liberal Arts Emphasis is dehumanizing black men

> “The emphasis liberal arts disciplines place on theory often allows negative stereotypes and pathological assertions about Black men to remain unchallenged.” ([Curry, 2023, p. 1](zotero://select/groups/2202160/items/Y5UWRK9Z)) ([pdf](zotero://open-pdf/groups/2202160/items/U6KXED58?page=1&annotation=RVT5QKH4))

> “Drawing from an analysis of Black men depicted by the Moynihan Report as well as contemporary educational literature, this article argues that Black males experience institutional and inter-personal forms of misandric aggression.” ([Curry, 2023, p. 1](zotero://select/groups/2202160/items/Y5UWRK9Z)) ([pdf](zotero://open-pdf/groups/2202160/items/U6KXED58?page=1&annotation=RV77XLN3))

> “Researchers have shown that labor trends, geographical isolation, and racist stereotypes concerning Black men have had some negative effects on Black male degree attainment in the United States (Sharpe & Darity 2009; Hamilton 2012).” ([Curry, 2023, p. 1](zotero://select/groups/2202160/items/Y5UWRK9Z)) ([pdf](zotero://open-pdf/groups/2202160/items/U6KXED58?page=1&annotation=PIFJNY8D))

> “Black mothers particularly tend to encourage Black girls academically over Black boys (Wood, Kurtz-Costes, Rowley, & OkekeAdeyanju 2010)” ([Curry, 2023, p. 2](zotero://select/groups/2202160/items/Y5UWRK9Z)) ([pdf](zotero://open-pdf/groups/2202160/items/U6KXED58?page=2&annotation=UC9LW6PE))

> “Black males are evaluated and judged so negatively, they rarely interact with teachers outside the classroom and suffer from the social isolation and denial of networks that are so important to graduate education and professionalization.” ([Curry, 2023, p. 2](zotero://select/groups/2202160/items/Y5UWRK9Z)) ([pdf](zotero://open-pdf/groups/2202160/items/U6KXED58?page=2&annotation=YNWY5HCX))

> “yet no analyses that I am aware of have investigated how the Moynihan Report depends on the pathologization and dehumanization of Black males.” ([Curry, 2023, p. 4](zotero://select/groups/2202160/items/Y5UWRK9Z)) ([pdf](zotero://open-pdf/groups/2202160/items/U6KXED58?page=4&annotation=QP7WM4GS))

> “Moynihan merely reflects the mid-20th century theories of social scientists who believed Black men are a population deterred from social ascension and cultural assimilation.” ([Curry, 2023, p. 4](zotero://select/groups/2202160/items/Y5UWRK9Z)) ([pdf](zotero://open-pdf/groups/2202160/items/U6KXED58?page=4&annotation=9SHQHITH))

> “As William V. Spanos argued in The End of Education (1993), the core curriculum was an ideological apparatus constructed by American universities to repair the damage the Black radicalism and anti-imperialism of the 1960s did to the legacy of Western civilization.” ([Curry, 2023, p. 5](zotero://select/groups/2202160/items/Y5UWRK9Z)) ([pdf](zotero://open-pdf/groups/2202160/items/U6KXED58?page=5&annotation=7RCVLEHB))

> “For Spanos, liberal arts disciplines are organized around the preservation of civility and the prevention of future cultural ruptures which facilitated the student-based protests and new disciplinary branches such as Black Studies.” ([Curry, 2023, p. 5](zotero://select/groups/2202160/items/Y5UWRK9Z)) ([pdf](zotero://open-pdf/groups/2202160/items/U6KXED58?page=5&annotation=8G8JBJ2I))

These stereotypes hinder black males abilities to obtain advanced degrees.

> Researchers have shown that labor trends, geographical isolation, and racist stereotypes concerning Black men have had some negative effects on Black male degree attainment in the United States (Sharpe & Darity 2009; Hamilton 2012).

## But this is only problematic if advanced degree correlates with humaness

But these stereotypes do not just begin in academia, only that they persist there:

> Black mothers particularly tend to encourage Black girls academically over Black boys (Wood, Kurtz-Costes, Rowley, & OkekeAdeyanju 2010)

It is not clear however whether the isolation is only found in institutions of learning. If black mothers are likely to act on a given racist stereotype of black sons, then it is possible that misandric harm is not located only in these institutions.

> Black males are evaluated and judged so negatively, they rarely interact with teachers outside the classroom and suffer from the *social isolation and denial of networks* that are so important to graduate education and professionalization.

We might think that the social isolation black men experience

> yet no analyses that I am aware of have investigated how the Moynihan Report depends on the pathologization and dehumanization of Black males. Moynihan merely reflects the mid-20th century theories of social scientists who believed Black men are a population deterred from social ascension and cultural assimilation.

in society begins in the black home and as such, the stereotypes prevalent in the society begin in the black home.

For the purpose of excluding them from society

> While Black males were not the focus of many of the previous scholarly engagements with the Moynihan Report, an understanding that the racist theories used by white social scientists and psychologists were insidiously gendered and geared towards justifying the exclusion and removal of Black males from American society (Stewart & Scott 1978).

But once again, it is not necessarily clear that this exclusion is only found in acadmia. And as such, liberal arts in higher education have *only* sought to cement this practice.

> As William V. Spanos argued in The End of Education (1993), the core curriculum was an ideological apparatus constructed by American universities to repair the damage the Black radicalism and anti-imperialism of the 1960s did to the legacy of Western civilization. Spanos (1993) “In the aftermath of the Vietnam War, a massive educational reform movement was initiated in 1979 by Harvard University (marked by the adoption of the Harvard Core Curriculum Report)...

In order to undo the harm caused to western civilization by black militancy

> This reform movement has as its purpose the recuperation of not only the humanist curriculum that was shattered by the protest movement in the 1960s but also the discourse of disinterestedness now called into question by the theoretical discourses that have come to be called postmodern or poststructuralist” (p. xiv). For Spanos, liberal arts disciplines are organized around the preservation of civility and the prevention of future cultural ruptures which facilitated the student-based protests and new disciplinary branches such as Black Studies.

I argue that the harm originates in a broken family for which American institutions, or any human centered institution for that matter, are not in a position to redress. Namely humanizing humans.

> The radical student protests exposed the excess inadequacies of Western thought—its inability to produce student-citizen-humans capable of imagining much less recognizing the humanity of Blacks, Asians, etc.—were understood by the engineers of 20th century humanist education and the liberal arts (core) curriculum as destabilizing and dangerous to the reproduction of American (Western) cultural norms of knowledge making (Holloway, 2006).

Underscoring the threat posed to the west by not only black militancy, but any threat from a non-western cultural norm.

> In Sylvia Wynter’s “On How We Mistook the Map for the Territory, and Imprisoned Ourselves in Our Unbearable Wrongness of Being, of Desetre: Black Studies Toward the Human Problem” (2006) she argues that the Black Power radicalism of the 1960s and 1970s introduced a new way of thinking about the human. One that is rooted in a moral obligation to resist oppression directly.

> “Black male militancy changed the affective and political imaginary of the civil rights era and it is this disruption of both the white supremacist episteme and the order of civil society that liberal arts disciplines became set against (Corrigan 2020; 2016).” ([Curry, 2023, p. 6](zotero://select/groups/2202160/items/Y5UWRK9Z)) ([pdf](zotero://open-pdf/groups/2202160/items/U6KXED58?page=6&annotation=TDMF9TUW))

However, this would require of us a great moral burden that does not alleviate, mitigate, or undue a common suffering for marginalized groups. As such, it is not clear that it is necessary, or even beneficial. Instead, I argue for a need to define humanity in interpersonal relationship, as an aim of a new broader study of humanities and liberal arts.

## On Stereotypes

***Defining behavior:***

https://www.sciencedirect.com/topics/neuroscience/behavior-neuroscience

https://www.quebec.ca/en/family-and-support-for-individuals/childhood/child-development/effects-stereotypes-personal-development/definition-stereotypes

***Behavior and autism treatment:***

https://link.springer.com/referenceworkentry/10.1007/978-1-4614-4788-7_137

Maladaptive behaviors

https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/stereotyped-behavior#:~:text=Stereotyped%20behaviors%20are%20well%2Ddefined,clearly%20fulfil%20an%20adaptive%20purpose.

***Stereotypes and Judgment:***

https://greatergood.berkeley.edu/article/item/how_do_stereotypes_shape_your_judgment

***Stereotypes and Abortion:***

https://www.scientificamerican.com/article/who-gets-an-abortion-in-the-u-s-perceptions-dont-match-reality/

https://pmc.ncbi.nlm.nih.gov/articles/PMC9704102/

> Three quantitative studies found that women of colour had different experiences of abortion stigma compared to White women. Non-peer-reviewed studies of qualitative PhD-level dissertation research found that race, culture, religion and immigration had unique and complex effects on abortion stigma experienced by Latinx women. While abortion stigma is common, we found that there is a lack of research contextualising the racialisation of the United States. Quantitative studies found that women of colour experience abortion stigma at lower levels compared to White women. However, qualitative analyses of experiences suggest that quantitative measures of abortion stigma may not capture unique aspects of abortion stigma as experienced by women of colour.[Understanding the role of race in abortion stigma in the United States: A systematic scoping review](https://pmc.ncbi.nlm.nih.gov/articles/PMC9704102/)

***Question:***

[Situating stigma in stratified reproduction: Abortion stigma and miscarriage stigma as barriers to reproductive healthcare](https://www.sciencedirect.com/science/article/abs/pii/S1877575616301793?via%3Dihub)

> [Are] race and reported history of abortion are associated with abortion stigma and miscarriage stigma, both independently and comparatively[?]

***Relevant Results:***

> Among those who did report an abortion, white women perceived more stigma from abortion than miscarriage, while Black and Latina women perceived more stigma from miscarriage than abortion.

## Humanities and the Value of the Human Individual


Consider expressions of materiality and sufficiency conditions for well-being:

*  Post Malone’s Rich and Sad: “All this stuntin' couldn't satisfy my soul (–oul), Got a hundred big places, but I'm still alone (–one)”. Contrast: [money] “couldn’t satisfy my soul” with [money] “could satisfy my soul”
* Especially as in Ty Dolla’s by Yourself: “Stacked your bread and bought your own Mercedes (Vroom, vroom). You your own boss, do it your way (Way)

