# Black male studies and the bigger picture

## Adaptive Relationships:

### Tommy Curry

***Black Humanities:***

[Interview on Black Humanities](file:///C:/Users/redap/mega-folder/zotero_storage/Humanizing_Blackness_An_Interview_With_T.pdf)

> It doesn’t disown that there are different kinds of
experiences, but when you talk about Blackness in America, you’re talking about how
groups of people who are descendants of slaves and colonialism whose existence within
the empire is conditioned by death. That’s a very different thing. And yet, there’s something
in Black people that says resist.

But there is something in Christian blacks "And yet, there's something in [Christian] Black people that says 'love'".

> We can’t both hold that the discipline is false
because it’s based on the illusions or perceptions of mythologies from the white mind, and
say that our notions of Blackness should have equal weight today. Why should we be equal
to the illusion? We know that’s false; we have to start intervening

* We have to start reimagining

> We have not yet even begun, even though we’re in the twentyfirst century, we have not reached a point where Black people could identify humanity
studies as just the study of Black people.

* We should understand it as the study of relationship as a core-component of who we are.

But there are two ways:

* as a nation
* as a people within a nation

I suggest how but first:

***Inventing Failure:***

[Inventing Failure](https://www.academia.edu/51002655/Inventing_Failure_Being_Black_and_Male_in_Liberal_Arts_Graduate_Programs_Such_as_Philosophy)

