
# Representation

Question:

What is the importance of representation? Perhaps it has to do with how someone identifies, what a good life is for that person:

Consider someone say J, who was raised in the circus. Perhaps J’s parents were trapeze artists. Although this is not true of many, J wants to be just like her parents, more importantly, J sees her parents as someone she is supposed to be. She thinks about nothing else being a great trapeze artist and works very hard at honing her craft. In J’s eyes, no other trapeze artist could ever hope to be as good. Further, in J’s estimation, though she is not nearly as great of a trapeze artist as her parents, she is better than any other trapeze artist.

**J identifies as a trapeze artist.**

**J identifies as a great trapeze artist.**

Under a robust sense of representation, J experiences regret when failing to perform as she believes she ought to do given who she is.

As such, if someone where to attempt to represent the kind of person J is, they would want to show J as endeavoring to be a great trapeze artist, and experiencing regret when she fails to do so.

Analogously, if someone perceives a family member, or teacher as a great moral exemplar, and to the extent that they identify with that individual (perhaps it is a member of the community which they belong to, they share the same language, practice the same customs, have had the same immigration experiences, lived in the same community, etc.), then they would likely see themselves as a moral exemplar (vulnerable and reliant on other humans for their well-being), perhaps not at the same level, but better than others. They too would experience regret when performing a given behavior, they feel is not conducive of the kind of person they are. When one represents them then, they would want to show similar regrets.

