
---
title: "The Virtue of Humanity"
author: "Montaque Reynolds"
department: "Department of Philosophy"
school: "School of Arts & Sciences"
university: "SAINT LOUIS UNIVERSITY"
year: 2024
output:
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    toc: true
    toc_depth: 3
    lot: true
    lof: true
    number_sections: true
    fig_caption: true
    latex_engine: xelatex
    keep_tex: true
documentclass: book
fontsize: 12pt
linestretch: 2
geometry: margin=1in
bibliography: /home/redapemusic35/data_storage/Exported-Items.bib
csl: /home/redapemusic35/data_storage/chicago-fullnote-bibliography-with-ibid.csl
---

# The Good Life

I have found it difficult to explain to a seven year old why he shouldn't kill mobs in minecraft. Although this particular seven year-old will refrain from killing mobs in minecraft because he trusts my judgement, and so that when I say "don't kill mobs", he will generally say "okay, I won't, but why?"

This is where I find it difficult to come up with a reason that seems satisfying.

Consider deontology: do not kill mobs in minecraft because doing so will be treating them as an object. Well, they are objects aren't they? Consequentialists might point out that we are not hurting anyone. A natural law theorist? Is there a law giver, evolution, natural selection or God that would care?

Would God care? Why?

This question closely aligns with ones about whether and to what extent we should allow our children to play video games, watch certain movies, or what songs we might allow to be played in the house.

At the surface, this questions seem as though they have an easy answer. But often these answers are grounded either in one's accepted religion, culture, or more likely, some cultural behavioral practice. For instance, take someone who ascribes to atheist beliefs more generally. Such a person can identify with a strong professional social committement, and not allow, or endorse music that encourages unprofessional behavior. Let's imagine that they themselves had been born into an academic community.

We might initially think that there is no correlation between a person's character and their treatment of virtual objects. However, the point is not the connection as such, but rather the reason for their treatment of such objects. We will consider these to be *'circumstantial contexts'*

This paper argues that the reason has to do with the individual and how they respond given environmental constraints, and not the circumstantial contexts. The former has more bearing on the kind of character the individual possesses. As such, this paper presents a counter-cultural case for valorizing Christian Hip-Hop over and above commerical hip-hop as normatively ethnographic.

Therefore,

Another question: emotion, stereotypes, narratives, and reason.

***Emotion and Reason:***

> the emotion instantiates an appraisal of the value (to oneself or what one cares about) of that object. [@gilm20, 45]

The appraisal of objects defines a person's character.

What emotions are warranted and when?

## Country Music

As noted in emerging work on country music, there is a reason to think that a web of societal, historical, and temporal factors constructs social identity (McLean and Syed 2018). Authors have argued that the narrative implicit in country music’s aesthetic constructs the identity of the modern American Anglo-Saxon man (Mann 2008; Shusterman 1999; Meissner and Huebner 2022; Grossman 2002; Hayes 2010; Hollowell and Miller 2019; Hughes 2015; Watson 2020). But it is not clear who is the agent in such constructions. Critical race theorists also ask related questions regarding the social construction of the identities of racial minorities. As noted in the narrative literature, agency is a central concern on both accounts. Agency is rooted in one’s emotional experiences upon a retelling of their life story (Altshuler 2021; Velleman 2005a; Korsgaard 1996). More specifically, there are important relationships between narratives and an agent’s feelings, for instance of regret (Goldberg 2009), or pride, towards actions that one did or did not do. Using Mark Alfano, Cheong, and Curry (2022)’s Morality as Cooperation dictionary, I machine code an ethnographic account of agency by scoring the expressed relational virtues in popular song lyrics.

Consider expressions of materiality and sufficiency conditions for well-being:

*  Post Malone’s Rich and Sad: “All this stuntin' couldn't satisfy my soul (–oul), Got a hundred big places, but I'm still alone (–one)”. Contrast: [money] “couldn’t satisfy my soul” with [money] “could satisfy my soul”
* Especially as in Ty Dolla’s by Yourself: “Stacked your bread and bought your own Mercedes (Vroom, vroom). You your own boss, do it your way (Way)

## Emotional Disposition

Here, expressed emotional dispositions can effectively portray the endorsement or rejection of a given emotion state regarding how things went in a relationship, and subsequently represents a proposed inter-relational value. What emotional value (e.g., -0.531?) is the author ascribing to solitude in Rich and Sad versus the emotional value (e.g., 0.215?) is the author prescribing solitude in By Yourself. For my purposes here, there are three kinds of narratives that complicate a narrative account of agency and personhood.

* They include autobiographical narratives (McAdams and McLean 2013; McAdams 2014; Pasupathi 2016).
  * These narratives are internalized reconstructions of events.
  * They include an emotional evaluation of such events and taken as a whole; are central to a personal understanding of one is.
* Biographical narratives are externalized reconstructions of events.
  * They are culturally specific stories that are often.
  * accepted by the members of that society to either internalize or to resist (McLean and Syed 2015a).

## Extracting Sentiment

In this project, I consider extracted sentiment from the third type of narrative, what I refer to as literary narratives, to understand represented relational term objects in popular art (Mohammad 2021) as a type of biographical narrative.

* This will enable us to visualize emotionally relational content.
* By analyzing the sentimental content of music lyrics, I attempt to extract those phrases that artists attach the most sentient to.
* These include both negatively and positively valanced cultural ascriptions of social values among members of various populations. I ask what contributions these make in the construction of social identities.

## Method

My proposed research revolves around the fundamental question of whether there exists a relationship between moral knowledge and popular narratives, particularly those embedded within music. I argue this question is related to ones about moral testimony in literature on epistemology. Drawing inspiration from notable thinkers like Robert Hopkins, Nomy Arpaly, David Enoc, Laura Callahan, Jesse Prinz, and Michael Slote, who have championed ethical theories and those centered in moral psychology, such as emotionism and sentimentalism, I delve into the multifaceted claims surrounding the idea that these theories connect our emotions with our moral judgments.

In the rich landscape of psychological literature on narratives and narrative meaning, Jerome Bruner (1991), E.H. Erikson (1968), sees narratives as pivotal tools that inform our self-identity, and infuse our lives with meaning, a vital component of psychological development. But there are other philosophers who have also contributed significantly to literature on narrative. I follow individuals such as Eleonore Stump (2020) and Martha Nussbaum and anchor my research in the context of human well-being related to this body of literature. This work also draws upon psychological studies which emphasize the role of narratives in community-building, the formation of pro-social attitudes, and the enhancement of emotional bonds among a society’s members.

This work notes where other ethical theories like critical theory may overlook the significance of various sources of social identity, for instance popular music. In the pursuit of social equality, these views often fail to acknowledge contemporary methods of the construction of various identities. In my proposal, I consider the music genre as a form of literary narrative. I argue that the music genre, as a kind of literary narrative, can be useful in helping to form conceptions of narrative identity and therefore, there needs to be more work done on how such popular sources ground social identity. Following notable work on country music, I contrast country music with both commercial and Christian hip-hop to explore their representations of moral norms and social values. I contend that music genres can have potential value in helping to shape a community's inter-personal values. I argue that this can have implications for the well-being of a given community as noted most often in work on Country music. Drawing on moral epistemology, particularly moral testimony, and moral feeling, I argue that narratives in music constitute a form of moral knowledge by constructing social identities and linking emotions with moral objects. Thus, music plays a leading role in shaping social identities and can thus contribute to a community’s well-being.

## Research Proposal

My proposal addresses two key inquiries in moral epistemology and cognitivism. First, it questions the tenability of moral testimony. Scholars like Alison Hills (2009, 2013) and Sarah McGrath (2018) express concerns about the justification of moral actions based on testimony, as they may lack moral worth. I table this question to focus specifically on narrative well-being. This leads to the second question regarding emotions. While emotions towards fiction are common, their appropriateness varies depending on context, challenging the notion of apt emotional expression. In response to the challenge of apt emotional expression directed at art, I consider an ethic of care. Rosalind Hursthouse has noted once that virtue ethics enables us to perceive the complexity in moral decisions (1971). That it is not always the right apprehension of facts that counts, but rather sometimes it is the right attitude, facts about our emotions, that can be more relevant than the other relevant facts. I explore the relationship between fiction and moral understanding, contrasting standard epistemological cases with moral epistemological ones. I then delve into philosophical accounts of narrative, resting on the established proposal (E.g., Catherine-Harris 2018) that narratives offer avenues for affective moral understanding.

This involves appropriate feelings in response to moral situations as depicted in fiction. This project examines psychological perspectives on narrative, particularly those linking narrative understanding to human flourishing, whether narrative gets an account of human flourishing correct. Does a given narrative represent the emotions in each context in a way that would accurately represent a flourishing life? Does a given fiction represent sorrow in response to the loss of a close friend or apathy? Finally, it considers whether popular music, as a form of non-classical narrative, contributes to human flourishing and moral enhancement, by providing a comprehensive model that aligns with philosophical and psychological perspectives on narrative and well-being as apt expressions of care.
