# Social Reflection

The problem is that defending deference via cognitivism, fails to appreciate all the ways in which our faculties enables us to recognize the truth of a given moral proposition about the way that the world is. Especially that it neglects the important role that our perceptions play in our moral cognition. What it in effect says is that while we may be incapable of perceiving for ourselves the truth of a given proposition, our apprehension of the given truth by way of testimony or deference is a valid substitute. However, while this may or may not be true in the non-moral realm, I give some reasons to think that there is an asymmetry between the moral and non-moral realms with respect to such claims. We can come to know the truth about the way the world is in more ways than that recognized by McGrath and it may be possible that we have an ulterior obligation to do so. For instance, we can come to perceive the truth about a given proposition in the same way that we can perceive the sun shinning on our face. In the next section, I suggest that narrative is a form of moral testimony which fine-tunes those faculties central to moral perception enabling us to better perceive the moral truth of a given moral proposition.

Social epistemologists often question whether some individuals can have a better grasp on the moral particulars of a given social order, or given the current social environment, than others. Someone might know what to do relative to others, when conflicts arise among members of a given culture for instance. The concern here is that someone may strictly rely on another's testimony for their own moral views in a given context only. But while one action may be right in one context but not another, it is still possible that there is a general theory of rightness that explains why an action is the right one in one context but the wrong one in another.

## Epistemic Standpoints

Consider a case by @jone99. Peter lives in a cooperative house. Lately he has been feeling uneasy about the various decisions being made. In one case, the women in the home had withheld their support for several member applicants on the basis of sexism. Peter wanted to understand their allegations but was unable pick out the exact instances in question. Although with some cases, when the allegations were explained more carefully to him, he was able to understand the accusations, he was never able to see the evidence for himself. He was never able to point out specific instances without a careful explanation of why a certain look or tone of voice was deemed sexist [59--60].

Epistemic standpoint theorists such as @jone99; @coll05; @sain20; @long02; @hekm97; have given us some reasons in defense of such views. For instance, some individuals have a better appreciation of, or are better able to recognize some moral facts because of their epistemic standing in a given society or their own personal experiences. Such sensitivity confers moral worth onto an agent\'s action and while they may or may not think that the sensitivity in question cannot come by way of moral testimony, the problem with some accounts is that they fail to recognize the importance of moral knowledge for moral understanding.^[E.g., see @hill09c.] However, there are some accounts that provide room to go into this direction: "Reliably acting rightly is a part of having a good character, of course, but a good, virtuous person is someone whose whole self---her thoughts, decisions, feelings, and emotions as well as her actions---is structured by her sensitivity to morality" [@hill09c, 112]. Perhaps some of the confusion can be found in the possibility that these seemingly contradict this view: "Understanding is often associated with certain sorts of feeling: a flash of enlightenment; a light drawing. But these are not necessary . . ." [@mcgr19, 103]. Perhaps the confusion consists in the fact that while one can recognize both moral and non-moral feeling: ". . . respect for others can be a feeling which is not explicitly moral" [@mcgr19, 109], they may diverge some from the standard account. A point I worry about throughout this section, is whether feeling is distinctively important for moral consideration. This is perhaps what Scanlon hopes to show in his defense of irreducible normative reasons. This is because understanding requires more than knowledge or true belief in the way of cognitive appreciation of and facility with a given proposition--related reasons and reasoning [@call18a, 441], which for Scanlon are grounded in desire.

## Social Testimony {-}

There is one particular direction for moral action that is gaining increased attention recently, is that of the fundamental purpose of moral behavior. Traditionally, ethicists such as Jocke, Mill, Kant were interpreted as defending accounts of moral behavior based on logic, reason, rationality. However, if we consider, for instance, Mill's famous line about the end of all action being happiness, and his definition of such as being more comprehensive then that which would only be fit for pigs, a picture emerges of ethics as being part of what makes a life good or well-lived. Conversations about ethics may then be conversations about what makes a life good.

But lets imagine John. John is a professional soldier during a particularly fraught era in European history. As such, John has fought in many wars and has seen many good friends die. It may be that we can imagine John having difficulty having any sort of meaningful emotional attachment. For the cognitivist, John's emotional states do not matter. As long as John can recite the reasons why one does a given action, we might say that John *knows* a given moral proposition.

Assuming that John heard his commander give a list of reasons why a given action is right, and is able to appreciate why those reasons are valid, then John understands. Here, John has knowledge and understanding of a given proposition. Now lets imagine that both of John's parents have died recently. John's commander tells him to go to the store, buy a bouquet of roses, take them to the funeral, stay for one and a half hours, then he is free to leave. John faithfully follows the instructions his commander gives him, and accepts the reasons why these actions are the appropriate ones. If John did not have the experiences which he did, loosing many friends, seeing good people die, etc., we might find it odd that John isn't able to grieve on his own, but is told how to show that he is grieving.

The important point here, is that the emotional states which we expect John to have, have certain characteristic actions that follow them. Some think that moral behaviors too, can be actions characteristic of one's emotional state. This is because our faculties enable us to perceive moral properties. Some philosophers call this kind of perception sensibility and argued that our emotions are representations of this special kind of sensibility.^[Early sentimentalists included David Hume, Francis Hutcheson, The Earl of  Shaftsbury and Adam Smith] We can imagine earlier in one of the wars John fought in, that his friends were stuck behind enemy lines. John successfully motivates the unit he is a part of to conduct a very risky mission to free them. The only reason why they do so however, is because of a complex set of emotions which they all experienced upon hearing what happened to the friend's unit.^[@aris99 provides a well-known of moral virtue based on close intimate relationships.]

If this is right, then what it shows us, is that morality is affective. It may be a good state of affairs for Peter to be able to trust reliable sources when he himself lacks the perceptual capacity to see what his moral obligations are in some given circumstance. However, a better state would be one wherein Peter acts out of direct rather than indirect appreciation for the right reasons. The important concern here is whether such perceptions are necessary or only sufficient for morally worthy action. An emotionist is going to say that such perceptions are necessary for morally worthy action. As such, morally right reasons here are essentially related to one's emotional states. Acting for the right reasons, means being moved by the appropriate feels [For some important emotionist theories, see; @darw92; @mcdo85; @wigg87].

This helps us to understand why reasons are irreducibly normative, and because they are, moral testimony should motivate such reasons. Narratives have often been supposed to do just this. However there are some points that should be stressed first.

There are often varying levels of truth found in narratives and as such, narratives are not always accurate with respect to various truths. A literary artist for instance, may imbellish on one claim while truthfully expressing another. For instance, a comic book author may create a character with super hero strength and the ability to fly, in order to communicate the importance of responsibility with one's unique strengths.

However, I suspect that some falsehoods are even more problematic than those often presented in narratives of virtue. Compare an individual with malevolent intentions falsely portraying members of a community. Because he dislikes the members of that community, or holds particular biases about what kinds of character the member possess, he intentially portrays them in such a way that will skew the public's perceptions of that community's members. Maybe with the intention of motivating beliefs about *what they are like* to more closely resemble those that he holds. Fans of a certain sports team may falsely portray fans of the opposing team at a sporting event by falsely representing them in a given false narrative, e.g., *Raider's fans are all violent*. Perhaps, regardless of the intentions of the one portraying falsehoods, some falsehoods cause harm while others elevate.

One available explanation as to why some inaccuracies are more harmful than others, is that when maligning others, we think that we have an obligation to be as truthful as possible. This is because the harms here outweigh the benefits. We are harming a particular person. In the virtuous narrative, the benefits provided by moral education outweigh the harms of inaccuracy with respect to the truth. As such, there are two kinds of inaccuracy in the narrative. One concerns the inaccurate narrative of the malicious individual attempting to harm others, while another seeks to represent reality. They lie (or embellish the truth) in order to communicate some aspect of moral reality that would be difficult or impossible to do without such embellishments.

This suggests that narrative accounts have an obligation to faithfully represent the landscape in a way dis-analogous to narratives of non-normative facts about the real world [E.g., @nuss83]. Facts such as the chemical composition of pool cleaner for instance. But we are still concerned with facts. As such, truth, faithfulness and accuracy are still requirements for representing the moral landscape. But this says nothing about our emotional responses. Our emotional responses to fiction aid in our moral understanding of a moral proposition. If an audience member is unhappy with the emotion prescribed by an artist, she declines engaging with that work of art. Even more damning for my argument, is the fact that sentimental optimists accept this conclusion. Only some literature is a source for moral knowledge. Accordingly, while some literature is a source for moral knowledge with the potential to undermine knowledge about moral reality, this is not the case for all literature. The rest is merely a-moral.

Similarly, relying on testimony in a range of situations confers justification to one’s belief of a proposition. In a robust sense for example, when a child obtains true beliefs from a reliable source, for instance in primary education, we credit her with knowledge [e.g. @mcgr19, 65]. Similarly, the student who sits through forty hours of lecture on thermonuclear astrophysics has more justified beliefs about thermonuclear astrophysics than the student sits through five. However, the main reason for relying on moral testimony is not primarily to confer justification, to justify her beliefs, but rather to motivate behavior. To be trusted with the kinds of finances required for testing one's theories regarding thermonuclear astrophysics, one might need additional lecture hours in addition to a proven research record. There are several reasons for this. The person who holds justified non-moral beliefs on a topic, confirms or disproves the beliefs of others. Our own beliefs are justified by those who have justified beliefs, or who possess a greater degree of justification. Therefore, relying on justification to confirm that our moral belief is the correct one, leaves a lot to be desired.  As such, the epistemic state that we care about in cases of moral testimony is understanding and not knowledge. The point of contention here is a difference between the epistemic state of knowledge and the one of understanding.  Knowledge is knowing *that p*, that a given proposition is true or false, while understanding is knowing *that p* and *why* *p* is the case. This is perhaps a reason why a number of authors recognize a deep connection between narratives and moral knowledge [@nuss90; @stum10]. We may think that what these authors mean by moral knowledge, is a richer state of understanding.

Additionally, authors have argued that the connection between narrative and moral knowledge has to do with a narrative’s ability to express important moments in a character’s emotional and moral development [@stum10; @nuss83; @nuss85, @nuss01; @arpa04; @zagz17; @harr11; @dol18]. Mr. Jones is an FBI operative tasked with observing and reporting on the activities of Mr. Smith, who is suspected of robbing a bank. Accordingly, Mr. Jones is being asked to give a first person account of the life and actions of Mr. Smith. Such accounts would clearly state that the observations being performed, are being done by Mr. Jones. "I, Mr. Jones, have observed the suspect, Mr. Smith, on the morning of ...". But assuming that Mr. Smith has been brought in for questioning, the detective on the case, wants more information than that which can be provided by Mr. Jones. If Mr. Smith chooses to be cooperative, then the detective may want to know *why* Mr. Smith robbed a given bank on a given day. While Mr. Jones may be able to give his assessment as to Mr. Smith's motives, he would not be able to do so in the same way as Mr. Smith. Mr. Jones can give a first person account of his observations regarding Mr. Smith actions and the motives he attributes to Mr. Smith's actions, and a third person account, for instance "Mr. Smith told me . . .", "or I obsevered Mr. Smith making pottery", he cannot give a second personal account as a matter of reporting because such accounts are intimately relational. Such accounts would provide Mr. Jones with an awareness of Mr. Smith as a rational or not sort of agent because Mr. Jones would understand Mr. Smith's motivations as a matter of experience rather than reporting and third party observation. Such an account from Mr. Smith would enable reciprocal understanding of the other's moral autonomy.^[See @darw13c]

Narratives can be a source of second personal knowledge where through narratives, we develop close relationships with characters in narratives [@stum10, 78]. We might think this is plausible assuming that a narrative has an ability to represent these important moments contributing to our sense of familiarity with them. Perhaps we then grow along with the individual through the narrative. We experience moments of hardship and joy, and other defining moments which often contribute to our understanding of the world as potentially experienced by that character. It is not immediately clear what this has to do with moral understanding of a given moral proposition. The standard argument is that narratives are a form of moral education. However, this connection spans two separate concerns. First, there is the less controversial worry about moral testimony as a source for moral knowledge [@hill09c; @hopk07a; @nick01; @enoc14]. However, this can lead to questions about the perceived relationship between art and ethics, an issue that is more contentious [@gilm20].

While Stump suggests that we can understand narratives as a source of moral knowledge, the psychological implications, the processes involved, are not immediately clear. For such an account to develop beyond folk psychology, it will be helpful to distinguish between several psychological accounts of moral development. On another similar account regarding second-personal testimonies, @nuss01 has defended an interpretation of Greek tragedy wherein the project of Greek tragedy is that it enables us to get a sense for just how fragile a good human life is. Ultimately, Nussbaum concludes that the most important feature of a good human life are our relationships with other persons. According to Nussbaum, tragedy as a form of narrative is important for its ability to communicate this intrinsic feature of a good human life. For instance, in Pindar’s version of Aeschylus’s Agamemnon, when Agamemnon sacrifices his daughter to meet his obligations to Zeus, he does so without any sense of the emotions we would expect one to have in a similar situation. As such, Agamemnon fails to recognize the moral conflict Zeus’ demands have placed on him, the moral conflict undergirding his competing obligations to Zeus and Artimus. While narratives are often thought to communicate the emotions experienced by a character second-personally, in this telling of Agamemnon, narratives express what it would feel like when important emotions are vacant.

What is attractive about narrative is that it gives us insight into what communities plausibly care about, thereby helping us to understand what we may care about. Oftentimes, when we think about psychological disorders, one trait that many of them have in common is that they undermine the sense of connection that we may experience with other members of a close community of people. For instance, individuals with various mental health differences, may often lack recognizable expressions of empathy, and as a result, experience social isolation, or fail to show markers of human connection, such as eye contact. The point here is that our ability to share the perceptions of others may make up an intrinsic part of who we are as a species, the relationships that we cultivate with one another.

For instance, works geared towards pleasure as @gilm20 argues, are not intended for moral knowledge and therefore it is a matter of controversy whether they are unable to undermine moral knowledge. If the work is particularly morally problematic, then perhaps the author or audience is culpable, i.e., Birth of a Nation, but not the work. Importantly here however, there are many ways in which culpability of the audience can be absolved. Perhaps a certain segment of the audience is only interested in the historical facts surrounding Birth of a Nation, or the aesthetic qualities of the film, perhaps another segment of the audience is interested in the technology which led to the creation of the film. But the worry here is that on some level, there is a market value for such films which justifies their place in the market.

To fix this, I suggest that narratives be defined as any work which represents human emotion in the context of human other relationships. In the context of human relationships, justice is often prioritized as the framework that best organizes such joint activities. However, given the above concerns surrounding moral testimony, we might think that an ethics of care will provide the best framework for understanding the importance of narratives for moral knowledge. On an ethics of care account, a systematic way to recognize moral frameworks in narratives would modeled on a sentimentalist ethic. Such an ethic could enable us to recognize moral testimony as a source of moral knowledge in a way other ethical theories are incapable of. Such accounts of moral testimony necessarily include narratives and therefore on an ethics of care account of moral testimony, narrative is an important source of moral knowledge not recognized in the literature as a kind of moral testimony.

Future directions of this work then could highlight the asymmetry of moral testimony in its ability or inability to confer morally worthy affective states. Critically analyzing literary examples might show the importance of affective states in moral reasoning and how without appropriate affect, something is missing in moral action. For instance, we might consider the ability of some given love song to stir our emotions in the way a love affair ought to. Because of the importance of affective states in moral reasoning, and how narratives are supremely important for showing this relation, future work would look at relationships between narratives and morally worthy action, starting by looking at specific conversations between those who think that our emotions towards fictions are governed by the same criteria as our emotions towards situations in the real world, and those who disagree.^[See @gilm20; @stum10; @nuss01; @nuss85]
