# Equivocation and Imagination

It may not be initially clear, but this is a video about philosophy . . . well that and the Space MMO Star Citizen. What does the one have to do with the other? In my previous video, I briefly expressed the hope that virtual game worlds can be used to teach us about our philosophical intuitions, including moral, ethical, metaphysical pre-judgments. However, many may justifiably think that this is a fools errand. They are going to say that philosophical exploration and analysis requires that we leave the extra curricular behind.

That the virtue of the philosophical method is its semantic precision. Each word choosen for a specific purpose, that only that word could fulfill in that context. This philosophical insight requires that we directly articulate the nature of a given problem, and clearly and concisely explain counter examples, expressing our reasons in a way they can be understood by anyone, and that there force is immediately recognized, it enables a special kind of insight. The narrative arts, movies, fiction, etc., complicate such explications.

Welcome to the next episode. If you recall, previously, which you will see a link for here; we discussed the puzzle of imaginative use, which is a question about how a game's transcendent properties help us to learn something about the real world.

As I alluded to in that video, Star Citizen is an ambitious Space MMO, which makes it something like a communally played game. But you don't have to *play* the game, and that, in my opinion is what makes it special. So what game will we play instead?

When I was younger, there were games like Mario World, The Legend of Zelda, Pong. These games gave you a well defined goal, and specific constraints that were placed on you in completing a goal. In order to participate, you had to play the game.

You could not harvest the plants in Zelda, or cut down the flag pole at the end of the first level in Mario, build a home in Pong, etc. You could play other games, for instance performing a speed run where the object is not to kill the npcs, but to get to the end as quickly as possible. You could kill only blue targets, or avoid leveling up for as long as possible.

Many games coming out now, attempt to give the player as many choices as possible, many more than these other player defined choices. More importantly, by doing so, we are not running afoul of the aims of the developer. The developer wants us to define our own objectives. So *these* choices aren't just choices about how to progress through the game, they include choices about what progression through game means for the player.

Star Citizen is like this. I might have a goal to fly to Microtech, sit on the bank of a stream and eat lunch. I've experienced watching the sun rise on the surface of a moon and taken note of the difference in build quality for a ship like the 890 Jump and Drake Cutter. Some of my more memorable moments in the game have consisted of reflecting on and admiring the wood paneling embedded seamlessly in the floor running along the edge of the carpet in the former, in contrast to the riveted paneling in the latter. But what do such experiences, experiences of trancendence, have for learning facts about the real world? This is a puzzle, hum.

Philosophy is filled with puzzles, from Meno's paradox, to the problem of other minds and the experience machine to mention a few. The puzzle of imaginative use questions why one mental faculty, namely imagination, can be used for both transcendence, play, absorption, entertainment, and instruction, planning, discovery.

Does a game like Star Citizen offer a better chance at teaching me something since it does afford me more opportunities to engage my imagination than Mario Kart Racing.

In Star Citizen, I could race, say for instance if I decided to participate in one of the yearly races on Daymar, or I could refrain from doing so and lay down in the grass and gaze up at the sky through the leaves of a forest on Micro Tech.

More importantly, how can a mental faculty that seems primarily dedicated to pleasure, experiencing my reflection on a simulated pool of water, and entertainment for instance flying a Terrapin with my friends, and absorption grinding a mining loop so that I can save up for the Origin 325i, uses which are transcendent, also be used for instruction, such as when planning for the future. What can Star Citizen teach me about the real world? The hear and now? The twenty-first century? While I might learn what ship to purchase, or discover what I should take with me when embarking on a mission in Star Citizen, say food and water, do I also learn what car I might purchase when considering a new business endeavor, or what to take with me when driving cross-country to visit in-laws in the real-world?

In a collection of views about the potential for the instructive uses of the imagination, Amy Kind and Peter Kung in *Knowledge Through Imagination*, argue that the way forward, explaining the instructive use of the imagination, requires being able to recognize when constraints are placed on imagination.^[@kind16] When the proper constraints are put into place, then imagination can help us "discover truths about the real world". It is not initially clear what these constraints might be at the outset however, but if this is true, then Star Citizen should have restrictions in place to satisfy the epistemological aims of man-kind.

Fortunately however, I think that their solution does appear to be what Star Citizen is aiming for in its game-play. Namely modeling the real-world where choices are not forced and outcomes are not indefinitely fixed. Initially then, it might be difficult to square this with the solution suggested earlier, that to explain the instructive use of the imagination, we have to first be able to recognize what constraints exist in the game. Only when we understand what is metaphysically impossible, do we begin to understand what is metaphsyically possible and thereby discover through imagination, something true about the real-world.

Continuing on, in future videos, I will explore other attempts at solving the puzzle. These include the equivocation view, three historical treatments including Descartes, Hume, and Kant. Three contemporary views, including Kendall Walton, some Modalist views, and mind-reading, or knowledge or other minds, whichever locution you prefer. Finally, we will look at Kind and Kung's own suggested constraints and ask ourselves how these views are exemplified in the Star Citizen universe.

## Taxonomies of Philosophies

For those are stumbling on this video for the first time, this is a discussion about the philosophical puzzle of how a single mental activity can be both transcendent and instructive at the same time. If this is your first time with us, I will recommend that you go back and watch *Part I of Imagining a Philosophy of Star Citizen*. In this video, we will be covering with more depth the equivocation solution to the puzzle of imaginative use. According to it, the way we explain how the one mental state of imagination can be used for both instructive and transcendent uses is because philosophers equivocate between different senses of imagination.

One helpful way to understand the philosophical discipline, is to first recognize how enduring philosophical questions have been divided up into subdisciplines. These often are presented as puzzles.

They include Metaphysics, questions about the nature of reality, time etc. Well known questions in this genre include Saint Anselm's Ontological argument. God is a being greater than any being that can be conceived. If you imagine a being that is omniscient, omnipotent, omni-benevolent, then this is by definition God. However, the second premise asks you to consider the non-existence of such a being. Here is where we run into a conceptual contradiction. Existence is greater than non-existence, and therefore a being that is omnipotent, omniscient, omni-benevolent, but does not exist cannot be God. Therefore, it is impossible to imagine such a being that does not exist without contradiction.

Questions in epistemology include questions about the nature of knowledge, Value theory, questions about the nature of what we value, or what is valuable. Included in these questions are those about ethics, right, good, etc., aesthetics, beauty, etc., etc. and so on. For a helpful outline, you can peruse [PhilPapers](https://www.philpapers.org).

Given that we are talking about games, we might be asking questions about art, the beautiful, and representation. But while this is plausible, and there are very good discussions about video games and video game properties (including one that I hope to do a video in the near future on the in universe work of art *Tears of Fire*) among other discussions about the nature of the beautiful, this is not that.

Within the disciplines of metaphsyics and epistemology, there are questions about the nature of internal mental states. I guess a question about metaphysics can include questions about the correlation of mental states with brain states. Does one directly infer, or is entailed by the other? Are mental states distinct from brain states or are they identical? While it might be appropriate to correlate brain states with mental ones, within the domain of philosophy, we still treat the two as distinct from one another. But those are questions for another day, in fact however, we are getting closer to our original topic. I apologize for the digression.

When speaking of the metaphysics of mental states, it would be helpful to talk about what we mean by mental states. Perhaps you will have already guessed what we mean by mental states, but it is important to be precise and specific. So in the interests of clarity, I will first give some examples, these include desire, belief, and attention to name but a few. Why is attention a mental state? Well, imagine that your wife is telling you how her day went, which bills are coming due, the friend she met at the gun range etc. She ends the dialogue with a question, what's for dinner? and you respond: that's nice. Well, you were not paying attention and now you've been caught and she calls you out on this. Further, she now *has* your attention. What was your state of mind before, and what is your state of mind now? What distinguishes one from the other? Further, there are two mental states of concern here, attention and in-attention. What does each look like and what are their natures?

This is an interesting question for Star Citizen. How many times have we failed to pay attention and lost cargo and other valuable loot because of a mental distraction or other? How many of us have run full speed into the salvage vehicle we were navigating towards and failed to pay attention as we got closer to it? But this question does finally get us closer to the original, I recognize that this video is taking longer than it needs to, I apologize.

I digress yet again.

Ultimately, what is it like to fail to pay attention to an imagined scene? Isn't that what we are doing? Imagining that we've just traded valuable currency for an imagined wreck, from which we can derive valuable cargo and imaginatively sell this cargo for more valuable currency? While I am not in a position to answer that question, a question more near our initial one is what can our imagining in Star Citizen teach us about the nature of our various mental states? Including attention, inattention, and imagination itself? Therefore, perhaps by engaging in imaginative exercises, for instance those afforded to us in games like Star Citizen, we can better understand important truths about the real world such as the nature of mental states like imagination, attention, desire, etc. Of course, in looking at questions regarding the nature of a single given mental state like imagination, we can make our job of analyzing such a state easier by once again breaking it up into smaller questions, such as what are some of the functions of imagination. Here we see two. These include transcendent uses and instructive ones. And here we've come around full circle back to our initial question, namely how can we have the one without the other? From here then, we will look at our first proposed solution.

### Equivocating Solutions to the Puzzle

What is imagination? Notice how we skipped over the question about what are mental states? A reason why we've done this is because sometimes it is helpful to break up larger questions into more manageable ones. When we asked what mental states were, the best answers we could give are examples of things we think are mental states, for instance desire, belief, imagination, attention and so on. So since the best we could do was give examples of things we think are mental states, it becomes obvious that one way to understand the bigger question about mental states, is to explore things that are mental states. That brings us here, to the mental state of imagination.

What is imagination, what counts as imagination? Perhaps transcendent uses of the imagination rely on one concept of the imagination while instructive uses another.

> If there are different senses of imagination in play in philosophical discussion, then perhaps it is imagination in one sense that is responsible for the transcendent use of imagination, while imagination in some other sense is responsible for the instructive use of imagination.

Well, we know that it is a mental state, but what is its nature or essence? Here there are many possibilities available to us. This is because many different philosophers have given different answers to this question. This fact about historical treatments of the imagination has been cited as a reason why the puzzle of imaginative use persists. This is called the equivocation solution. According to it, when we focus on the transcendent uses of the imagination, we are talking about one set of proposed natures, while talking about another, we are focusing on the instructive uses.

Lets begin with an example. What if history extended beyond earth history? For instance, Star Wars is said to begin eons before human civilization on earth. The lore regarding the Star Citizen timeline models a similar history. According to it, the recorded history of the Xi'an empire begins during the earth year 300,000 BCE. However, the in-game events take place in the earth year 2954 and the player does not play from the perspective of the Xi'an, but rather from that of human society in the current earth year 2954. In consequence, those individuals participating in the imaginative enterprise that is Star Citizen are being asked to imagine that 930 years have elapsed from the time they first opened the RSI Launcher until the loading screen has finished its cycle and the player presses *F* and "gets out of bed".

There is also extensive documentation detailing many of the other imaginative requirements for successful participation in the game. These include the immediate experience of thirst and hunger upon opening their eyes. Perhaps developing a plan for "that day in the verse" which might include looking for lucrative bounties or cargo missions. Perhaps they have been saving their UEC credits for a particular ship and now they finally have enough. Maybe they have been saving the coordinates of a scenic mountain range on Microtech and they now finally have the real-world time available to visit this mountain range.

But notice here that some imaginations are necessary for participation in the simulation while others are contingent on the aims of the player. Is the former a more pure case of imagination while the later is not? I cannot avoid imagining that I am experiencing hunger and thirst. There have been many times that I have wanted to. I might be excited about climbing aboard a new ship and traveling to a package location. But then I look to the lower left of my screen and my "mobiglass" is telling me that my hydration is at 13%. I try to ignore it because it takes time to source hydration and I would rather spend that time flying my new ship rather than sourcing hydration, especially given that there are real-world time constraints that place demands on me in addition to the imaginative ones. But if I ignore the image the game is forcing on me, I will be ejected from my desired imaginative state, flying my ship, into a new one, namely waking up in a hospital bed.

But does this forced imaginative activity differ from the following, waking up at Port Elisar and flying my new ship to New Babbage to meet up with some friends. Meeting up with my friends at New Babbage is not necessary to participate in the imaginative activity that is Star Citizen while "eating and drinking" is.

Some imaginative activities are contingently necessary. A contingently necessary imaginative activity is an imaginative activity that is necessary for an additional imaginative activity. Notice how eating and drinking might qualify as such. In order to fly my Aurora, I need to first eat and drink. However there are better examples, for instance, earning UEC credits by doing various tasks in order to buy a cargo ship that further enables me to transport cargo from one location to another.

One way we might define such distinctions is through the philosophical literature on imagination. The distinction is between imagination from the inside and imagination from the outside. Kind and Kung ask us to imagine ourselves skiing versus imagining ourselves having frozen cheeks on account of skiing. But once again, I think that Star Citizen can present us with a better example.

We might focus on our internal states of desire here. Internally, I have a desire to race in a canyon on Delmar. But it seems that my character has an ulterior desire to eat and drink, don a helmet when in a low oxygen environment such as space or a non-terraformed planet etc. In part, there is a connection between my character's states of desire and my own. Namely they are contingent, for every internal state of desire that I experience, fly among the stars, dip my hands into a stream, meet friends in a bar on New Babbage, my character develops a contingent set of desires.

The way Kind and Kung articulate this development is by pointing out that an important distinction regarding imagination from the inside versus that from the outside plays a role in predicting how we react to given scenarios. My desire to witness first hand the corrosive effects of the ocean on Crusader will enable my friends to predict that I am likely to "fly" to Crusader. Therefore, it may at first seem that the equivocation view is highly plausible. The fact that I can make predictions about what one is likely to do given a particular imaginative activity, infers that the instructive uses of imagination rely on imagining from the inside.

But what happens when we consider that the point of the imaginative activity is to be able to pan the game camera out to the third person view and *see* what one *would* look like if he or she were to stand on the shoreline of a maximally polluted ocean? This is imagining from the outside and yet, it still might be instructive. Or lets consider the in-game feature that allows us to try on items such as armor and fashionable clothes prior to purchasing them with UEC credits. I might do so to learn what they look like on my character.

Each of these examples seem to suggest that both imagining from the inside and from the outside can be instructive, or transcendent or both. As such, the equivocation is not really helpful for solving the problem of explaining how one mental activity can be both instructive and transcendent.
