# Biotechnology and Bioengineering

Star Citizen is a space simulator, sandbox, MMO that is set 930 years into the future from our current timeline. In this imagined future, like many imagined futures, humans have developed a number of transformative technologies that allow them to operate in environments previously unimaginable. These transformative technologies include various kinds of armor used for a variety of purposes, from mining deep underground or in space, to engaging in combat. Armor here has different kinds of practical purposes, keeping the wearer warm, cool in adverse whether conditions or protecting them from shrapnel and other projectiles in hostile environments.

In our own timeline, unlike that of Star Citizen, we are only now having to consider to what extent we should allow emerging technologies to influence and change human biology. When considering the impact that technology may have on human biology, we might consider a number a terms used to describe such interactions. Biotechnology is one such term, and is typically defined as the "manipulation of biological systems and organisms through technological means" [@fala24, 295]. The kinds of interactions between human biology and technology under the umbrella of Biotechnology, are performance enhancing drugs, stem-cell research, genetic engineering, cloning, and genetic screening to name but a few possibilities.

What does transhumanism have to do with Star Citizen, when this might on the surface be obvious. However, from the perspective of the lore surrounding the development of the game, it is not as obvious as one would think. One constant fact about game play in Star Citizen, is the length of time often required for the most trivial of pursuits. In most games, an individual logs in, and can engage in game play almost immediately. However, here Star Citizen, in the interests of immersion, that facet of game development that seeks to represent the real world as much as possible, differs from most games. At the start of a typical game session, an individual logs in and finds themselves in a habitation unit. This is a shelter where you "live", or one where you might have logged out during the previous game play session. From here, depending on what you would like to accomplish during that session, you will walk towards some type of transportation platform. You will then take something akin to a shuttle to a platform. Here you will take an elevator to your hanger, recall your ship, fly to a location etc etc. All of this takes time, lots of it.

A mistake I often made in the beginning, is the subject of this portion of the video. Namely forgetting to source nutrition and hydration, which are necessary for game play. There is often a visual representation of your state of health, including your hydration levels, in the bottom left corner of the screen. This tells you how long you have until you need to rehydrate or taken in nutrition. Rehydrating takes time because you have to source hydration which is available on kiosks at various locations across the game. More additionally, you have to walk to these, which once again takes time. However, you can always carry various drugs. Would it be wrong to, say inject yourself with a drug solely for the purposes of mitigating the adverse affects of dehydration or nutrition deprivation? One distinction that is important for consideration here, references the kind of drug, of which there are two. On the one hand, taking a drug to mitigate the effects of disease, it would most likely be a therapeutic one. However, if I am merely looking to improve my performance, say avoid the need for nutrition or hydration, then this would be enhancing. There are not really such drugs on the market currently, although we are getting close with various nutrition supplements. These often mitigate the need for more robust nutrition intake in the interests of gaining muscle mass or loosing weight. But there are other enhancing drugs which are quite prevalent in many first world nations, for instance taking Ritalin even though one does not have adhd.

Um, that was tasty.

A constant in human innovation has been the improvement of technology for a direct benefit to human lives. This includes being more efficient with respect to resource management and production, warfare, environment management, habitation and so on. More importantly, when considering the distinction between healthcare and human enhancement, bioethicists often promote three distinct aims. These include beneficence, autonomy, and non-maleficence. Arguably, a given health procedure should pursue the three. This means that a health procedure should be beneficial, performed with respect to the patient's autonomy, and not intended to harm the patient. But this leaves a lot of room for enhancements to human biology and it is not clear what lines should be drawn. One possible ethical commitment is a kind of consequentialism, namely that the consequences outweigh other considerations with respect to the moral value of a given action. Nick Bostrom is one such philosopher who embraces transhumanism as a biotechnology that produces good consequences. On the one hand, embracing whatever technological advances contribute to more well-being overall might be morally obligatory for a utilitarian like Bostrom.

For instance, if we consider cognition to be a kind of resource, then developing drugs which improve cognition is no different than creating a system that enables us to more efficiently manage food crops. More efficient use of food crops means that they can be enjoyed by more people. The more people who can make use of such crops, means that the well-being of more individuals is promoted.

One particularly important area of improvement for technology, has been those improvements of technology with respect to the benefit of individuals with disabilities. However, it is not clear where we have always drawn the line here, or whether we need to. For instance, while some drugs and treatments were initially created for individuals with disabilities, they are often used by individuals without disabilities. Is inability the same thing as disability? I am unable to fly while birds have no trouble doing such. I can mitigate this fact by buying and building a hobby kit plan, allowing me to fly like a bird. Why shouldn't I take drugs to improve my cognition or pursue treatments that do the same? If I could take a drug that enables me to play the violin like Itzhak Perlman, why shouldn't I?

Consider whether some individuals have a cognitive advantage over others. Is it justifiable to use technology enhancements to decrease the gap in cognitive performance? What about physical advantages? Is it justifiable to use technology enhancements to decrease gaps in physical performance abilities? What about individuals without quote unquote disabilities? Would it be fair for these individuals to make use of technology to boost their performance, whether cognitive or physical? We live in a day and age where many technological advances are forcing us to confront such questions.

In Star Citizen, such questions have seemingly already been answered in the form of various technologies available to the general public. But what advancements in Star Citizen would be considered controversial today? One such controversy includes the wealth gap between those who can afford to engage in interplanetary travel, namely the player's character, and the many NPCs that inhabit the various space stations and outposts around the system. These NPC characters often remind me of retail employees given their seeming lack of enthusiasm and drive. Additionally, it is impossible that such individuals are earning the credits necessary for living similar lifestyles as the characters us players play as. Further more, according to lore, there is an important distinction between "citizens", a group which we as players belong to, and non-citizens. My initial assumption as that the NPCs who inhabit and work the various kiosks that we purchase goods such as weapons, armor and drink, likely do not belong to this class. What medical technologies are they prohibited from possessing on account of this fact?

Such wealth gaps become important to consider especially when we include the access to medical innovation that "us Star Citizens" possess. Our access to performance enhancing drugs is one kind of such access. These drugs include Demexatrine, which relieves muscle fatigue and concussion symptoms; Roxaphen, alleviates symptoms that hinder movement, typically as the result of injury; and Sterogen, symptoms related to muscle weakness. Such individuals will have an unfair advantage in improving their social stature, for instance, mining rock which can be quite lucrative but is also physically demanding. Performance enhancing drugs like those mentioned above, would be very beneficial when performing such lucrative activities.

What about individuals with unequal leg lengths? It is now possible for them to have a surgery which increases the length of one of their legs to make it the same length as the other. But what about elective reasons for such surgeries, for instance the person who always wanted to be an even 6 feet tall? Cosmetic height surgery is an elective surgery that individuals pursue for the sole interests of being taller. Is there a limit to what kinds of cosmetic surgeries are allowed by the FDA? But what about practical uses of such surgeries, for instance perhaps an increased height might be necessary to pilot some ships or don some armors.

Each of these questions fall under a more general one. Trans-humanists allow that human progress will necessarily involve therapeutic and enhancing applications. Therapeutic applications benefit individuals with what are typically described disabilities and diseases while enhancements are applications that benefit individuals without industry defined applications. Where transhumanists different from a more conservative approach is that they will also allow enhancing technologies arguing that transform human experience overall.

In our own timelines, many deaf people have recently been using a device called a "cochlear implant" to mitigate the effects of their auditory disability. A cochlear implant is an electronic device that "bypasses the ear and connects directly to the auditory nerve". This seems to be an admirable use for such a device since it allows the wearer a sense of autonomy that perhaps was less available to them previously. They can now have conversations with others who perhaps do not know sign language, say the worker at the Department of Motor Vehicles. However, surely such a device might be also put to good use by someone without a defined auditory disability. For instance a soldier who would benefit from having more sensitive auditory equipment directly implanted into her skull. Developing this technology is an example of bioengineering, which is the application of biological science to design machines. It is not clear whether such biological enhancements are necessary for us Star Citizens.

Are neural implants used to create an interface between our brain and the armor we wear? What about piloting our ships? In Eve Online, another space sim, sandbox, MMO, the player has been bioengineered so that the ship they fly becomes an extension of themselves. We do not have a similar lore in Star Citizen. But it is possible that our ability to pilot the ships we pilot, was augmented another way. For instance, most pilots in our own timelines need to be in peak physical condition at all times. Piloting planes is very taxing on the human body. It only stands to reason that piloting space-ships is infinitely more taxing, especially through wormholes and in quantum travel. What is the lore surrounding the ability of so many individuals to meet the demands that such travel obviously present?

One possibility is a robust eugenics program. Eugenics is the science of improving the genetic components of a species. Examples can be seen when comparing corn samples from hundreds of years ago which looked more similar to wheat, to those we might find in the supermarket today. Not only would it have been effective in eradicating hereditary diseases, but also improving the cognitive abilities of the average person in the same way that corn has been improved over the centuries to be more nutritious. Once again however, this could be where being a Star Citizen would have been necessary. Inhabiting such a class would likely provide certain benefits that enabled access to such a eugenic program, or the medical technologies that allowed an individual to select certain traits that they desired their offspring to possess.

Since world war II, eugenics programs have become wildly unpopular for obvious reasons. However, what is less obvious, is the possibility that though unpopular, such programs still persist in the form of IVF and other fertility treatments. When selecting sperm and eggs for such treatments, it is highly unlikely that fertility patients will actively pursue specimen from low level criminals or retail employees.

But other concerns include the wishes of the potential individual. To what extent does an individual have autonomy regarding who they want to be? Do we have the "right to an open future" as some suggest? Or is it the case that improving one's biology actually have more, not less, options available to her. For instance, there are developing technologies that allow scientists to modify the genes of an embryonic cell, what Rosemarie Garland-Thomson has called "Velvet Eugenics". This is different from selective breeding, which might be compared with how an individual chooses a romantic partner, as it entails actively seeking out those traits that a patient doesn't want, and removing them from the genome of the potential embryo. Lets imagine that a parent does not want to pass on their genes that contributed to the fact that they write with their left hand. Bioethicists have asked whether the potential individual should have a say in whether they wanted to be left-handed or not.


